/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AFHTTPRequestOperation.h"

@class NSString, NSError, NSObject;
@protocol OS_dispatch_queue;

@interface AFDownloadRequestOperation : AFHTTPRequestOperation {
	NSError* _fileError;
	id _responseObject;
	BOOL _shouldOverwrite;
	BOOL _shouldResume;
	BOOL _deleteTempFileOnCancel;
	NSString* _targetPath;
	NSObject<OS_dispatch_queue>* _progressiveDownloadCallbackQueue;
	NSString* _tempPath;
	id _progressiveDownloadProgress;
	long long _totalContentLength;
	long long _offsetContentLength;
	long long _totalBytesReadPerDownload;
}
@property(assign, getter=isDeletingTempFileOnCancel) BOOL deleteTempFileOnCancel;
@property(assign) long long offsetContentLength;
@property(assign, nonatomic) NSObject<OS_dispatch_queue>* progressiveDownloadCallbackQueue;
@property(copy, nonatomic) id progressiveDownloadProgress;
@property(assign) BOOL shouldOverwrite;
@property(readonly, assign) BOOL shouldResume;
@property(retain) NSString* targetPath;
@property(retain, nonatomic) NSString* tempPath;
@property(assign, nonatomic) long long totalBytesReadPerDownload;
@property(assign) long long totalContentLength;
+ (id)acceptableStatusCodes;
+ (id)cacheFolder;
+ (id)md5StringForString:(id)string;
- (id)initWithRequest:(id)request targetPath:(id)path shouldResume:(BOOL)resume;
- (void).cxx_destruct;
- (void)connection:(id)connection didReceiveData:(id)data;
- (void)connection:(id)connection didReceiveResponse:(id)response;
- (void)dealloc;
- (BOOL)deleteTempFileWithError:(id*)error;
- (id)error;
- (unsigned long long)fileSizeForPath:(id)path;
- (void)pause;
- (id)responseObject;
- (void)setProgressiveDownloadProgressBlock:(id)block;
- (BOOL)updateByteStartRangeForRequest;
@end

