/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ChineseSkillNew-Structs.h"
#import "NSCopying.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSInputStream, NSString, NSDictionary;

@interface AFHTTPBodyPart : XXUnknownSuperclass <NSCopying> {
	int _phase;
	NSInputStream* _inputStream;
	unsigned long long _phaseReadOffset;
	BOOL _hasInitialBoundary;
	BOOL _hasFinalBoundary;
	unsigned _stringEncoding;
	NSDictionary* _headers;
	NSString* _boundary;
	id _body;
	unsigned long long _bodyContentLength;
}
@property(retain, nonatomic) id body;
@property(assign, nonatomic) unsigned long long bodyContentLength;
@property(copy, nonatomic) NSString* boundary;
@property(readonly, assign, nonatomic, getter=hasBytesAvailable) BOOL bytesAvailable;
@property(readonly, assign, nonatomic) unsigned long long contentLength;
@property(assign, nonatomic) BOOL hasFinalBoundary;
@property(assign, nonatomic) BOOL hasInitialBoundary;
@property(retain, nonatomic) NSDictionary* headers;
@property(retain, nonatomic) NSInputStream* inputStream;
@property(assign, nonatomic) unsigned stringEncoding;
- (id)init;
- (void).cxx_destruct;
- (id)copyWithZone:(NSZone*)zone;
- (void)dealloc;
- (int)read:(char*)read maxLength:(unsigned)length;
- (int)readData:(id)data intoBuffer:(char*)buffer maxLength:(unsigned)length;
- (id)stringForHeaders;
- (BOOL)transitionToNextPhase;
@end

