/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ChineseSkillNew-Structs.h"
#import "AFHTTPResponseSerializer.h"


@interface AFImageResponseSerializer : AFHTTPResponseSerializer {
	BOOL _automaticallyInflatesResponseImage;
	float _imageScale;
}
@property(assign, nonatomic) BOOL automaticallyInflatesResponseImage;
@property(assign, nonatomic) float imageScale;
- (id)init;
- (id)initWithCoder:(id)coder;
- (id)copyWithZone:(NSZone*)zone;
- (void)encodeWithCoder:(id)coder;
- (id)responseObjectForResponse:(id)response data:(id)data error:(id*)error;
@end

