/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol AFMultipartFormData
- (void)appendPartWithFileData:(id)fileData name:(id)name fileName:(id)name3 mimeType:(id)type;
- (BOOL)appendPartWithFileURL:(id)fileURL name:(id)name error:(id*)error;
- (BOOL)appendPartWithFileURL:(id)fileURL name:(id)name fileName:(id)name3 mimeType:(id)type error:(id*)error;
- (void)appendPartWithFormData:(id)formData name:(id)name;
- (void)appendPartWithHeaders:(id)headers body:(id)body;
- (void)appendPartWithInputStream:(id)inputStream name:(id)name fileName:(id)name3 length:(long long)length mimeType:(id)type;
- (void)throttleBandwidthWithPacketSize:(unsigned)packetSize delay:(double)delay;
@end

