/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol AVAudioRecorderDelegate <NSObject>
@optional
- (void)audioRecorderBeginInterruption:(id)interruption;
- (void)audioRecorderDidFinishRecording:(id)audioRecorder successfully:(BOOL)successfully;
- (void)audioRecorderEncodeErrorDidOccur:(id)audioRecorderEncodeError error:(id)error;
- (void)audioRecorderEndInterruption:(id)interruption;
- (void)audioRecorderEndInterruption:(id)interruption withFlags:(unsigned)flags;
- (void)audioRecorderEndInterruption:(id)interruption withOptions:(unsigned)options;
@end

