/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSRequest.h"

@class NSString;

@interface AWSAutoScalingDeleteScheduledActionType : AWSRequest {
	NSString* _autoScalingGroupName;
	NSString* _scheduledActionName;
}
@property(retain, nonatomic) NSString* autoScalingGroupName;
@property(retain, nonatomic) NSString* scheduledActionName;
+ (id)JSONKeyPathsByPropertyKey;
- (void).cxx_destruct;
@end

