/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class NSArray, NSString, NSNumber;

@interface AWSAutoScalingScalingPolicy : AWSModel {
	NSString* _adjustmentType;
	NSArray* _alarms;
	NSString* _autoScalingGroupName;
	NSNumber* _cooldown;
	NSNumber* _minAdjustmentStep;
	NSString* _policyARN;
	NSString* _policyName;
	NSNumber* _scalingAdjustment;
}
@property(retain, nonatomic) NSString* adjustmentType;
@property(retain, nonatomic) NSArray* alarms;
@property(retain, nonatomic) NSString* autoScalingGroupName;
@property(retain, nonatomic) NSNumber* cooldown;
@property(retain, nonatomic) NSNumber* minAdjustmentStep;
@property(retain, nonatomic) NSString* policyARN;
@property(retain, nonatomic) NSString* policyName;
@property(retain, nonatomic) NSNumber* scalingAdjustment;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)alarmsJSONTransformer;
- (void).cxx_destruct;
@end

