/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class NSString, NSNumber;

@interface AWSAutoScalingEbs : AWSModel {
	NSNumber* _deleteOnTermination;
	NSNumber* _iops;
	NSString* _snapshotId;
	NSNumber* _volumeSize;
	NSString* _volumeType;
}
@property(retain, nonatomic) NSNumber* deleteOnTermination;
@property(retain, nonatomic) NSNumber* iops;
@property(retain, nonatomic) NSString* snapshotId;
@property(retain, nonatomic) NSNumber* volumeSize;
@property(retain, nonatomic) NSString* volumeType;
+ (id)JSONKeyPathsByPropertyKey;
- (void).cxx_destruct;
@end

