/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class NSString, NSNumber, AWSAutoScalingEbs;

@interface AWSAutoScalingBlockDeviceMapping : AWSModel {
	NSString* _deviceName;
	AWSAutoScalingEbs* _ebs;
	NSNumber* _noDevice;
	NSString* _virtualName;
}
@property(retain, nonatomic) NSString* deviceName;
@property(retain, nonatomic) AWSAutoScalingEbs* ebs;
@property(retain, nonatomic) NSNumber* noDevice;
@property(retain, nonatomic) NSString* virtualName;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)ebsJSONTransformer;
- (void).cxx_destruct;
@end

