/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class NSNumber;

@interface AWSAutoScalingDescribeAccountLimitsAnswer : AWSModel {
	NSNumber* _maxNumberOfAutoScalingGroups;
	NSNumber* _maxNumberOfLaunchConfigurations;
}
@property(retain, nonatomic) NSNumber* maxNumberOfAutoScalingGroups;
@property(retain, nonatomic) NSNumber* maxNumberOfLaunchConfigurations;
+ (id)JSONKeyPathsByPropertyKey;
- (void).cxx_destruct;
@end

