/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class NSString;

@interface AWSAutoScalingAutoScalingInstanceDetails : AWSModel {
	NSString* _autoScalingGroupName;
	NSString* _availabilityZone;
	NSString* _healthStatus;
	NSString* _instanceId;
	NSString* _launchConfigurationName;
	NSString* _lifecycleState;
}
@property(retain, nonatomic) NSString* autoScalingGroupName;
@property(retain, nonatomic) NSString* availabilityZone;
@property(retain, nonatomic) NSString* healthStatus;
@property(retain, nonatomic) NSString* instanceId;
@property(retain, nonatomic) NSString* launchConfigurationName;
@property(retain, nonatomic) NSString* lifecycleState;
+ (id)JSONKeyPathsByPropertyKey;
- (void).cxx_destruct;
@end

