/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSRequest.h"

@class NSString, NSNumber;

@interface AWSAutoScalingSetInstanceHealthQuery : AWSRequest {
	NSString* _healthStatus;
	NSString* _instanceId;
	NSNumber* _shouldRespectGracePeriod;
}
@property(retain, nonatomic) NSString* healthStatus;
@property(retain, nonatomic) NSString* instanceId;
@property(retain, nonatomic) NSNumber* shouldRespectGracePeriod;
+ (id)JSONKeyPathsByPropertyKey;
- (void).cxx_destruct;
@end

