/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSService.h"

@class AWSNetworking, AWSServiceConfiguration;

@interface AWSAutoScaling : AWSService {
	AWSServiceConfiguration* _configuration;
	AWSNetworking* _networking;
}
@property(retain, nonatomic) AWSServiceConfiguration* configuration;
@property(retain, nonatomic) AWSNetworking* networking;
+ (id)defaultAutoScaling;
- (id)initWithConfiguration:(id)configuration;
- (void).cxx_destruct;
- (id)attachInstances:(id)instances;
- (id)completeLifecycleAction:(id)action;
- (id)createAutoScalingGroup:(id)group;
- (id)createLaunchConfiguration:(id)configuration;
- (id)createOrUpdateTags:(id)tags;
- (id)deleteAutoScalingGroup:(id)group;
- (id)deleteLaunchConfiguration:(id)configuration;
- (id)deleteLifecycleHook:(id)hook;
- (id)deleteNotificationConfiguration:(id)configuration;
- (id)deletePolicy:(id)policy;
- (id)deleteScheduledAction:(id)action;
- (id)deleteTags:(id)tags;
- (id)describeAccountLimits:(id)limits;
- (id)describeAdjustmentTypes:(id)types;
- (id)describeAutoScalingGroups:(id)groups;
- (id)describeAutoScalingInstances:(id)instances;
- (id)describeAutoScalingNotificationTypes:(id)types;
- (id)describeLaunchConfigurations:(id)configurations;
- (id)describeLifecycleHookTypes:(id)types;
- (id)describeLifecycleHooks:(id)hooks;
- (id)describeMetricCollectionTypes:(id)types;
- (id)describeNotificationConfigurations:(id)configurations;
- (id)describePolicies:(id)policies;
- (id)describeScalingActivities:(id)activities;
- (id)describeScalingProcessTypes:(id)types;
- (id)describeScheduledActions:(id)actions;
- (id)describeTags:(id)tags;
- (id)describeTerminationPolicyTypes:(id)types;
- (id)detachInstances:(id)instances;
- (id)disableMetricsCollection:(id)collection;
- (id)enableMetricsCollection:(id)collection;
- (id)enterStandby:(id)standby;
- (id)executePolicy:(id)policy;
- (id)exitStandby:(id)standby;
- (id)invokeRequest:(id)request HTTPMethod:(int)method URLString:(id)string targetPrefix:(id)prefix operationName:(id)name outputClass:(Class)aClass;
- (id)putLifecycleHook:(id)hook;
- (id)putNotificationConfiguration:(id)configuration;
- (id)putScalingPolicy:(id)policy;
- (id)putScheduledUpdateGroupAction:(id)action;
- (id)recordLifecycleActionHeartbeat:(id)heartbeat;
- (id)resumeProcesses:(id)processes;
- (id)setDesiredCapacity:(id)capacity;
- (id)setInstanceHealth:(id)health;
- (id)suspendProcesses:(id)processes;
- (id)terminateInstanceInAutoScalingGroup:(id)autoScalingGroup;
- (id)updateAutoScalingGroup:(id)group;
@end

