/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSAbstractCognitoIdentityProvider.h"


@interface AWSBasicCognitoIdentityProvider : AWSAbstractCognitoIdentityProvider {
}
- (id)initWithRegionType:(int)regionType identityId:(id)anId accountId:(id)anId3 identityPoolId:(id)anId4 logins:(id)logins;
@end

