/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSRequest.h"

@class NSString, NSNumber;

@interface AWSCognitoSyncListRecordsRequest : AWSRequest {
	NSString* _datasetName;
	NSString* _identityId;
	NSString* _identityPoolId;
	NSNumber* _lastSyncCount;
	NSNumber* _maxResults;
	NSString* _nextToken;
	NSString* _syncSessionToken;
}
@property(retain, nonatomic) NSString* datasetName;
@property(retain, nonatomic) NSString* identityId;
@property(retain, nonatomic) NSString* identityPoolId;
@property(retain, nonatomic) NSNumber* lastSyncCount;
@property(retain, nonatomic) NSNumber* maxResults;
@property(retain, nonatomic) NSString* nextToken;
@property(retain, nonatomic) NSString* syncSessionToken;
+ (id)JSONKeyPathsByPropertyKey;
- (void).cxx_destruct;
@end

