/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class AWSCognitoSyncIdentityUsage;

@interface AWSCognitoSyncDescribeIdentityUsageResponse : AWSModel {
	AWSCognitoSyncIdentityUsage* _identityUsage;
}
@property(retain, nonatomic) AWSCognitoSyncIdentityUsage* identityUsage;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)identityUsageJSONTransformer;
- (void).cxx_destruct;
@end

