/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSRequest.h"

@class NSString, NSArray, NSNumber;

@interface AWSCloudWatchPutMetricAlarmInput : AWSRequest {
	NSNumber* _actionsEnabled;
	NSArray* _alarmActions;
	NSString* _alarmDescription;
	NSString* _alarmName;
	int _comparisonOperator;
	NSArray* _dimensions;
	NSNumber* _evaluationPeriods;
	NSArray* _insufficientDataActions;
	NSString* _metricName;
	NSString* _namespace;
	NSArray* _OKActions;
	NSNumber* _period;
	int _statistic;
	NSNumber* _threshold;
	int _unit;
}
@property(retain, nonatomic) NSArray* OKActions;
@property(retain, nonatomic) NSNumber* actionsEnabled;
@property(retain, nonatomic) NSArray* alarmActions;
@property(retain, nonatomic) NSString* alarmDescription;
@property(retain, nonatomic) NSString* alarmName;
@property(assign, nonatomic) int comparisonOperator;
@property(retain, nonatomic) NSArray* dimensions;
@property(retain, nonatomic) NSNumber* evaluationPeriods;
@property(retain, nonatomic) NSArray* insufficientDataActions;
@property(retain, nonatomic) NSString* metricName;
@property(retain, nonatomic) NSString* namespace;
@property(retain, nonatomic) NSNumber* period;
@property(assign, nonatomic) int statistic;
@property(retain, nonatomic) NSNumber* threshold;
@property(assign, nonatomic) int unit;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)comparisonOperatorJSONTransformer;
+ (id)dimensionsJSONTransformer;
+ (id)statisticJSONTransformer;
+ (id)unitJSONTransformer;
- (void).cxx_destruct;
@end

