/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class AWSCognitoRecord;

@interface AWSCognitoRecordTuple : XXUnknownSuperclass {
	AWSCognitoRecord* _localRecord;
	AWSCognitoRecord* _remoteRecord;
}
@property(readonly, assign, nonatomic) AWSCognitoRecord* localRecord;
@property(readonly, assign, nonatomic) AWSCognitoRecord* remoteRecord;
- (id)initWithLocalRecord:(id)localRecord remoteRecord:(id)record;
- (void).cxx_destruct;
@end

