/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"

@class NSString, NSDate;

@protocol AWSCredentialsProvider <NSObject>
@optional
@property(readonly, assign, nonatomic) NSString* accessKey;
@property(readonly, assign, nonatomic) NSDate* expiration;
@property(readonly, assign, nonatomic) NSString* secretKey;
@property(readonly, assign, nonatomic) NSString* sessionKey;
- (id)refresh;
@end

