/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSRequest.h"

@class NSArray, NSString, NSNumber;

@interface AWSCloudWatchDescribeAlarmsInput : AWSRequest {
	NSString* _actionPrefix;
	NSString* _alarmNamePrefix;
	NSArray* _alarmNames;
	NSNumber* _maxRecords;
	NSString* _nextToken;
	int _stateValue;
}
@property(retain, nonatomic) NSString* actionPrefix;
@property(retain, nonatomic) NSString* alarmNamePrefix;
@property(retain, nonatomic) NSArray* alarmNames;
@property(retain, nonatomic) NSNumber* maxRecords;
@property(retain, nonatomic) NSString* nextToken;
@property(assign, nonatomic) int stateValue;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)stateValueJSONTransformer;
- (void).cxx_destruct;
@end

