/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class NSString;

@interface AWSCognitoIdentityIdentityPoolShortDescription : AWSModel {
	NSString* _identityPoolId;
	NSString* _identityPoolName;
}
@property(retain, nonatomic) NSString* identityPoolId;
@property(retain, nonatomic) NSString* identityPoolName;
+ (id)JSONKeyPathsByPropertyKey;
- (void).cxx_destruct;
@end

