/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSRequest.h"

@class NSString, AWSCognitoSyncPushSync;

@interface AWSCognitoSyncSetIdentityPoolConfigurationRequest : AWSRequest {
	NSString* _identityPoolId;
	AWSCognitoSyncPushSync* _pushSync;
}
@property(retain, nonatomic) NSString* identityPoolId;
@property(retain, nonatomic) AWSCognitoSyncPushSync* pushSync;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)pushSyncJSONTransformer;
- (void).cxx_destruct;
@end

