/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class AWSDynamoDBConsumedCapacity, NSDictionary, NSArray, NSNumber;

@interface AWSDynamoDBScanOutput : AWSModel {
	AWSDynamoDBConsumedCapacity* _consumedCapacity;
	NSNumber* _count;
	NSArray* _items;
	NSDictionary* _lastEvaluatedKey;
	NSNumber* _scannedCount;
}
@property(retain, nonatomic) AWSDynamoDBConsumedCapacity* consumedCapacity;
@property(retain, nonatomic) NSNumber* count;
@property(retain, nonatomic) NSArray* items;
@property(retain, nonatomic) NSDictionary* lastEvaluatedKey;
@property(retain, nonatomic) NSNumber* scannedCount;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)consumedCapacityJSONTransformer;
+ (id)itemsJSONTransformer;
+ (id)lastEvaluatedKeyJSONTransformer;
- (void).cxx_destruct;
@end

