/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSNumber, NSDictionary;

@interface AWSDynamoDBQueryExpression : XXUnknownSuperclass {
	NSNumber* _scanIndexForward;
	id _hashKeyValues;
	NSDictionary* _rangeKeyConditions;
	NSDictionary* _exclusiveStartKey;
	NSNumber* _limit;
	NSString* _indexName;
}
@property(retain, nonatomic) NSDictionary* exclusiveStartKey;
@property(retain, nonatomic) id hashKeyValues;
@property(retain, nonatomic) NSString* indexName;
@property(retain, nonatomic) NSNumber* limit;
@property(retain, nonatomic) NSDictionary* rangeKeyConditions;
@property(retain, nonatomic) NSNumber* scanIndexForward;
- (void).cxx_destruct;
@end

