/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class NSArray, NSString;

@interface AWSDynamoDBListTablesOutput : AWSModel {
	NSString* _lastEvaluatedTableName;
	NSArray* _tableNames;
}
@property(retain, nonatomic) NSString* lastEvaluatedTableName;
@property(retain, nonatomic) NSArray* tableNames;
+ (id)JSONKeyPathsByPropertyKey;
- (void).cxx_destruct;
@end

