/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class NSDictionary;

@interface AWSDynamoDBDeleteRequest : AWSModel {
	NSDictionary* _key;
}
@property(retain, nonatomic) NSDictionary* key;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)keyJSONTransformer;
- (void).cxx_destruct;
@end

