/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class NSNumber;

@interface AWSDynamoDBProvisionedThroughput : AWSModel {
	NSNumber* _readCapacityUnits;
	NSNumber* _writeCapacityUnits;
}
@property(retain, nonatomic) NSNumber* readCapacityUnits;
@property(retain, nonatomic) NSNumber* writeCapacityUnits;
+ (id)JSONKeyPathsByPropertyKey;
- (void).cxx_destruct;
@end

