/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class AWSDynamoDBAttributeValue;

@interface AWSDynamoDBAttributeValueUpdate : AWSModel {
	int _action;
	AWSDynamoDBAttributeValue* _value;
}
@property(assign, nonatomic) int action;
@property(retain, nonatomic) AWSDynamoDBAttributeValue* value;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)actionJSONTransformer;
+ (id)valueJSONTransformer;
- (void).cxx_destruct;
@end

