/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSService.h"

@class AWSNetworking, AWSServiceConfiguration;

@interface AWSDynamoDB : AWSService {
	AWSServiceConfiguration* _configuration;
	AWSNetworking* _networking;
}
@property(retain, nonatomic) AWSServiceConfiguration* configuration;
@property(retain, nonatomic) AWSNetworking* networking;
+ (id)defaultDynamoDB;
- (id)initWithConfiguration:(id)configuration;
- (void).cxx_destruct;
- (id)batchGetItem:(id)item;
- (id)batchWriteItem:(id)item;
- (id)createTable:(id)table;
- (id)deleteItem:(id)item;
- (id)deleteTable:(id)table;
- (id)describeTable:(id)table;
- (id)getItem:(id)item;
- (id)invokeRequest:(id)request HTTPMethod:(int)method URLString:(id)string targetPrefix:(id)prefix operationName:(id)name outputClass:(Class)aClass;
- (id)listTables:(id)tables;
- (id)putItem:(id)item;
- (id)query:(id)query;
- (id)scan:(id)scan;
- (id)updateItem:(id)item;
- (id)updateTable:(id)table;
@end

