/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class NSArray, NSNumber;

@interface AWSElasticLoadBalancingBackendServerDescription : AWSModel {
	NSNumber* _instancePort;
	NSArray* _policyNames;
}
@property(retain, nonatomic) NSNumber* instancePort;
@property(retain, nonatomic) NSArray* policyNames;
+ (id)JSONKeyPathsByPropertyKey;
- (void).cxx_destruct;
@end

