/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class NSString, NSArray;

@interface AWSEC2Reservation : AWSModel {
	NSArray* _groups;
	NSArray* _instances;
	NSString* _ownerId;
	NSString* _requesterId;
	NSString* _reservationId;
}
@property(retain, nonatomic) NSArray* groups;
@property(retain, nonatomic) NSArray* instances;
@property(retain, nonatomic) NSString* ownerId;
@property(retain, nonatomic) NSString* requesterId;
@property(retain, nonatomic) NSString* reservationId;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)groupsJSONTransformer;
+ (id)instancesJSONTransformer;
- (void).cxx_destruct;
@end

