/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSRequest.h"

@class NSArray, NSString;

@interface AWSElasticLoadBalancingCreateLoadBalancerPolicyInput : AWSRequest {
	NSString* _loadBalancerName;
	NSArray* _policyAttributes;
	NSString* _policyName;
	NSString* _policyTypeName;
}
@property(retain, nonatomic) NSString* loadBalancerName;
@property(retain, nonatomic) NSArray* policyAttributes;
@property(retain, nonatomic) NSString* policyName;
@property(retain, nonatomic) NSString* policyTypeName;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)policyAttributesJSONTransformer;
- (void).cxx_destruct;
@end

