/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class NSDate, NSString, NSArray, NSNumber;

@interface AWSEC2Snapshot : AWSModel {
	NSString* _detail;
	NSNumber* _encrypted;
	NSString* _ownerAlias;
	NSString* _ownerId;
	NSString* _progress;
	NSString* _snapshotId;
	NSDate* _startTime;
	int _state;
	NSArray* _tags;
	NSString* _volumeId;
	NSNumber* _volumeSize;
}
@property(retain, nonatomic) NSString* detail;
@property(retain, nonatomic) NSNumber* encrypted;
@property(retain, nonatomic) NSString* ownerAlias;
@property(retain, nonatomic) NSString* ownerId;
@property(retain, nonatomic) NSString* progress;
@property(retain, nonatomic) NSString* snapshotId;
@property(retain, nonatomic) NSDate* startTime;
@property(assign, nonatomic) int state;
@property(retain, nonatomic) NSArray* tags;
@property(retain, nonatomic) NSString* volumeId;
@property(retain, nonatomic) NSNumber* volumeSize;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)startTimeJSONTransformer;
+ (id)stateJSONTransformer;
+ (id)tagsJSONTransformer;
- (void).cxx_destruct;
@end

