/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSRequest.h"

@class NSString, NSData, NSNumber;

@interface AWSEC2ImportKeyPairRequest : AWSRequest {
	NSNumber* _dryRun;
	NSString* _keyName;
	NSData* _publicKeyMaterial;
}
@property(retain, nonatomic) NSNumber* dryRun;
@property(retain, nonatomic) NSString* keyName;
@property(retain, nonatomic) NSData* publicKeyMaterial;
+ (id)JSONKeyPathsByPropertyKey;
- (void).cxx_destruct;
@end

