/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSRequest.h"

@class NSString, NSArray, NSNumber;

@interface AWSEC2DescribeTagsRequest : AWSRequest {
	NSNumber* _dryRun;
	NSArray* _filters;
	NSNumber* _maxResults;
	NSString* _nextToken;
}
@property(retain, nonatomic) NSNumber* dryRun;
@property(retain, nonatomic) NSArray* filters;
@property(retain, nonatomic) NSNumber* maxResults;
@property(retain, nonatomic) NSString* nextToken;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)filtersJSONTransformer;
- (void).cxx_destruct;
@end

