/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class NSString;

@interface AWSEC2AllocateAddressResult : AWSModel {
	NSString* _allocationId;
	int _domain;
	NSString* _publicIp;
}
@property(retain, nonatomic) NSString* allocationId;
@property(assign, nonatomic) int domain;
@property(retain, nonatomic) NSString* publicIp;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)domainJSONTransformer;
- (void).cxx_destruct;
@end

