/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class NSString, NSData;

@interface AWSEC2S3Storage : AWSModel {
	NSString* _AWSAccessKeyId;
	NSString* _bucket;
	NSString* _prefix;
	NSData* _uploadPolicy;
	NSString* _uploadPolicySignature;
}
@property(retain, nonatomic) NSString* AWSAccessKeyId;
@property(retain, nonatomic) NSString* bucket;
@property(retain, nonatomic) NSString* prefix;
@property(retain, nonatomic) NSData* uploadPolicy;
@property(retain, nonatomic) NSString* uploadPolicySignature;
+ (id)JSONKeyPathsByPropertyKey;
- (void).cxx_destruct;
@end

