/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class AWSElasticLoadBalancingPolicies, AWSElasticLoadBalancingHealthCheck, NSDate, NSString, NSArray, AWSElasticLoadBalancingSourceSecurityGroup;

@interface AWSElasticLoadBalancingLoadBalancerDescription : AWSModel {
	NSArray* _availabilityZones;
	NSArray* _backendServerDescriptions;
	NSString* _canonicalHostedZoneName;
	NSString* _canonicalHostedZoneNameID;
	NSDate* _createdTime;
	NSString* _DNSName;
	AWSElasticLoadBalancingHealthCheck* _healthCheck;
	NSArray* _instances;
	NSArray* _listenerDescriptions;
	NSString* _loadBalancerName;
	AWSElasticLoadBalancingPolicies* _policies;
	NSString* _scheme;
	NSArray* _securityGroups;
	AWSElasticLoadBalancingSourceSecurityGroup* _sourceSecurityGroup;
	NSArray* _subnets;
	NSString* _VPCId;
}
@property(retain, nonatomic) NSString* DNSName;
@property(retain, nonatomic) NSString* VPCId;
@property(retain, nonatomic) NSArray* availabilityZones;
@property(retain, nonatomic) NSArray* backendServerDescriptions;
@property(retain, nonatomic) NSString* canonicalHostedZoneName;
@property(retain, nonatomic) NSString* canonicalHostedZoneNameID;
@property(retain, nonatomic) NSDate* createdTime;
@property(retain, nonatomic) AWSElasticLoadBalancingHealthCheck* healthCheck;
@property(retain, nonatomic) NSArray* instances;
@property(retain, nonatomic) NSArray* listenerDescriptions;
@property(retain, nonatomic) NSString* loadBalancerName;
@property(retain, nonatomic) AWSElasticLoadBalancingPolicies* policies;
@property(retain, nonatomic) NSString* scheme;
@property(retain, nonatomic) NSArray* securityGroups;
@property(retain, nonatomic) AWSElasticLoadBalancingSourceSecurityGroup* sourceSecurityGroup;
@property(retain, nonatomic) NSArray* subnets;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)backendServerDescriptionsJSONTransformer;
+ (id)createdTimeJSONTransformer;
+ (id)healthCheckJSONTransformer;
+ (id)instancesJSONTransformer;
+ (id)listenerDescriptionsJSONTransformer;
+ (id)policiesJSONTransformer;
+ (id)sourceSecurityGroupJSONTransformer;
- (void).cxx_destruct;
@end

