/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSRequest.h"

@class NSString, NSNumber;

@interface AWSEC2DetachNetworkInterfaceRequest : AWSRequest {
	NSString* _attachmentId;
	NSNumber* _dryRun;
	NSNumber* _force;
}
@property(retain, nonatomic) NSString* attachmentId;
@property(retain, nonatomic) NSNumber* dryRun;
@property(retain, nonatomic) NSNumber* force;
+ (id)JSONKeyPathsByPropertyKey;
- (void).cxx_destruct;
@end

