/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class NSString, AWSEC2InstanceState;

@interface AWSEC2InstanceStateChange : AWSModel {
	AWSEC2InstanceState* _currentState;
	NSString* _instanceId;
	AWSEC2InstanceState* _previousState;
}
@property(retain, nonatomic) AWSEC2InstanceState* currentState;
@property(retain, nonatomic) NSString* instanceId;
@property(retain, nonatomic) AWSEC2InstanceState* previousState;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)currentStateJSONTransformer;
+ (id)previousStateJSONTransformer;
- (void).cxx_destruct;
@end

