/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class NSString;

@interface AWSEC2VpcPeeringConnectionVpcInfo : AWSModel {
	NSString* _cidrBlock;
	NSString* _ownerId;
	NSString* _vpcId;
}
@property(retain, nonatomic) NSString* cidrBlock;
@property(retain, nonatomic) NSString* ownerId;
@property(retain, nonatomic) NSString* vpcId;
+ (id)JSONKeyPathsByPropertyKey;
- (void).cxx_destruct;
@end

