/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class NSNumber;

@interface AWSElasticLoadBalancingConnectionDraining : AWSModel {
	NSNumber* _enabled;
	NSNumber* _timeout;
}
@property(retain, nonatomic) NSNumber* enabled;
@property(retain, nonatomic) NSNumber* timeout;
+ (id)JSONKeyPathsByPropertyKey;
- (void).cxx_destruct;
@end

