/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class NSString;

@interface AWSEC2AttachNetworkInterfaceResult : AWSModel {
	NSString* _attachmentId;
}
@property(retain, nonatomic) NSString* attachmentId;
+ (id)JSONKeyPathsByPropertyKey;
- (void).cxx_destruct;
@end

