/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class AWSEC2AttributeBooleanValue, AWSEC2AttributeValue, NSString, NSArray;

@interface AWSEC2InstanceAttribute : AWSModel {
	NSArray* _blockDeviceMappings;
	AWSEC2AttributeBooleanValue* _disableApiTermination;
	AWSEC2AttributeBooleanValue* _ebsOptimized;
	NSArray* _groups;
	NSString* _instanceId;
	AWSEC2AttributeValue* _instanceInitiatedShutdownBehavior;
	AWSEC2AttributeValue* _instanceType;
	AWSEC2AttributeValue* _kernelId;
	NSArray* _productCodes;
	AWSEC2AttributeValue* _ramdiskId;
	AWSEC2AttributeValue* _rootDeviceName;
	AWSEC2AttributeBooleanValue* _sourceDestCheck;
	AWSEC2AttributeValue* _sriovNetSupport;
	AWSEC2AttributeValue* _userData;
}
@property(retain, nonatomic) NSArray* blockDeviceMappings;
@property(retain, nonatomic) AWSEC2AttributeBooleanValue* disableApiTermination;
@property(retain, nonatomic) AWSEC2AttributeBooleanValue* ebsOptimized;
@property(retain, nonatomic) NSArray* groups;
@property(retain, nonatomic) NSString* instanceId;
@property(retain, nonatomic) AWSEC2AttributeValue* instanceInitiatedShutdownBehavior;
@property(retain, nonatomic) AWSEC2AttributeValue* instanceType;
@property(retain, nonatomic) AWSEC2AttributeValue* kernelId;
@property(retain, nonatomic) NSArray* productCodes;
@property(retain, nonatomic) AWSEC2AttributeValue* ramdiskId;
@property(retain, nonatomic) AWSEC2AttributeValue* rootDeviceName;
@property(retain, nonatomic) AWSEC2AttributeBooleanValue* sourceDestCheck;
@property(retain, nonatomic) AWSEC2AttributeValue* sriovNetSupport;
@property(retain, nonatomic) AWSEC2AttributeValue* userData;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)blockDeviceMappingsJSONTransformer;
+ (id)disableApiTerminationJSONTransformer;
+ (id)ebsOptimizedJSONTransformer;
+ (id)groupsJSONTransformer;
+ (id)instanceInitiatedShutdownBehaviorJSONTransformer;
+ (id)instanceTypeJSONTransformer;
+ (id)kernelIdJSONTransformer;
+ (id)productCodesJSONTransformer;
+ (id)ramdiskIdJSONTransformer;
+ (id)rootDeviceNameJSONTransformer;
+ (id)sourceDestCheckJSONTransformer;
+ (id)sriovNetSupportJSONTransformer;
+ (id)userDataJSONTransformer;
- (void).cxx_destruct;
@end

