/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class NSArray, NSString;

@interface AWSEC2DescribeInstancesResult : AWSModel {
	NSString* _nextToken;
	NSArray* _reservations;
}
@property(retain, nonatomic) NSString* nextToken;
@property(retain, nonatomic) NSArray* reservations;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)reservationsJSONTransformer;
- (void).cxx_destruct;
@end

