/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class NSString;

@interface AWSEC2NetworkInterfaceAssociation : AWSModel {
	NSString* _allocationId;
	NSString* _associationId;
	NSString* _ipOwnerId;
	NSString* _publicDnsName;
	NSString* _publicIp;
}
@property(retain, nonatomic) NSString* allocationId;
@property(retain, nonatomic) NSString* associationId;
@property(retain, nonatomic) NSString* ipOwnerId;
@property(retain, nonatomic) NSString* publicDnsName;
@property(retain, nonatomic) NSString* publicIp;
+ (id)JSONKeyPathsByPropertyKey;
- (void).cxx_destruct;
@end

