/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSRequest.h"

@class NSString, NSNumber;

@interface AWSEC2CreateCustomerGatewayRequest : AWSRequest {
	NSNumber* _bgpAsn;
	NSNumber* _dryRun;
	NSString* _publicIp;
	int _type;
}
@property(retain, nonatomic) NSNumber* bgpAsn;
@property(retain, nonatomic) NSNumber* dryRun;
@property(retain, nonatomic) NSString* publicIp;
@property(assign, nonatomic) int type;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)typeJSONTransformer;
- (void).cxx_destruct;
@end

