/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class NSString, NSArray, AWSEC2AttributeValue;

@interface AWSEC2ImageAttribute : AWSModel {
	NSArray* _blockDeviceMappings;
	AWSEC2AttributeValue* _detail;
	NSString* _imageId;
	AWSEC2AttributeValue* _kernelId;
	NSArray* _launchPermissions;
	NSArray* _productCodes;
	AWSEC2AttributeValue* _ramdiskId;
	AWSEC2AttributeValue* _sriovNetSupport;
}
@property(retain, nonatomic) NSArray* blockDeviceMappings;
@property(retain, nonatomic) AWSEC2AttributeValue* detail;
@property(retain, nonatomic) NSString* imageId;
@property(retain, nonatomic) AWSEC2AttributeValue* kernelId;
@property(retain, nonatomic) NSArray* launchPermissions;
@property(retain, nonatomic) NSArray* productCodes;
@property(retain, nonatomic) AWSEC2AttributeValue* ramdiskId;
@property(retain, nonatomic) AWSEC2AttributeValue* sriovNetSupport;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)blockDeviceMappingsJSONTransformer;
+ (id)detailJSONTransformer;
+ (id)kernelIdJSONTransformer;
+ (id)launchPermissionsJSONTransformer;
+ (id)productCodesJSONTransformer;
+ (id)ramdiskIdJSONTransformer;
+ (id)sriovNetSupportJSONTransformer;
- (void).cxx_destruct;
@end

