/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class AWSEC2ExportTask;

@interface AWSEC2CreateInstanceExportTaskResult : AWSModel {
	AWSEC2ExportTask* _exportTask;
}
@property(retain, nonatomic) AWSEC2ExportTask* exportTask;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)exportTaskJSONTransformer;
- (void).cxx_destruct;
@end

