/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class AWSEC2VpcPeeringConnectionVpcInfo, NSString, NSDate, NSArray, AWSEC2VpcPeeringConnectionStateReason;

@interface AWSEC2VpcPeeringConnection : AWSModel {
	AWSEC2VpcPeeringConnectionVpcInfo* _accepterVpcInfo;
	NSDate* _expirationTime;
	AWSEC2VpcPeeringConnectionVpcInfo* _requesterVpcInfo;
	AWSEC2VpcPeeringConnectionStateReason* _status;
	NSArray* _tags;
	NSString* _vpcPeeringConnectionId;
}
@property(retain, nonatomic) AWSEC2VpcPeeringConnectionVpcInfo* accepterVpcInfo;
@property(retain, nonatomic) NSDate* expirationTime;
@property(retain, nonatomic) AWSEC2VpcPeeringConnectionVpcInfo* requesterVpcInfo;
@property(retain, nonatomic) AWSEC2VpcPeeringConnectionStateReason* status;
@property(retain, nonatomic) NSArray* tags;
@property(retain, nonatomic) NSString* vpcPeeringConnectionId;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)accepterVpcInfoJSONTransformer;
+ (id)expirationTimeJSONTransformer;
+ (id)requesterVpcInfoJSONTransformer;
+ (id)statusJSONTransformer;
+ (id)tagsJSONTransformer;
- (void).cxx_destruct;
@end

