/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class NSString, NSDate;

@interface AWSEC2GetPasswordDataResult : AWSModel {
	NSString* _instanceId;
	NSString* _passwordData;
	NSDate* _timestamp;
}
@property(retain, nonatomic) NSString* instanceId;
@property(retain, nonatomic) NSString* passwordData;
@property(retain, nonatomic) NSDate* timestamp;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)timestampJSONTransformer;
- (void).cxx_destruct;
@end

