/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class NSString, NSDate;

@interface AWSEC2InstanceStatusEvent : AWSModel {
	int _code;
	NSString* _detail;
	NSDate* _notAfter;
	NSDate* _notBefore;
}
@property(assign, nonatomic) int code;
@property(retain, nonatomic) NSString* detail;
@property(retain, nonatomic) NSDate* notAfter;
@property(retain, nonatomic) NSDate* notBefore;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)codeJSONTransformer;
+ (id)notAfterJSONTransformer;
+ (id)notBeforeJSONTransformer;
- (void).cxx_destruct;
@end

