/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class AWSEC2Monitoring, AWSEC2IamInstanceProfile, NSDate, NSString, NSArray, AWSEC2InstanceState, AWSEC2StateReason, NSNumber, AWSEC2Placement;

@interface AWSEC2Instance : AWSModel {
	NSNumber* _amiLaunchIndex;
	int _architecture;
	NSArray* _blockDeviceMappings;
	NSString* _clientToken;
	NSNumber* _ebsOptimized;
	int _hypervisor;
	AWSEC2IamInstanceProfile* _iamInstanceProfile;
	NSString* _imageId;
	NSString* _instanceId;
	int _instanceLifecycle;
	int _instanceType;
	NSString* _kernelId;
	NSString* _keyName;
	NSDate* _launchTime;
	AWSEC2Monitoring* _monitoring;
	NSArray* _networkInterfaces;
	AWSEC2Placement* _placement;
	int _platform;
	NSString* _privateDnsName;
	NSString* _privateIpAddress;
	NSArray* _productCodes;
	NSString* _publicDnsName;
	NSString* _publicIpAddress;
	NSString* _ramdiskId;
	NSString* _rootDeviceName;
	int _rootDeviceType;
	NSArray* _securityGroups;
	NSNumber* _sourceDestCheck;
	NSString* _spotInstanceRequestId;
	NSString* _sriovNetSupport;
	AWSEC2InstanceState* _state;
	AWSEC2StateReason* _stateReason;
	NSString* _stateTransitionReason;
	NSString* _subnetId;
	NSArray* _tags;
	int _virtualizationType;
	NSString* _vpcId;
}
@property(retain, nonatomic) NSNumber* amiLaunchIndex;
@property(assign, nonatomic) int architecture;
@property(retain, nonatomic) NSArray* blockDeviceMappings;
@property(retain, nonatomic) NSString* clientToken;
@property(retain, nonatomic) NSNumber* ebsOptimized;
@property(assign, nonatomic) int hypervisor;
@property(retain, nonatomic) AWSEC2IamInstanceProfile* iamInstanceProfile;
@property(retain, nonatomic) NSString* imageId;
@property(retain, nonatomic) NSString* instanceId;
@property(assign, nonatomic) int instanceLifecycle;
@property(assign, nonatomic) int instanceType;
@property(retain, nonatomic) NSString* kernelId;
@property(retain, nonatomic) NSString* keyName;
@property(retain, nonatomic) NSDate* launchTime;
@property(retain, nonatomic) AWSEC2Monitoring* monitoring;
@property(retain, nonatomic) NSArray* networkInterfaces;
@property(retain, nonatomic) AWSEC2Placement* placement;
@property(assign, nonatomic) int platform;
@property(retain, nonatomic) NSString* privateDnsName;
@property(retain, nonatomic) NSString* privateIpAddress;
@property(retain, nonatomic) NSArray* productCodes;
@property(retain, nonatomic) NSString* publicDnsName;
@property(retain, nonatomic) NSString* publicIpAddress;
@property(retain, nonatomic) NSString* ramdiskId;
@property(retain, nonatomic) NSString* rootDeviceName;
@property(assign, nonatomic) int rootDeviceType;
@property(retain, nonatomic) NSArray* securityGroups;
@property(retain, nonatomic) NSNumber* sourceDestCheck;
@property(retain, nonatomic) NSString* spotInstanceRequestId;
@property(retain, nonatomic) NSString* sriovNetSupport;
@property(retain, nonatomic) AWSEC2InstanceState* state;
@property(retain, nonatomic) AWSEC2StateReason* stateReason;
@property(retain, nonatomic) NSString* stateTransitionReason;
@property(retain, nonatomic) NSString* subnetId;
@property(retain, nonatomic) NSArray* tags;
@property(assign, nonatomic) int virtualizationType;
@property(retain, nonatomic) NSString* vpcId;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)architectureJSONTransformer;
+ (id)blockDeviceMappingsJSONTransformer;
+ (id)hypervisorJSONTransformer;
+ (id)iamInstanceProfileJSONTransformer;
+ (id)instanceLifecycleJSONTransformer;
+ (id)instanceTypeJSONTransformer;
+ (id)launchTimeJSONTransformer;
+ (id)monitoringJSONTransformer;
+ (id)networkInterfacesJSONTransformer;
+ (id)placementJSONTransformer;
+ (id)platformJSONTransformer;
+ (id)productCodesJSONTransformer;
+ (id)rootDeviceTypeJSONTransformer;
+ (id)securityGroupsJSONTransformer;
+ (id)stateJSONTransformer;
+ (id)stateReasonJSONTransformer;
+ (id)tagsJSONTransformer;
+ (id)virtualizationTypeJSONTransformer;
- (void).cxx_destruct;
@end

