/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class AWSEC2InstanceStatusSummary, NSString, NSArray, AWSEC2InstanceState;

@interface AWSEC2InstanceStatus : AWSModel {
	NSString* _availabilityZone;
	NSArray* _events;
	NSString* _instanceId;
	AWSEC2InstanceState* _instanceState;
	AWSEC2InstanceStatusSummary* _instanceStatus;
	AWSEC2InstanceStatusSummary* _systemStatus;
}
@property(retain, nonatomic) NSString* availabilityZone;
@property(retain, nonatomic) NSArray* events;
@property(retain, nonatomic) NSString* instanceId;
@property(retain, nonatomic) AWSEC2InstanceState* instanceState;
@property(retain, nonatomic) AWSEC2InstanceStatusSummary* instanceStatus;
@property(retain, nonatomic) AWSEC2InstanceStatusSummary* systemStatus;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)eventsJSONTransformer;
+ (id)instanceStateJSONTransformer;
+ (id)instanceStatusJSONTransformer;
+ (id)systemStatusJSONTransformer;
- (void).cxx_destruct;
@end

