/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class NSNumber;

@interface AWSEC2PricingDetail : AWSModel {
	NSNumber* _count;
	NSNumber* _price;
}
@property(retain, nonatomic) NSNumber* count;
@property(retain, nonatomic) NSNumber* price;
+ (id)JSONKeyPathsByPropertyKey;
- (void).cxx_destruct;
@end

