/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSRequest.h"

@class NSString, AWSEC2ExportToS3TaskSpecification;

@interface AWSEC2CreateInstanceExportTaskRequest : AWSRequest {
	NSString* _detail;
	AWSEC2ExportToS3TaskSpecification* _exportToS3Task;
	NSString* _instanceId;
	int _targetEnvironment;
}
@property(retain, nonatomic) NSString* detail;
@property(retain, nonatomic) AWSEC2ExportToS3TaskSpecification* exportToS3Task;
@property(retain, nonatomic) NSString* instanceId;
@property(assign, nonatomic) int targetEnvironment;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)exportToS3TaskJSONTransformer;
+ (id)targetEnvironmentJSONTransformer;
- (void).cxx_destruct;
@end

