/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class NSString, NSArray;

@interface AWSEC2RouteTable : AWSModel {
	NSArray* _associations;
	NSArray* _propagatingVgws;
	NSString* _routeTableId;
	NSArray* _routes;
	NSArray* _tags;
	NSString* _vpcId;
}
@property(retain, nonatomic) NSArray* associations;
@property(retain, nonatomic) NSArray* propagatingVgws;
@property(retain, nonatomic) NSString* routeTableId;
@property(retain, nonatomic) NSArray* routes;
@property(retain, nonatomic) NSArray* tags;
@property(retain, nonatomic) NSString* vpcId;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)associationsJSONTransformer;
+ (id)propagatingVgwsJSONTransformer;
+ (id)routesJSONTransformer;
+ (id)tagsJSONTransformer;
- (void).cxx_destruct;
@end

