/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class NSArray;

@interface AWSEC2DescribeSecurityGroupsResult : AWSModel {
	NSArray* _securityGroups;
}
@property(retain, nonatomic) NSArray* securityGroups;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)securityGroupsJSONTransformer;
- (void).cxx_destruct;
@end

