/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class NSString;

@interface AWSEC2SpotPlacement : AWSModel {
	NSString* _availabilityZone;
	NSString* _groupName;
}
@property(retain, nonatomic) NSString* availabilityZone;
@property(retain, nonatomic) NSString* groupName;
+ (id)JSONKeyPathsByPropertyKey;
- (void).cxx_destruct;
@end

