/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class NSArray, NSString;

@interface AWSEC2SecurityGroup : AWSModel {
	NSString* _detail;
	NSString* _groupId;
	NSString* _groupName;
	NSArray* _ipPermissions;
	NSArray* _ipPermissionsEgress;
	NSString* _ownerId;
	NSArray* _tags;
	NSString* _vpcId;
}
@property(retain, nonatomic) NSString* detail;
@property(retain, nonatomic) NSString* groupId;
@property(retain, nonatomic) NSString* groupName;
@property(retain, nonatomic) NSArray* ipPermissions;
@property(retain, nonatomic) NSArray* ipPermissionsEgress;
@property(retain, nonatomic) NSString* ownerId;
@property(retain, nonatomic) NSArray* tags;
@property(retain, nonatomic) NSString* vpcId;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)ipPermissionsEgressJSONTransformer;
+ (id)ipPermissionsJSONTransformer;
+ (id)tagsJSONTransformer;
- (void).cxx_destruct;
@end

