/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSRequest.h"

@class NSArray;

@interface AWSElasticLoadBalancingRemoveTagsInput : AWSRequest {
	NSArray* _loadBalancerNames;
	NSArray* _tags;
}
@property(retain, nonatomic) NSArray* loadBalancerNames;
@property(retain, nonatomic) NSArray* tags;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)tagsJSONTransformer;
- (void).cxx_destruct;
@end

