/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSRequest.h"

@class NSArray, NSNumber;

@interface AWSEC2DescribeImagesRequest : AWSRequest {
	NSNumber* _dryRun;
	NSArray* _executableUsers;
	NSArray* _filters;
	NSArray* _imageIds;
	NSArray* _owners;
}
@property(retain, nonatomic) NSNumber* dryRun;
@property(retain, nonatomic) NSArray* executableUsers;
@property(retain, nonatomic) NSArray* filters;
@property(retain, nonatomic) NSArray* imageIds;
@property(retain, nonatomic) NSArray* owners;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)filtersJSONTransformer;
- (void).cxx_destruct;
@end

