/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class NSString;

@interface AWSEC2NetworkAclAssociation : AWSModel {
	NSString* _networkAclAssociationId;
	NSString* _networkAclId;
	NSString* _subnetId;
}
@property(retain, nonatomic) NSString* networkAclAssociationId;
@property(retain, nonatomic) NSString* networkAclId;
@property(retain, nonatomic) NSString* subnetId;
+ (id)JSONKeyPathsByPropertyKey;
- (void).cxx_destruct;
@end

