/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSRequest.h"

@class NSString, NSNumber;

@interface AWSElasticLoadBalancingSetLoadBalancerListenerSSLCertificateInput : AWSRequest {
	NSString* _loadBalancerName;
	NSNumber* _loadBalancerPort;
	NSString* _SSLCertificateId;
}
@property(retain, nonatomic) NSString* SSLCertificateId;
@property(retain, nonatomic) NSString* loadBalancerName;
@property(retain, nonatomic) NSNumber* loadBalancerPort;
+ (id)JSONKeyPathsByPropertyKey;
- (void).cxx_destruct;
@end

