/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSRequest.h"

@class AWSEC2AttributeBooleanValue, AWSEC2AttributeValue, NSString, NSArray, NSNumber, AWSEC2BlobAttributeValue;

@interface AWSEC2ModifyInstanceAttributeRequest : AWSRequest {
	int _attribute;
	NSArray* _blockDeviceMappings;
	AWSEC2AttributeBooleanValue* _disableApiTermination;
	NSNumber* _dryRun;
	AWSEC2AttributeBooleanValue* _ebsOptimized;
	NSArray* _groups;
	NSString* _instanceId;
	AWSEC2AttributeValue* _instanceInitiatedShutdownBehavior;
	AWSEC2AttributeValue* _instanceType;
	AWSEC2AttributeValue* _kernel;
	AWSEC2AttributeValue* _ramdisk;
	AWSEC2AttributeBooleanValue* _sourceDestCheck;
	AWSEC2AttributeValue* _sriovNetSupport;
	AWSEC2BlobAttributeValue* _userData;
	NSString* _value;
}
@property(assign, nonatomic) int attribute;
@property(retain, nonatomic) NSArray* blockDeviceMappings;
@property(retain, nonatomic) AWSEC2AttributeBooleanValue* disableApiTermination;
@property(retain, nonatomic) NSNumber* dryRun;
@property(retain, nonatomic) AWSEC2AttributeBooleanValue* ebsOptimized;
@property(retain, nonatomic) NSArray* groups;
@property(retain, nonatomic) NSString* instanceId;
@property(retain, nonatomic) AWSEC2AttributeValue* instanceInitiatedShutdownBehavior;
@property(retain, nonatomic) AWSEC2AttributeValue* instanceType;
@property(retain, nonatomic) AWSEC2AttributeValue* kernel;
@property(retain, nonatomic) AWSEC2AttributeValue* ramdisk;
@property(retain, nonatomic) AWSEC2AttributeBooleanValue* sourceDestCheck;
@property(retain, nonatomic) AWSEC2AttributeValue* sriovNetSupport;
@property(retain, nonatomic) AWSEC2BlobAttributeValue* userData;
@property(retain, nonatomic) NSString* value;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)attributeJSONTransformer;
+ (id)blockDeviceMappingsJSONTransformer;
+ (id)disableApiTerminationJSONTransformer;
+ (id)ebsOptimizedJSONTransformer;
+ (id)instanceInitiatedShutdownBehaviorJSONTransformer;
+ (id)instanceTypeJSONTransformer;
+ (id)kernelJSONTransformer;
+ (id)ramdiskJSONTransformer;
+ (id)sourceDestCheckJSONTransformer;
+ (id)sriovNetSupportJSONTransformer;
+ (id)userDataJSONTransformer;
- (void).cxx_destruct;
@end

