/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSRequest.h"

@class NSString, NSNumber;

@interface AWSEC2DeleteNetworkAclEntryRequest : AWSRequest {
	NSNumber* _dryRun;
	NSNumber* _egress;
	NSString* _networkAclId;
	NSNumber* _ruleNumber;
}
@property(retain, nonatomic) NSNumber* dryRun;
@property(retain, nonatomic) NSNumber* egress;
@property(retain, nonatomic) NSString* networkAclId;
@property(retain, nonatomic) NSNumber* ruleNumber;
+ (id)JSONKeyPathsByPropertyKey;
- (void).cxx_destruct;
@end

