/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class AWSEC2SpotInstanceStateFault, NSString;

@interface AWSEC2SpotDatafeedSubscription : AWSModel {
	NSString* _bucket;
	AWSEC2SpotInstanceStateFault* _fault;
	NSString* _ownerId;
	NSString* _prefix;
	int _state;
}
@property(retain, nonatomic) NSString* bucket;
@property(retain, nonatomic) AWSEC2SpotInstanceStateFault* fault;
@property(retain, nonatomic) NSString* ownerId;
@property(retain, nonatomic) NSString* prefix;
@property(assign, nonatomic) int state;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)faultJSONTransformer;
+ (id)stateJSONTransformer;
- (void).cxx_destruct;
@end

