/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class NSArray, NSString;

@interface AWSElasticLoadBalancingPolicyTypeDescription : AWSModel {
	NSString* _detail;
	NSArray* _policyAttributeTypeDescriptions;
	NSString* _policyTypeName;
}
@property(retain, nonatomic) NSString* detail;
@property(retain, nonatomic) NSArray* policyAttributeTypeDescriptions;
@property(retain, nonatomic) NSString* policyTypeName;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)policyAttributeTypeDescriptionsJSONTransformer;
- (void).cxx_destruct;
@end

