/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSRequest.h"

@class NSString, NSNumber;

@interface AWSEC2CreateVpnGatewayRequest : AWSRequest {
	NSString* _availabilityZone;
	NSNumber* _dryRun;
	int _type;
}
@property(retain, nonatomic) NSString* availabilityZone;
@property(retain, nonatomic) NSNumber* dryRun;
@property(assign, nonatomic) int type;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)typeJSONTransformer;
- (void).cxx_destruct;
@end

