/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class AWSElasticLoadBalancingLoadBalancerAttributes;

@interface AWSElasticLoadBalancingDescribeLoadBalancerAttributesOutput : AWSModel {
	AWSElasticLoadBalancingLoadBalancerAttributes* _loadBalancerAttributes;
}
@property(retain, nonatomic) AWSElasticLoadBalancingLoadBalancerAttributes* loadBalancerAttributes;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)loadBalancerAttributesJSONTransformer;
- (void).cxx_destruct;
@end

