/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class NSArray, NSString, NSNumber;

@interface AWSEC2Vpc : AWSModel {
	NSString* _cidrBlock;
	NSString* _dhcpOptionsId;
	int _instanceTenancy;
	NSNumber* _isDefault;
	int _state;
	NSArray* _tags;
	NSString* _vpcId;
}
@property(retain, nonatomic) NSString* cidrBlock;
@property(retain, nonatomic) NSString* dhcpOptionsId;
@property(assign, nonatomic) int instanceTenancy;
@property(retain, nonatomic) NSNumber* isDefault;
@property(assign, nonatomic) int state;
@property(retain, nonatomic) NSArray* tags;
@property(retain, nonatomic) NSString* vpcId;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)instanceTenancyJSONTransformer;
+ (id)stateJSONTransformer;
+ (id)tagsJSONTransformer;
- (void).cxx_destruct;
@end

