/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class AWSElasticLoadBalancingHealthCheck;

@interface AWSElasticLoadBalancingConfigureHealthCheckOutput : AWSModel {
	AWSElasticLoadBalancingHealthCheck* _healthCheck;
}
@property(retain, nonatomic) AWSElasticLoadBalancingHealthCheck* healthCheck;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)healthCheckJSONTransformer;
- (void).cxx_destruct;
@end

