/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class NSArray, NSString, NSDate;

@interface AWSEC2ReservedInstancesModification : AWSModel {
	NSString* _clientToken;
	NSDate* _createDate;
	NSDate* _effectiveDate;
	NSArray* _modificationResults;
	NSArray* _reservedInstancesIds;
	NSString* _reservedInstancesModificationId;
	NSString* _status;
	NSString* _statusMessage;
	NSDate* _updateDate;
}
@property(retain, nonatomic) NSString* clientToken;
@property(retain, nonatomic) NSDate* createDate;
@property(retain, nonatomic) NSDate* effectiveDate;
@property(retain, nonatomic) NSArray* modificationResults;
@property(retain, nonatomic) NSArray* reservedInstancesIds;
@property(retain, nonatomic) NSString* reservedInstancesModificationId;
@property(retain, nonatomic) NSString* status;
@property(retain, nonatomic) NSString* statusMessage;
@property(retain, nonatomic) NSDate* updateDate;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)createDateJSONTransformer;
+ (id)effectiveDateJSONTransformer;
+ (id)modificationResultsJSONTransformer;
+ (id)reservedInstancesIdsJSONTransformer;
+ (id)updateDateJSONTransformer;
- (void).cxx_destruct;
@end

