/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSRequest.h"

@class NSString, NSNumber;

@interface AWSEC2ResetImageAttributeRequest : AWSRequest {
	int _attribute;
	NSNumber* _dryRun;
	NSString* _imageId;
}
@property(assign, nonatomic) int attribute;
@property(retain, nonatomic) NSNumber* dryRun;
@property(retain, nonatomic) NSString* imageId;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)attributeJSONTransformer;
- (void).cxx_destruct;
@end

