/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class AWSEC2VpcPeeringConnection;

@interface AWSEC2CreateVpcPeeringConnectionResult : AWSModel {
	AWSEC2VpcPeeringConnection* _vpcPeeringConnection;
}
@property(retain, nonatomic) AWSEC2VpcPeeringConnection* vpcPeeringConnection;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)vpcPeeringConnectionJSONTransformer;
- (void).cxx_destruct;
@end

