/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class NSString;

@interface AWSEC2VpcAttachment : AWSModel {
	int _state;
	NSString* _vpcId;
}
@property(assign, nonatomic) int state;
@property(retain, nonatomic) NSString* vpcId;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)stateJSONTransformer;
- (void).cxx_destruct;
@end

