/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class AWSEC2InternetGateway;

@interface AWSEC2CreateInternetGatewayResult : AWSModel {
	AWSEC2InternetGateway* _internetGateway;
}
@property(retain, nonatomic) AWSEC2InternetGateway* internetGateway;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)internetGatewayJSONTransformer;
- (void).cxx_destruct;
@end

