/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class NSString, AWSEC2ReservedInstancesConfiguration;

@interface AWSEC2ReservedInstancesModificationResult : AWSModel {
	NSString* _reservedInstancesId;
	AWSEC2ReservedInstancesConfiguration* _targetConfiguration;
}
@property(retain, nonatomic) NSString* reservedInstancesId;
@property(retain, nonatomic) AWSEC2ReservedInstancesConfiguration* targetConfiguration;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)targetConfigurationJSONTransformer;
- (void).cxx_destruct;
@end

