/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSMobileAnalyticsEventIterator.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, AWSMobileAnalyticsFileEventStore, AWSMobileAnalyticsBufferedReader;

@interface AWSFileEventIterator : XXUnknownSuperclass <AWSMobileAnalyticsEventIterator> {
	BOOL _isEndOfFile;
	AWSMobileAnalyticsFileEventStore* _eventStore;
	int _linesRead;
	NSString* _nextBuffer;
	AWSMobileAnalyticsBufferedReader* _reader;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(retain, nonatomic) AWSMobileAnalyticsFileEventStore* eventStore;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) BOOL isEndOfFile;
@property(assign, nonatomic) int linesRead;
@property(retain, nonatomic) NSString* nextBuffer;
@property(retain, nonatomic) AWSMobileAnalyticsBufferedReader* reader;
@property(readonly, assign) Class superclass;
- (id)initFileStore:(id)store;
- (void).cxx_destruct;
- (BOOL)hasNext;
- (id)next;
- (id)peek;
- (void)removeReadEvents;
- (void)resetReader;
- (void)tryCloseReader;
- (BOOL)tryOpenReader;
@end

