/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface AWSJSONBuilder : XXUnknownSuperclass {
}
+ (id)buildJSONDictionary:(id)dictionary actionName:(id)name serviceDefinitionRule:(id)rule error:(id*)error;
+ (BOOL)failWithCode:(int)code description:(id)description error:(id*)error;
+ (id)jsonDataForDictionary:(id)dictionary actionName:(id)name serviceDefinitionRule:(id)rule error:(id*)error;
+ (id)serializeList:(id)list values:(id)values error:(id*)error;
+ (id)serializeMap:(id)map values:(id)values error:(id*)error;
+ (id)serializeMember:(id)member value:(id)value error:(id*)error;
+ (id)serializeStructure:(id)structure values:(id)values error:(id*)error;
@end

