/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSService.h"

@class NSString, FMDatabaseQueue, AWSKinesis;

@interface AWSKinesisRecorder : AWSService {
	unsigned _notificationByteThreshold;
	unsigned _diskByteLimit;
	AWSKinesis* _kinesis;
	FMDatabaseQueue* _databaseQueue;
	NSString* _databasePath;
	double _diskAgeLimit;
}
@property(retain, nonatomic) NSString* databasePath;
@property(retain, nonatomic) FMDatabaseQueue* databaseQueue;
@property(assign, nonatomic) double diskAgeLimit;
@property(assign, nonatomic) unsigned diskByteLimit;
@property(readonly, assign, nonatomic) unsigned diskBytesUsed;
@property(retain, nonatomic) AWSKinesis* kinesis;
@property(assign, nonatomic) unsigned notificationByteThreshold;
+ (id)defaultKinesisRecorder;
- (id)initWithConfiguration:(id)configuration identifier:(id)identifier;
- (id)initWithConfiguration:(id)configuration identifier:(id)identifier cacheName:(id)name;
- (void).cxx_destruct;
- (void)importLegacyData:(id)data;
- (id)removeAllRecords;
- (id)saveRecord:(id)record streamName:(id)name;
- (id)submitAllRecords;
@end

