/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class NSString;

@interface AWSKinesisSequenceNumberRange : AWSModel {
	NSString* _endingSequenceNumber;
	NSString* _startingSequenceNumber;
}
@property(retain, nonatomic) NSString* endingSequenceNumber;
@property(retain, nonatomic) NSString* startingSequenceNumber;
+ (id)JSONKeyPathsByPropertyKey;
- (void).cxx_destruct;
@end

