/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSRequest.h"

@class NSString, NSNumber;

@interface AWSKinesisListStreamsInput : AWSRequest {
	NSString* _exclusiveStartStreamName;
	NSNumber* _limit;
}
@property(retain, nonatomic) NSString* exclusiveStartStreamName;
@property(retain, nonatomic) NSNumber* limit;
+ (id)JSONKeyPathsByPropertyKey;
- (void).cxx_destruct;
@end

