/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSFileManager;

@interface AWSMobileAnalyticsFile : XXUnknownSuperclass {
	BOOL _isFile;
	BOOL _isDirectory;
	NSString* _fileName;
	NSString* _absolutePath;
	NSFileManager* _fileManager;
}
@property(readonly, assign, nonatomic) NSString* absolutePath;
@property(retain, nonatomic) NSFileManager* fileManager;
@property(readonly, assign, nonatomic) NSString* fileName;
@property(readonly, assign, nonatomic) BOOL isDirectory;
@property(readonly, assign, nonatomic) BOOL isFile;
- (id)init;
- (id)initWithFileMananager:(id)fileMananager withAbsolutePath:(id)absolutePath;
- (id)initWithFileMananager:(id)fileMananager withParent:(id)parent withChildPath:(id)childPath;
- (id)initWithFileMananager:(id)fileMananager withParentPath:(id)parentPath withChildPath:(id)childPath;
- (void).cxx_destruct;
- (BOOL)createNewFile;
- (BOOL)deleteFile;
- (BOOL)exists;
- (unsigned long long)length;
- (id)listFiles;
- (BOOL)mkdirs;
- (BOOL)renameTo:(id)to;
@end

