/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSMobileAnalyticsEventObserver.h"


@protocol AWSMobileAnalyticsDeliveryClient <AWSMobileAnalyticsEventObserver>
- (void)attemptDelivery;
- (id)batchedEvents;
- (void)enqueueEventForDelivery:(id)delivery;
- (void)forceDeliveryAndWaitForCompletion:(BOOL)completion;
- (void)waitForDeliveryOperations;
@end

