/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface AWSMobileAnalyticsErrorUtils : XXUnknownSuperclass {
}
+ (id)errorWithDomain:(id)domain withDescription:(id)description withErrorCode:(int)errorCode;
+ (BOOL)safeSetError:(id*)error withError:(id)error2;
@end

