/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol AWSMobileAnalyticsFileManager <NSObject>
- (id)createDirectory:(id)directory error:(id*)error;
- (id)createFile:(id)file error:(id*)error;
- (id)createFileWithPath:(id)path error:(id*)error;
- (BOOL)deleteFile:(id)file error:(id*)error;
- (BOOL)deleteFileWithPath:(id)path error:(id*)error;
- (id)getDirectory:(id)directory error:(id*)error;
- (id)listFilesInDirectory:(id)directory error:(id*)error;
- (id)listFilesInDirectoryWithPath:(id)path error:(id*)error;
- (id)newInputStream:(id)stream error:(id*)error;
- (id)newInputStreamWithPath:(id)path error:(id*)error;
- (id)newOutputStream:(id)stream appendMode:(BOOL)mode error:(id*)error;
- (id)newOutputStreamWithPath:(id)path appendMode:(BOOL)mode error:(id*)error;
- (id)readDataFromFile:(id)file withFormat:(int)format withDataProcessor:(id)dataProcessor withError:(id*)error;
- (id)readDataFromFile:(id)file withFormat:(int)format withError:(id*)error;
- (id)readDataFromFile:(id)file withReader:(id)reader withDataProcessor:(id)dataProcessor withFormat:(int)format withError:(id*)error;
- (BOOL)writeData:(id)data toFile:(id)file withFormat:(int)format withDataProcessor:(id)dataProcessor withError:(id*)error;
- (BOOL)writeData:(id)data toFile:(id)file withFormat:(int)format withError:(id*)error;
@end

