/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSMobileAnalyticsDefaultInterceptor.h"

@class AWSMobileAnalyticsSDKInfo;

@interface AWSMobileAnalyticsSDKInfoInterceptor : AWSMobileAnalyticsDefaultInterceptor {
	AWSMobileAnalyticsSDKInfo* _sdkInfo;
}
@property(retain, nonatomic) AWSMobileAnalyticsSDKInfo* sdkInfo;
- (id)initWithSDKInfo:(id)sdkinfo;
- (void).cxx_destruct;
- (void)before:(id)before;
@end

