/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface AWSMobileAnalyticsSDKInfo : XXUnknownSuperclass {
	NSString* _sdkVersion;
	NSString* _sdkName;
}
@property(retain, nonatomic) NSString* sdkName;
@property(retain, nonatomic) NSString* sdkVersion;
+ (id)sdkInfoFromBrazil;
+ (id)sdkInfoWithName:(id)name withVersion:(id)version;
- (id)initWithName:(id)name withVersion:(id)version;
- (void).cxx_destruct;
@end

