/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MTLJSONSerializing.h"
#import "MTLModel.h"


@interface AWSModel : MTLModel <MTLJSONSerializing> {
}
+ (id)JSONKeyPathsByPropertyKey;
- (id)dictionaryValue;
@end

