/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol AWSMobileAnalyticsEventClient <NSObject>
- (void)addGlobalAttribute:(id)attribute forKey:(id)key;
- (void)addGlobalAttribute:(id)attribute forKey:(id)key forEventType:(id)eventType;
- (void)addGlobalMetric:(id)metric forKey:(id)key;
- (void)addGlobalMetric:(id)metric forKey:(id)key forEventType:(id)eventType;
- (id)createEventWithEventType:(id)eventType;
- (void)recordEvent:(id)event;
- (void)removeGlobalAttributeForKey:(id)key;
- (void)removeGlobalAttributeForKey:(id)key forEventType:(id)eventType;
- (void)removeGlobalMetricForKey:(id)key;
- (void)removeGlobalMetricForKey:(id)key forEventType:(id)eventType;
- (void)submitEvents;
@end

