/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface AWSMobileAnalyticsStringUtils : XXUnknownSuperclass {
}
+ (id)appendTo:(id)to theString:(id)string;
+ (id)appendTo:(id)to theString:(id)string withFormat:(id)format;
+ (id)clipString:(id)string toMaxChars:(unsigned)maxChars andAppendEllipses:(BOOL)ellipses;
+ (id)dataToString:(id)string;
+ (BOOL)isBlank:(id)blank;
+ (BOOL)isNotBlank:(id)blank;
+ (BOOL)stringToBool:(id)aBool withBool:(BOOL*)aBool2;
+ (BOOL)stringToDouble:(id)aDouble withDouble:(double*)aDouble2;
+ (BOOL)stringToFloat:(id)aFloat withFloat:(float*)aFloat2;
+ (BOOL)stringToInt:(id)int withInt:(int*)int2;
+ (BOOL)stringToLongLong:(id)longLong withLongLong:(long long*)longLong2;
+ (id)trimString:(id)string toLength:(int)length orPadWith:(BOOL)with;
@end

