/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSMobileAnalyticsDefaultInterceptor.h"


@interface AWSMobileAnalyticsLogInterceptor : AWSMobileAnalyticsDefaultInterceptor {
}
- (void)after:(id)after;
- (void)before:(id)before;
@end

