/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class AWSServiceConfiguration, AWSMobileAnalyticsEnvironment, NSDictionary;

@interface AWSMobileAnalyticsConfiguration : XXUnknownSuperclass {
	BOOL _useHttps;
	BOOL _transmitOnWAN;
	BOOL _enableEvents;
	NSDictionary* _attributes;
	AWSMobileAnalyticsEnvironment* _environment;
	int _identificationStrategy;
	AWSServiceConfiguration* _serviceConfiguration;
}
@property(retain, nonatomic) NSDictionary* attributes;
@property(assign, nonatomic) BOOL enableEvents;
@property(retain, nonatomic) AWSMobileAnalyticsEnvironment* environment;
@property(assign, nonatomic) int identificationStrategy;
@property(retain, nonatomic) AWSServiceConfiguration* serviceConfiguration;
@property(assign, nonatomic) BOOL transmitOnWAN;
@property(assign, nonatomic) BOOL useHttps;
- (id)init;
- (void).cxx_destruct;
@end

