/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "AWSMobileAnalyticsConfiguring.h"

@class AWSMobileAnalyticsFile, NSRecursiveLock, NSOperationQueue, NSString, NSDictionary;
@protocol AWSMobileAnalyticsFileManager, AWSMobileAnalyticsHttpClient, AWSMobileAnalyticsConnectivity, AWSMobileAnalyticsPreferences;

@interface AWSMobileAnalyticsHttpCachingConfiguration : XXUnknownSuperclass <AWSMobileAnalyticsConfiguring> {
	id<AWSMobileAnalyticsHttpClient> _httpClient;
	NSDictionary* _settings;
	id<AWSMobileAnalyticsPreferences> _preferences;
	id<AWSMobileAnalyticsConnectivity> _connectivity;
	NSOperationQueue* _operationQueue;
	NSString* _uniqueId;
	NSString* _applicationKey;
	id<AWSMobileAnalyticsFileManager> _fileManager;
	AWSMobileAnalyticsFile* _file;
	NSRecursiveLock* _fileLock;
	double _lastConfigSyncTimestamp;
}
@property(retain, nonatomic) NSString* applicationKey;
@property(retain, nonatomic) id<AWSMobileAnalyticsConnectivity> connectivity;
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(retain, nonatomic) AWSMobileAnalyticsFile* file;
@property(retain, nonatomic) NSRecursiveLock* fileLock;
@property(retain, nonatomic) id<AWSMobileAnalyticsFileManager> fileManager;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) id<AWSMobileAnalyticsHttpClient> httpClient;
@property(assign, nonatomic) double lastConfigSyncTimestamp;
@property(retain, nonatomic) NSOperationQueue* operationQueue;
@property(retain, nonatomic) id<AWSMobileAnalyticsPreferences> preferences;
@property(retain, nonatomic) NSDictionary* settings;
@property(readonly, assign) Class superclass;
@property(retain, nonatomic) NSString* uniqueId;
+ (id)configurationWithContext:(id)context withFileManager:(id)fileManager withOverrideSettings:(id)overrideSettings withOperationQueue:(id)operationQueue;
+ (id)createConfigurationRequestWithClient:(id)client withHost:(id)host withApplicationKey:(id)applicationKey withUniqueId:(id)uniqueId;
- (id)initWithContext:(id)context withFileManager:(id)fileManager withOverrideSettings:(id)overrideSettings withOperationQueue:(id)operationQueue;
- (void).cxx_destruct;
- (id)arrayForKey:(id)key;
- (id)arrayForKey:(id)key withOptValue:(id)optValue;
- (BOOL)boolForKey:(id)key withOptValue:(BOOL)optValue;
- (double)doubleForKey:(id)key withOptValue:(double)optValue;
- (int)intForKey:(id)key withOptValue:(int)optValue;
- (id)loadPersistedSettingsAndMergeWith:(id)with;
- (long)longForKey:(id)key withOptValue:(long)optValue;
- (long long)longLongForKey:(id)key withOptValue:(long long)optValue;
- (id)objectForKey:(id)key;
- (void)refresh;
- (void)saveConfiguration:(id)configuration;
- (id)stringForKey:(id)key;
- (id)stringForKey:(id)key withOptValue:(id)optValue;
@end

