/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class AWSMobileAnalyticsFile, NSRecursiveLock;
@protocol AWSMobileAnalyticsFileManager;

@interface AWSMobileAnalyticsSessionStore : XXUnknownSuperclass {
	NSRecursiveLock* _fileLock;
	id<AWSMobileAnalyticsFileManager> _fileManager;
	AWSMobileAnalyticsFile* _file;
}
@property(retain, nonatomic) AWSMobileAnalyticsFile* file;
@property(retain, nonatomic) NSRecursiveLock* fileLock;
@property(retain, nonatomic) id<AWSMobileAnalyticsFileManager> fileManager;
- (id)initWithFileManager:(id)fileManager;
- (void).cxx_destruct;
- (id)createSessionFromSerializedDictionary:(id)serializedDictionary;
- (BOOL)deletePesistedSession;
- (void)persistSessionDetails:(id)details;
- (id)retrievePersistedSessionDetails;
@end

