/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSInputStream, NSMutableData, NSMutableString, NSObject;

@interface AWSMobileAnalyticsBufferedReader : XXUnknownSuperclass {
	NSInputStream* _inputStream;
	NSMutableString* _readFromStream;
	unsigned _bufferLength;
	NSMutableData* _streamBuffer;
	NSObject* _lockObject;
}
@property(assign, nonatomic) unsigned bufferLength;
@property(retain, nonatomic) NSInputStream* inputStream;
@property(retain, nonatomic) NSObject* lockObject;
@property(retain, nonatomic) NSMutableString* readFromStream;
@property(retain, nonatomic) NSMutableData* streamBuffer;
+ (id)readerWithInputStream:(id)inputStream;
+ (id)readerWithInputStream:(id)inputStream withBufferLength:(unsigned)bufferLength;
- (id)initWithInputStream:(id)inputStream withBufferLength:(unsigned)bufferLength;
- (void).cxx_destruct;
- (void)clearBuffers;
- (void)close;
- (BOOL)readLine:(id*)line withError:(id*)error;
@end

