/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"

@class NSData, NSURL, NSString, NSDictionary;

@protocol AWSMobileAnalyticsRequest <NSObject>
@property(readonly, assign, nonatomic) NSDictionary* headers;
@property(assign, nonatomic) int method;
@property(readonly, assign, nonatomic) NSDictionary* params;
@property(retain, nonatomic) NSData* postBody;
@property(retain, nonatomic) NSString* postBodyString;
@property(retain, nonatomic) NSURL* url;
- (void)addHeader:(id)header forName:(id)name;
- (void)addParam:(id)param forName:(id)name;
- (id)headerForName:(id)name;
- (void)removeHeader:(id)header;
@end

