/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class NSURL, AWSNetworkingRequest, NSNumber;

@interface AWSRequest : AWSModel {
	id _uploadProgress;
	id _downloadProgress;
	NSURL* _downloadingFileURL;
	AWSNetworkingRequest* _internalRequest;
	NSNumber* _shouldWriteDirectly;
}
@property(readonly, assign, nonatomic, getter=isCancelled) BOOL cancelled;
@property(copy, nonatomic) id downloadProgress;
@property(retain, nonatomic) NSURL* downloadingFileURL;
@property(retain, nonatomic) AWSNetworkingRequest* internalRequest;
@property(assign, nonatomic) NSNumber* shouldWriteDirectly;
@property(copy, nonatomic) id uploadProgress;
- (id)init;
- (void).cxx_destruct;
- (id)cancel;
- (id)dictionaryValue;
- (id)pause;
@end

