/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class NSNumber;

@interface AWSSimpleDBDomainMetadataResult : AWSModel {
	NSNumber* _attributeNameCount;
	NSNumber* _attributeNamesSizeBytes;
	NSNumber* _attributeValueCount;
	NSNumber* _attributeValuesSizeBytes;
	NSNumber* _itemCount;
	NSNumber* _itemNamesSizeBytes;
	NSNumber* _timestamp;
}
@property(retain, nonatomic) NSNumber* attributeNameCount;
@property(retain, nonatomic) NSNumber* attributeNamesSizeBytes;
@property(retain, nonatomic) NSNumber* attributeValueCount;
@property(retain, nonatomic) NSNumber* attributeValuesSizeBytes;
@property(retain, nonatomic) NSNumber* itemCount;
@property(retain, nonatomic) NSNumber* itemNamesSizeBytes;
@property(retain, nonatomic) NSNumber* timestamp;
+ (id)JSONKeyPathsByPropertyKey;
- (void).cxx_destruct;
@end

