/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSRequest.h"

@class NSString;

@interface AWSSESSetIdentityNotificationTopicRequest : AWSRequest {
	NSString* _identity;
	int _notificationType;
	NSString* _snsTopic;
}
@property(retain, nonatomic) NSString* identity;
@property(assign, nonatomic) int notificationType;
@property(retain, nonatomic) NSString* snsTopic;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)notificationTypeJSONTransformer;
- (void).cxx_destruct;
@end

