/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class NSString, NSDictionary;

@interface AWSSNSPlatformApplication : AWSModel {
	NSDictionary* _attributes;
	NSString* _platformApplicationArn;
}
@property(retain, nonatomic) NSDictionary* attributes;
@property(retain, nonatomic) NSString* platformApplicationArn;
+ (id)JSONKeyPathsByPropertyKey;
- (void).cxx_destruct;
@end

