/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSRequest.h"

@class NSString, NSDictionary;

@interface AWSSNSCreatePlatformEndpointInput : AWSRequest {
	NSDictionary* _attributes;
	NSString* _customUserData;
	NSString* _platformApplicationArn;
	NSString* _token;
}
@property(retain, nonatomic) NSDictionary* attributes;
@property(retain, nonatomic) NSString* customUserData;
@property(retain, nonatomic) NSString* platformApplicationArn;
@property(retain, nonatomic) NSString* token;
+ (id)JSONKeyPathsByPropertyKey;
- (void).cxx_destruct;
@end

