/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class NSDate, NSString;

@interface AWSS3PutObjectOutput : AWSModel {
	NSString* _ETag;
	NSDate* _expiration;
	NSString* _SSECustomerAlgorithm;
	NSString* _SSECustomerKeyMD5;
	NSString* _SSEKMSKeyId;
	int _serverSideEncryption;
	NSString* _versionId;
}
@property(retain, nonatomic) NSString* ETag;
@property(retain, nonatomic) NSString* SSECustomerAlgorithm;
@property(retain, nonatomic) NSString* SSECustomerKeyMD5;
@property(retain, nonatomic) NSString* SSEKMSKeyId;
@property(retain, nonatomic) NSDate* expiration;
@property(assign, nonatomic) int serverSideEncryption;
@property(retain, nonatomic) NSString* versionId;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)expirationJSONTransformer;
+ (id)serverSideEncryptionJSONTransformer;
- (void).cxx_destruct;
@end

