/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class NSString, NSArray;

@interface AWSS3LoggingEnabled : AWSModel {
	NSString* _targetBucket;
	NSArray* _targetGrants;
	NSString* _targetPrefix;
}
@property(retain, nonatomic) NSString* targetBucket;
@property(retain, nonatomic) NSArray* targetGrants;
@property(retain, nonatomic) NSString* targetPrefix;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)targetGrantsJSONTransformer;
- (void).cxx_destruct;
@end

