/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface AWSSignatureSignerUtility : XXUnknownSuperclass {
}
+ (id)HMACSign:(id)sign withKey:(id)key usingAlgorithm:(unsigned)algorithm;
+ (id)hash:(id)hash;
+ (id)hashString:(id)string;
+ (id)hexEncode:(id)encode;
+ (id)sha256HMacWithData:(id)data withKey:(id)key;
@end

