/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"


@interface AWSS3GetObjectTorrentOutput : AWSModel {
	id _body;
}
@property(retain, nonatomic) id body;
+ (id)JSONKeyPathsByPropertyKey;
- (void).cxx_destruct;
@end

