/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSRequest.h"

@class NSString, NSNumber;

@interface AWSSESListIdentitiesRequest : AWSRequest {
	int _identityType;
	NSNumber* _maxItems;
	NSString* _nextToken;
}
@property(assign, nonatomic) int identityType;
@property(retain, nonatomic) NSNumber* maxItems;
@property(retain, nonatomic) NSString* nextToken;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)identityTypeJSONTransformer;
- (void).cxx_destruct;
@end

