/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class NSNumber;

@interface AWSS3NoncurrentVersionExpiration : AWSModel {
	NSNumber* _noncurrentDays;
}
@property(retain, nonatomic) NSNumber* noncurrentDays;
+ (id)JSONKeyPathsByPropertyKey;
- (void).cxx_destruct;
@end

