/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class NSString, NSDate;

@interface AWSS3Bucket : AWSModel {
	NSDate* _creationDate;
	NSString* _name;
}
@property(retain, nonatomic) NSDate* creationDate;
@property(retain, nonatomic) NSString* name;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)creationDateJSONTransformer;
- (void).cxx_destruct;
@end

