/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class NSString, NSDate, AWSS3Owner, AWSS3Initiator;

@interface AWSS3MultipartUpload : AWSModel {
	NSDate* _initiated;
	AWSS3Initiator* _initiator;
	NSString* _key;
	AWSS3Owner* _owner;
	int _storageClass;
	NSString* _uploadId;
}
@property(retain, nonatomic) NSDate* initiated;
@property(retain, nonatomic) AWSS3Initiator* initiator;
@property(retain, nonatomic) NSString* key;
@property(retain, nonatomic) AWSS3Owner* owner;
@property(assign, nonatomic) int storageClass;
@property(retain, nonatomic) NSString* uploadId;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)initiatedJSONTransformer;
+ (id)initiatorJSONTransformer;
+ (id)ownerJSONTransformer;
+ (id)storageClassJSONTransformer;
- (void).cxx_destruct;
@end

