/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSRequest.h"

@class AWSS3VersioningConfiguration, NSString;

@interface AWSS3PutBucketVersioningRequest : AWSRequest {
	NSString* _bucket;
	NSString* _contentMD5;
	NSString* _MFA;
	AWSS3VersioningConfiguration* _versioningConfiguration;
}
@property(retain, nonatomic) NSString* MFA;
@property(retain, nonatomic) NSString* bucket;
@property(retain, nonatomic) NSString* contentMD5;
@property(retain, nonatomic) AWSS3VersioningConfiguration* versioningConfiguration;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)versioningConfigurationJSONTransformer;
- (void).cxx_destruct;
@end

