/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSRequest.h"

@class AWSS3LifecycleConfiguration, NSString;

@interface AWSS3PutBucketLifecycleRequest : AWSRequest {
	NSString* _bucket;
	NSString* _contentMD5;
	AWSS3LifecycleConfiguration* _lifecycleConfiguration;
}
@property(retain, nonatomic) NSString* bucket;
@property(retain, nonatomic) NSString* contentMD5;
@property(retain, nonatomic) AWSS3LifecycleConfiguration* lifecycleConfiguration;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)lifecycleConfigurationJSONTransformer;
- (void).cxx_destruct;
@end

