/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class NSNumber;

@interface AWSSESGetSendQuotaResponse : AWSModel {
	NSNumber* _max24HourSend;
	NSNumber* _maxSendRate;
	NSNumber* _sentLast24Hours;
}
@property(retain, nonatomic) NSNumber* max24HourSend;
@property(retain, nonatomic) NSNumber* maxSendRate;
@property(retain, nonatomic) NSNumber* sentLast24Hours;
+ (id)JSONKeyPathsByPropertyKey;
- (void).cxx_destruct;
@end

