/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class AWSS3LifecycleExpiration, AWSS3NoncurrentVersionExpiration, AWSS3NoncurrentVersionTransition, NSString, AWSS3Transition;

@interface AWSS3Rule : AWSModel {
	AWSS3LifecycleExpiration* _expiration;
	NSString* _ID;
	AWSS3NoncurrentVersionExpiration* _noncurrentVersionExpiration;
	AWSS3NoncurrentVersionTransition* _noncurrentVersionTransition;
	NSString* _prefix;
	int _status;
	AWSS3Transition* _transition;
}
@property(retain, nonatomic) NSString* ID;
@property(retain, nonatomic) AWSS3LifecycleExpiration* expiration;
@property(retain, nonatomic) AWSS3NoncurrentVersionExpiration* noncurrentVersionExpiration;
@property(retain, nonatomic) AWSS3NoncurrentVersionTransition* noncurrentVersionTransition;
@property(retain, nonatomic) NSString* prefix;
@property(assign, nonatomic) int status;
@property(retain, nonatomic) AWSS3Transition* transition;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)expirationJSONTransformer;
+ (id)noncurrentVersionExpirationJSONTransformer;
+ (id)noncurrentVersionTransitionJSONTransformer;
+ (id)statusJSONTransformer;
+ (id)transitionJSONTransformer;
- (void).cxx_destruct;
@end

