/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class NSString;

@interface AWSS3CreateMultipartUploadOutput : AWSModel {
	NSString* _bucket;
	NSString* _key;
	NSString* _SSECustomerAlgorithm;
	NSString* _SSECustomerKeyMD5;
	NSString* _SSEKMSKeyId;
	int _serverSideEncryption;
	NSString* _uploadId;
}
@property(retain, nonatomic) NSString* SSECustomerAlgorithm;
@property(retain, nonatomic) NSString* SSECustomerKeyMD5;
@property(retain, nonatomic) NSString* SSEKMSKeyId;
@property(retain, nonatomic) NSString* bucket;
@property(retain, nonatomic) NSString* key;
@property(assign, nonatomic) int serverSideEncryption;
@property(retain, nonatomic) NSString* uploadId;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)serverSideEncryptionJSONTransformer;
- (void).cxx_destruct;
@end

