/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class AWSS3Condition, AWSS3Redirect;

@interface AWSS3RoutingRule : AWSModel {
	AWSS3Condition* _condition;
	AWSS3Redirect* _redirect;
}
@property(retain, nonatomic) AWSS3Condition* condition;
@property(retain, nonatomic) AWSS3Redirect* redirect;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)conditionJSONTransformer;
+ (id)redirectJSONTransformer;
- (void).cxx_destruct;
@end

