/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSRequest.h"

@class NSString;

@interface AWSSNSSubscribeInput : AWSRequest {
	NSString* _endpoint;
	NSString* _protocol;
	NSString* _topicArn;
}
@property(retain, nonatomic) NSString* endpoint;
@property(retain, nonatomic) NSString* protocol;
@property(retain, nonatomic) NSString* topicArn;
+ (id)JSONKeyPathsByPropertyKey;
- (void).cxx_destruct;
@end

