/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class NSString;

@interface AWSS3RedirectAllRequestsTo : AWSModel {
	NSString* _hostName;
	int _protocol;
}
@property(retain, nonatomic) NSString* hostName;
@property(assign, nonatomic) int protocol;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)protocolJSONTransformer;
- (void).cxx_destruct;
@end

