/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class NSString, NSNumber;

@interface AWSS3CompletedPart : AWSModel {
	NSString* _ETag;
	NSNumber* _partNumber;
}
@property(retain, nonatomic) NSString* ETag;
@property(retain, nonatomic) NSNumber* partNumber;
+ (id)JSONKeyPathsByPropertyKey;
- (void).cxx_destruct;
@end

