/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSService.h"

@class AWSServiceConfiguration;

@interface AWSS3PreSignedURLBuilder : AWSService {
	AWSServiceConfiguration* _configuration;
}
@property(retain, nonatomic) AWSServiceConfiguration* configuration;
+ (id)defaultS3PreSignedURLBuilder;
- (id)initWithConfiguration:(id)configuration;
- (void).cxx_destruct;
- (id)getPreSignedURL:(id)url;
@end

