/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class NSString, NSArray;

@interface AWSSimpleDBItem : AWSModel {
	NSString* _alternateNameEncoding;
	NSArray* _attributes;
	NSString* _name;
}
@property(retain, nonatomic) NSString* alternateNameEncoding;
@property(retain, nonatomic) NSArray* attributes;
@property(retain, nonatomic) NSString* name;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)attributesJSONTransformer;
- (void).cxx_destruct;
@end

