/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSRequest.h"

@class NSString, NSNumber;

@interface AWSS3UploadPartRequest : AWSRequest {
	id _body;
	NSString* _bucket;
	NSNumber* _contentLength;
	NSString* _contentMD5;
	NSString* _key;
	NSNumber* _partNumber;
	NSString* _SSECustomerAlgorithm;
	NSString* _SSECustomerKey;
	NSString* _SSECustomerKeyMD5;
	NSString* _SSEKMSKeyId;
	NSString* _uploadId;
}
@property(retain, nonatomic) NSString* SSECustomerAlgorithm;
@property(retain, nonatomic) NSString* SSECustomerKey;
@property(retain, nonatomic) NSString* SSECustomerKeyMD5;
@property(retain, nonatomic) NSString* SSEKMSKeyId;
@property(retain, nonatomic) id body;
@property(retain, nonatomic) NSString* bucket;
@property(retain, nonatomic) NSNumber* contentLength;
@property(retain, nonatomic) NSString* contentMD5;
@property(retain, nonatomic) NSString* key;
@property(retain, nonatomic) NSNumber* partNumber;
@property(retain, nonatomic) NSString* uploadId;
+ (id)JSONKeyPathsByPropertyKey;
- (void).cxx_destruct;
@end

