/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSRequest.h"

@class NSString, NSArray, NSNumber;

@interface AWSSimpleDBGetAttributesRequest : AWSRequest {
	NSArray* _attributeNames;
	NSNumber* _consistentRead;
	NSString* _domainName;
	NSString* _itemName;
}
@property(retain, nonatomic) NSArray* attributeNames;
@property(retain, nonatomic) NSNumber* consistentRead;
@property(retain, nonatomic) NSString* domainName;
@property(retain, nonatomic) NSString* itemName;
+ (id)JSONKeyPathsByPropertyKey;
- (void).cxx_destruct;
@end

