/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class NSDictionary;

@interface AWSSESGetIdentityDkimAttributesResponse : AWSModel {
	NSDictionary* _dkimAttributes;
}
@property(retain, nonatomic) NSDictionary* dkimAttributes;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)dkimAttributesJSONTransformer;
- (void).cxx_destruct;
@end

