/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class NSString, NSArray, NSNumber;

@interface AWSS3ListMultipartUploadsOutput : AWSModel {
	NSString* _bucket;
	NSArray* _commonPrefixes;
	NSString* _delimiter;
	int _encodingType;
	NSNumber* _isTruncated;
	NSString* _keyMarker;
	NSNumber* _maxUploads;
	NSString* _nextKeyMarker;
	NSString* _nextUploadIdMarker;
	NSString* _prefix;
	NSString* _uploadIdMarker;
	NSArray* _uploads;
}
@property(retain, nonatomic) NSString* bucket;
@property(retain, nonatomic) NSArray* commonPrefixes;
@property(retain, nonatomic) NSString* delimiter;
@property(assign, nonatomic) int encodingType;
@property(retain, nonatomic) NSNumber* isTruncated;
@property(retain, nonatomic) NSString* keyMarker;
@property(retain, nonatomic) NSNumber* maxUploads;
@property(retain, nonatomic) NSString* nextKeyMarker;
@property(retain, nonatomic) NSString* nextUploadIdMarker;
@property(retain, nonatomic) NSString* prefix;
@property(retain, nonatomic) NSString* uploadIdMarker;
@property(retain, nonatomic) NSArray* uploads;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)commonPrefixesJSONTransformer;
+ (id)encodingTypeJSONTransformer;
+ (id)uploadsJSONTransformer;
- (void).cxx_destruct;
@end

