/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSRequest.h"

@class NSString, AWSS3CompletedMultipartUpload;

@interface AWSS3CompleteMultipartUploadRequest : AWSRequest {
	NSString* _bucket;
	NSString* _key;
	AWSS3CompletedMultipartUpload* _multipartUpload;
	NSString* _uploadId;
}
@property(retain, nonatomic) NSString* bucket;
@property(retain, nonatomic) NSString* key;
@property(retain, nonatomic) AWSS3CompletedMultipartUpload* multipartUpload;
@property(retain, nonatomic) NSString* uploadId;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)multipartUploadJSONTransformer;
- (void).cxx_destruct;
@end

