/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSRequest.h"

@class NSString, NSDictionary;

@interface AWSSNSCreatePlatformApplicationInput : AWSRequest {
	NSDictionary* _attributes;
	NSString* _name;
	NSString* _platform;
}
@property(retain, nonatomic) NSDictionary* attributes;
@property(retain, nonatomic) NSString* name;
@property(retain, nonatomic) NSString* platform;
+ (id)JSONKeyPathsByPropertyKey;
- (void).cxx_destruct;
@end

