/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class NSString;

@interface AWSSTSFederatedUser : AWSModel {
	NSString* _arn;
	NSString* _federatedUserId;
}
@property(retain, nonatomic) NSString* arn;
@property(retain, nonatomic) NSString* federatedUserId;
+ (id)JSONKeyPathsByPropertyKey;
- (void).cxx_destruct;
@end

