/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class AWSServiceConfiguration, AWSSynchronizedMutableDictionary;

@interface AWSServiceManager : XXUnknownSuperclass {
	AWSServiceConfiguration* _defaultServiceConfiguration;
	AWSSynchronizedMutableDictionary* _dictionary;
}
@property(retain, nonatomic) AWSServiceConfiguration* defaultServiceConfiguration;
@property(retain, nonatomic) AWSSynchronizedMutableDictionary* dictionary;
+ (id)defaultServiceManager;
- (id)init;
- (void).cxx_destruct;
- (void)removeServiceForKey:(id)key;
- (id)serviceForKey:(id)key;
- (void)setService:(id)service forKey:(id)key;
@end

