/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class AWSS3RedirectAllRequestsTo, NSArray, AWSS3ErrorDocument, AWSS3IndexDocument;

@interface AWSS3WebsiteConfiguration : AWSModel {
	AWSS3ErrorDocument* _errorDocument;
	AWSS3IndexDocument* _indexDocument;
	AWSS3RedirectAllRequestsTo* _redirectAllRequestsTo;
	NSArray* _routingRules;
}
@property(retain, nonatomic) AWSS3ErrorDocument* errorDocument;
@property(retain, nonatomic) AWSS3IndexDocument* indexDocument;
@property(retain, nonatomic) AWSS3RedirectAllRequestsTo* redirectAllRequestsTo;
@property(retain, nonatomic) NSArray* routingRules;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)errorDocumentJSONTransformer;
+ (id)indexDocumentJSONTransformer;
+ (id)redirectAllRequestsToJSONTransformer;
+ (id)routingRulesJSONTransformer;
- (void).cxx_destruct;
@end

