/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class NSString, NSArray;

@interface AWSS3CloudFunctionConfiguration : AWSModel {
	NSString* _cloudFunction;
	int _event;
	NSArray* _events;
	NSString* _id;
	NSString* _invocationRole;
}
@property(retain, nonatomic) NSString* cloudFunction;
@property(assign, nonatomic) int event;
@property(retain, nonatomic) NSArray* events;
@property(retain, nonatomic) NSString* id;
@property(retain, nonatomic) NSString* invocationRole;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)eventJSONTransformer;
- (void).cxx_destruct;
@end

