/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSModel.h"

@class NSData, NSString, NSArray;

@interface AWSSQSMessageAttributeValue : AWSModel {
	NSArray* _binaryListValues;
	NSData* _binaryValue;
	NSString* _dataType;
	NSArray* _stringListValues;
	NSString* _stringValue;
}
@property(retain, nonatomic) NSArray* binaryListValues;
@property(retain, nonatomic) NSData* binaryValue;
@property(retain, nonatomic) NSString* dataType;
@property(retain, nonatomic) NSArray* stringListValues;
@property(retain, nonatomic) NSString* stringValue;
+ (id)JSONKeyPathsByPropertyKey;
- (void).cxx_destruct;
@end

