/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSURLRequestRetryHandler.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "NSObject.h"

@class NSString;

@protocol AWSURLRequestRetryHandler <NSObject>
@property(assign, nonatomic) unsigned maxRetryCount;
- (int)shouldRetry:(unsigned)retry response:(id)response data:(id)data error:(id)error;
- (double)timeIntervalForRetry:(unsigned)retry response:(id)response data:(id)data error:(id)error;
@end

@interface AWSURLRequestRetryHandler : XXUnknownSuperclass <AWSURLRequestRetryHandler> {
	BOOL _isClockSkewRetried;
	unsigned _maxRetryCount;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) unsigned hash;
@property(assign) BOOL isClockSkewRetried;
@property(assign, nonatomic) unsigned maxRetryCount;
@property(readonly, assign) Class superclass;
- (id)initWithMaximumRetryCount:(unsigned)maximumRetryCount;
- (BOOL)isClockSkewError:(id)error;
- (int)shouldRetry:(unsigned)retry response:(id)response data:(id)data error:(id)error;
- (double)timeIntervalForRetry:(unsigned)retry response:(id)response data:(id)data error:(id)error;
@end

