/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSURLSessionDelegate.h"
#import "NSURLSessionDataDelegate.h"
#import "NSURLSessionDownloadDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSURLSession, AWSNetworkingConfiguration, AWSSynchronizedMutableDictionary;

@interface AWSURLSessionManager : XXUnknownSuperclass <NSURLSessionDelegate, NSURLSessionDataDelegate, NSURLSessionDownloadDelegate> {
	AWSNetworkingConfiguration* _configuration;
	NSURLSession* _session;
	AWSSynchronizedMutableDictionary* _sessionManagerDelegates;
}
@property(retain, nonatomic) AWSNetworkingConfiguration* configuration;
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) NSURLSession* session;
@property(retain, nonatomic) AWSSynchronizedMutableDictionary* sessionManagerDelegates;
@property(readonly, assign) Class superclass;
- (id)init;
- (void).cxx_destruct;
- (void)URLSession:(id)session dataTask:(id)task didBecomeDownloadTask:(id)task3;
- (void)URLSession:(id)session dataTask:(id)task didReceiveData:(id)data;
- (void)URLSession:(id)session dataTask:(id)task didReceiveResponse:(id)response completionHandler:(id)handler;
- (void)URLSession:(id)session downloadTask:(id)task didFinishDownloadingToURL:(id)url;
- (void)URLSession:(id)session downloadTask:(id)task didResumeAtOffset:(long long)offset expectedTotalBytes:(long long)bytes;
- (void)URLSession:(id)session downloadTask:(id)task didWriteData:(long long)data totalBytesWritten:(long long)written totalBytesExpectedToWrite:(long long)write;
- (void)URLSession:(id)session task:(id)task didCompleteWithError:(id)error;
- (void)URLSession:(id)session task:(id)task didSendBodyData:(long long)data totalBytesSent:(long long)sent totalBytesExpectedToSend:(long long)send;
- (void)dataTaskWithRequest:(id)request completionHandler:(id)handler;
- (void)downloadTaskWithRequest:(id)request completionHandler:(id)handler;
- (void)taskWithDelegate:(id)delegate;
- (void)uploadTaskWithRequest:(id)request completionHandler:(id)handler;
@end

