/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "BFAppLinkReturnToRefererViewDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSURL, NSString, BFAppLinkReturnToRefererView, UINavigationController, BFURL;
@protocol BFAppLinkReturnToRefererControllerDelegate;

@interface BFAppLinkReturnToRefererController : XXUnknownSuperclass <BFAppLinkReturnToRefererViewDelegate> {
	BFURL* _lastShownBFUrl;
	NSURL* _lastShownUrl;
	BFAppLinkReturnToRefererView* _view;
	id<BFAppLinkReturnToRefererControllerDelegate> _delegate;
	UINavigationController* _attachedToNavController;
}
@property(retain, nonatomic) UINavigationController* attachedToNavController;
@property(readonly, copy) NSString* debugDescription;
@property(assign, nonatomic) __weak id<BFAppLinkReturnToRefererControllerDelegate> delegate;
@property(readonly, copy) NSString* description;
@property(readonly, assign) unsigned hash;
@property(readonly, assign) Class superclass;
@property(retain, nonatomic) BFAppLinkReturnToRefererView* view;
- (id)init;
- (id)initForDisplayAboveNavController:(id)displayAboveNavController;
- (void).cxx_destruct;
- (void)closeViewAnimated:(BOOL)animated;
- (void)dealloc;
- (void)moveNavigationBar;
- (void)openRefererAppLink:(id)link;
- (void)orientationDidChange:(id)orientation;
- (void)removeFromNavController;
- (void)returnToRefererViewDidTapInsideCloseButton:(id)returnToRefererView;
- (void)returnToRefererViewDidTapInsideLink:(id)returnToRefererView link:(id)link;
- (void)showViewForRefererAppLink:(id)refererAppLink;
- (void)showViewForRefererURL:(id)refererURL;
- (void)statusBarFrameDidChange:(id)statusBarFrame;
- (void)statusBarFrameWillChange:(id)statusBarFrame;
@end

