/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class BFTask;

@interface BFTaskCompletionSource : XXUnknownSuperclass {
	BFTask* _task;
}
@property(retain, nonatomic) BFTask* task;
+ (id)taskCompletionSource;
- (id)init;
- (void).cxx_destruct;
- (void)cancel;
- (void)setError:(id)error;
- (void)setException:(id)exception;
- (void)setResult:(id)result;
- (BOOL)trySetCancelled;
- (BOOL)trySetError:(id)error;
- (BOOL)trySetException:(id)exception;
- (BOOL)trySetResult:(id)result;
@end

