/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

typedef struct _NSZone NSZone;

typedef struct CGPoint {
	float x;
	float y;
} CGPoint;

typedef struct CGSize {
	float width;
	float height;
} CGSize;

typedef struct CGRect {
	CGPoint origin;
	CGSize size;
} CGRect;

typedef struct _NSRange {
	unsigned _field1;
	unsigned _field2;
} NSRange;

typedef struct CATransform3D {
	float _field1;
	float _field2;
	float _field3;
	float _field4;
	float _field5;
	float _field6;
	float _field7;
	float _field8;
	float _field9;
	float _field10;
	float _field11;
	float _field12;
	float _field13;
	float _field14;
	float _field15;
	float _field16;
} CATransform3D;

typedef struct {
	unsigned long _field1;
	id* _field2;
	unsigned long* _field3;
	unsigned long _field4[5];
} XXStruct_kFm5bA;

typedef struct CGColor* CGColorRef;

typedef struct UIEdgeInsets {
	float top;
	float left;
	float bottom;
	float right;
} UIEdgeInsets;

typedef struct CGContext* CGContextRef;

typedef struct _FileHashComputationContext {
	/*function-pointer*/ void* _field1;
	/*function-pointer*/ void* _field2;
	/*function-pointer*/ void* _field3;
	unsigned _field4;
	char** _field5;
} FileHashComputationContext;

typedef struct CGPath* CGPathRef;

typedef struct CGGradient* CGGradientRef;

typedef struct __SCNetworkReachability* SCNetworkReachabilityRef;

typedef struct __SecTrust SecTrust;

typedef struct __CFRunLoop* CFRunLoopRef;

typedef struct __CFString* CFStringRef;

typedef struct {
	int _field1;
	void* _field2;
	/*function-pointer*/ void* _field3;
	/*function-pointer*/ void* _field4;
	/*function-pointer*/ void* _field5;
} XXStruct_K1psTC;

typedef struct sqlite3 sqlite3;

typedef struct dispatch_queue_s dispatch_queue_s;

typedef struct sqlite3_stmt sqlite3_stmt;

typedef struct CGAffineTransform {
	float a;
	float b;
	float c;
	float d;
	float tx;
	float ty;
} CGAffineTransform;

typedef struct __SecRandom SecRandom;

typedef struct FBLikeControlLayout {
	CGSize _field1;
	CGRect _field2;
	CGRect _field3;
} FBLikeControlLayout;

typedef struct {
	double latitude;
	double longitude;
} XXStruct_zYrK5D;

typedef struct __CFDictionary* CFDictionaryRef;

typedef struct __CTFrame* CTFrameRef;

typedef struct {
	int location;
	int length;
} XXStruct_ny2fMB;

typedef struct __CFAttributedString* CFAttributedStringRef;

typedef struct in_addr {
	unsigned _field1;
} in_addr;

typedef struct sockaddr_in {
	unsigned char _field1;
	unsigned char _field2;
	unsigned short _field3;
	in_addr _field4;
	BOOL _field5[8];
} sockaddr_in;

typedef struct _TBXMLAttribute {
	char* _field1;
	char* _field2;
	TBXMLAttribute* _field3;
} TBXMLAttribute;

typedef struct _TBXMLElement {
	char* _field1;
	char* _field2;
	TBXMLAttribute* _field3;
	TBXMLElement* _field4;
	TBXMLElement* _field5;
	TBXMLElement* _field6;
	TBXMLElement* _field7;
	TBXMLElement* _field8;
} TBXMLElement;

typedef struct _TBXMLElementBuffer {
	TBXMLElement* _field1;
	TBXMLElementBuffer* _field2;
	TBXMLElementBuffer* _field3;
} TBXMLElementBuffer;

typedef struct _TBXMLAttributeBuffer {
	TBXMLAttribute* _field1;
	TBXMLAttributeBuffer* _field2;
	TBXMLAttributeBuffer* _field3;
} TBXMLAttributeBuffer;


