/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class DAO_db_word060, DAO_db_characterpart, DAO_db_sentence050, DAO_db_translation_jpn, DAO_db_lesson, DAO_db_word030, DAO_db_character, DAO_db_word, DAO_db_word040, DAO_db_sentence030, DAO_db_word050, DAO_db_level, DAO_db_translation_krn, CSDBUpdateModel, DAO_db_updateStatus, DAO_db_word020, DAO_db_sentence010, DAO_db_sentence040, DAO_db_sentence020, DAO_db_sentence, DAO_db_word010, DAO_db_unit;

__attribute__((visibility("hidden")))
@interface CSAWSDownloadCenter : XXUnknownSuperclass {
	BOOL _isUpdatingDataBase;
	int _updateCount;
	DAO_db_unit* _db_unit;
	DAO_db_level* _db_level;
	DAO_db_lesson* _db_lesson;
	DAO_db_updateStatus* _db_updateStatus;
	DAO_db_character* _db_character;
	DAO_db_characterpart* _db_characterpart;
	DAO_db_sentence010* _db_sentence010;
	DAO_db_sentence020* _db_sentence020;
	DAO_db_sentence030* _db_sentence030;
	DAO_db_sentence040* _db_sentence040;
	DAO_db_sentence050* _db_sentence050;
	DAO_db_sentence* _db_sentence;
	DAO_db_translation_jpn* _db_translation_jpn;
	DAO_db_translation_krn* _db_translation_krn;
	DAO_db_word010* _db_word010;
	DAO_db_word020* _db_word020;
	DAO_db_word030* _db_word030;
	DAO_db_word040* _db_word040;
	DAO_db_word050* _db_word050;
	DAO_db_word060* _db_word060;
	DAO_db_word* _db_word;
	CSDBUpdateModel* _maxVersionModel;
}
@property(retain, nonatomic) DAO_db_character* db_character;
@property(retain, nonatomic) DAO_db_characterpart* db_characterpart;
@property(retain, nonatomic) DAO_db_lesson* db_lesson;
@property(retain, nonatomic) DAO_db_level* db_level;
@property(retain, nonatomic) DAO_db_sentence* db_sentence;
@property(retain, nonatomic) DAO_db_sentence010* db_sentence010;
@property(retain, nonatomic) DAO_db_sentence020* db_sentence020;
@property(retain, nonatomic) DAO_db_sentence030* db_sentence030;
@property(retain, nonatomic) DAO_db_sentence040* db_sentence040;
@property(retain, nonatomic) DAO_db_sentence050* db_sentence050;
@property(retain, nonatomic) DAO_db_translation_jpn* db_translation_jpn;
@property(retain, nonatomic) DAO_db_translation_krn* db_translation_krn;
@property(retain, nonatomic) DAO_db_unit* db_unit;
@property(retain, nonatomic) DAO_db_updateStatus* db_updateStatus;
@property(retain, nonatomic) DAO_db_word* db_word;
@property(retain, nonatomic) DAO_db_word010* db_word010;
@property(retain, nonatomic) DAO_db_word020* db_word020;
@property(retain, nonatomic) DAO_db_word030* db_word030;
@property(retain, nonatomic) DAO_db_word040* db_word040;
@property(retain, nonatomic) DAO_db_word050* db_word050;
@property(retain, nonatomic) DAO_db_word060* db_word060;
@property(assign, nonatomic) BOOL isUpdatingDataBase;
@property(retain, nonatomic) CSDBUpdateModel* maxVersionModel;
@property(assign, nonatomic) int updateCount;
+ (id)sharedOperator;
- (id)init;
- (void).cxx_destruct;
- (void)Start;
- (void)checkAndUpdateAWSDDBSuccess:(id)success failure:(id)failure;
- (void)finishUpdateSuccess;
- (void)initialize;
- (BOOL)needUpdate;
- (void)releaseAllDBOperator;
- (void)setupDBOperator;
- (void)updateCharacterTableWithData:(id)data;
- (void)updateCharacterpartTableWithData:(id)data;
- (void)updateHomeViewWithData:(id)data;
- (void)updateJPNOrKRNWithData:(id)data;
- (void)updateOneLessonWithData:(id)data;
- (void)updateOneUnitViewWithData:(id)data;
- (void)updateSentence010TableWithData:(id)data;
- (void)updateSentence020TableWithData:(id)data;
- (void)updateSentence030TableWithData:(id)data;
- (void)updateSentence040TableWithData:(id)data;
- (void)updateSentence050TableWithData:(id)data;
- (void)updateSentenceTableWithData:(id)data;
- (void)updateTranslationJPN:(id)jpn;
- (void)updateTranslationKRN:(id)krn;
- (void)updateWord010WithData:(id)data;
- (void)updateWord020WithData:(id)data;
- (void)updateWord030WithData:(id)data;
- (void)updateWord040WithData:(id)data;
- (void)updateWord050WithData:(id)data;
- (void)updateWord060WithData:(id)data;
- (void)updateWordWithData:(id)data;
@end

