/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSURLConnection, NSMutableData;

__attribute__((visibility("hidden")))
@interface CSiPhonePlusThirtPartLogin : XXUnknownSuperclass {
	NSMutableData* _feedXML;
	NSString* _usernameCode;
	NSURLConnection* _connection;
	NSString* _EmailAddress;
}
@property(assign, nonatomic) __weak NSString* EmailAddress;
@property(retain, nonatomic) NSURLConnection* connection;
@property(retain, nonatomic) NSMutableData* feedXML;
@property(retain, nonatomic) NSString* usernameCode;
- (void).cxx_destruct;
- (void)connection:(id)connection didFailWithError:(id)error;
- (void)connection:(id)connection didReceiveData:(id)data;
- (void)connection:(id)connection didReceiveResponse:(id)response;
- (void)connectionDidFinishLoading:(id)connection;
- (void)handleError:(id)error;
- (void)loginWithExchangeCode:(id)exchangeCode withUserName:(id)userName;
- (void)signupSuccess;
@end

