/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface CSLessonResultModel : XXUnknownSuperclass {
	int _rightCount;
	int _errorCount;
	int _testCount;
	int _nGetScore;
	int _nTotalScore;
	int _nSencond;
}
@property(assign, nonatomic) int errorCount;
@property(assign, nonatomic) int nGetScore;
@property(assign, nonatomic) int nSencond;
@property(assign, nonatomic) int nTotalScore;
@property(assign, nonatomic) int rightCount;
@property(assign, nonatomic) int testCount;
@end

