/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface CSLessonResultCheck : XXUnknownSuperclass {
}
+ (id)ReplacePinyinTangue:(id)tangue;
+ (id)checkResultWithSentenceModel1M_data:(id)sentenceModel1M_data m_model:(id)model CurAnswer:(int)answer;
+ (id)checkResultWithSentenceModel2M_data:(id)sentenceModel2M_data m_model:(id)model InputStr:(id)str;
+ (id)checkResultWithSentenceModel3M_data:(id)sentenceModel3M_data m_model:(id)model CurAnswer:(int)answer;
+ (id)checkResultWithSentenceModel4M_data:(id)sentenceModel4M_data m_model:(id)model MyAnswer:(id)answer;
+ (id)checkResultWithSentenceModel5M_data:(id)sentenceModel5M_data m_model:(id)model MyAnswer:(id)answer;
+ (id)checkResultWithSentenceModel6M_data:(id)sentenceModel6M_data m_model:(id)model InputStr:(id)str;
+ (id)checkResultWithWordModel1M_data:(id)wordModel1M_data m_model:(id)model userAnswerWordId:(int)anId;
+ (id)checkResultWithWordModel2M_data:(id)wordModel2M_data m_model:(id)model userAnswerWordId:(int)anId;
+ (id)checkResultWithWordModel3M_data:(id)wordModel3M_data m_model:(id)model userAnswer:(id)answer;
+ (id)checkResultWithWordModel4M_data:(id)wordModel4M_data m_model:(id)model userAnswer:(id)answer;
+ (id)checkResultWithWordModel5M_data:(id)wordModel5M_data m_model:(id)model CorrentAnswerAfterRandom:(id)random RightString:(id)string CurAnswer:(int)answer;
+ (id)checkResultWithWordModel6M_data:(id)wordModel6M_data m_model:(id)model CorrentAnswerAfterRandom:(id)random CurAnswer:(int)answer;
@end

