/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface CSLessonRegexModel : XXUnknownSuperclass {
	int _nWordSentenceType;
	int _nWordSentenceId;
	int _nModelType;
	int _nModelId;
}
@property(assign, nonatomic) int nModelId;
@property(assign, nonatomic) int nModelType;
@property(assign, nonatomic) int nWordSentenceId;
@property(assign, nonatomic) int nWordSentenceType;
+ (id)characterReviewListToModel:(id)model withWordSentenceType:(int)wordSentenceType modelType:(int)type;
+ (id)m_RegexListToModel:(id)model;
+ (id)m_TestListToModel:(id)model withWordSentenceType:(int)wordSentenceType modelType:(int)type;
+ (id)sentenceReviewListToModel:(id)model withWordSentenceType:(int)wordSentenceType modelType:(int)type;
+ (id)wordReviewListToModel:(id)model withWordSentenceType:(int)wordSentenceType modelType:(int)type;
@end

