/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ChineseSkillNew-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UILabel, NSString;

__attribute__((visibility("hidden")))
@interface CSLSFluencyScoreImageView : XXUnknownSuperclass {
	NSString* _fluency;
	UILabel* _fluencyLabel;
}
@property(retain, nonatomic) NSString* fluency;
@property(retain, nonatomic) UILabel* fluencyLabel;
- (void).cxx_destruct;
- (id)getColor:(int)color;
- (void)layoutSubviews;
- (void)setFrame:(CGRect)frame;
@end

