/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol CSMainLeftView_iPhone6Delegate <NSObject>
@optional
- (void)GiftBoxBtnClicked;
- (void)ListenSpeakBtnClicked;
- (void)mainBtnClicked;
- (void)portraitImageClicked;
- (void)settingBtnClicked;
@end

