/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface CSReviewResouceDownloader : XXUnknownSuperclass {
}
+ (id)sharedOperator;
- (void)dealloc;
- (void)downloadAllSentenceResource:(id)resource;
- (void)downloadSentenceFamilyResource:(id)resource;
- (BOOL)isFileExistWithSentenceId:(int)sentenceId;
- (void)removeFilesToDownload;
- (void)timerStart;
- (void)timerStop;
@end

