/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "UITextViewDelegate.h"
#import "ChineseSkillNew-Structs.h"

@class UserStatisticsPayloadModel, UIButton, UITextView, UILabel, NSString, UIImageView, UIImage;
@protocol CSReportStatusDelegate;

__attribute__((visibility("hidden")))
@interface CSReportController : XXUnknownSuperclass <UITextViewDelegate> {
	BOOL _imageState;
	UIImage* _sendImage;
	NSString* _sendText;
	id<CSReportStatusDelegate> _delegate;
	UserStatisticsPayloadModel* _model;
	UITextView* _textView;
	UIImageView* _sendImageView;
	UILabel* _placeholder;
	UIImageView* _shapePin;
	UIButton* _doneBtn;
}
@property(readonly, copy) NSString* debugDescription;
@property(assign, nonatomic) __weak id<CSReportStatusDelegate> delegate;
@property(readonly, copy) NSString* description;
@property(retain, nonatomic) UIButton* doneBtn;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic, getter=isClosed) BOOL imageState;
@property(retain, nonatomic) UserStatisticsPayloadModel* model;
@property(retain, nonatomic) UILabel* placeholder;
@property(retain, nonatomic) UIImage* sendImage;
@property(retain, nonatomic) UIImageView* sendImageView;
@property(retain, nonatomic) NSString* sendText;
@property(retain, nonatomic) UIImageView* shapePin;
@property(readonly, assign) Class superclass;
@property(retain, nonatomic) UITextView* textView;
- (void).cxx_destruct;
- (void)MailSendWithImage:(id)image andText:(id)text model:(id)model;
- (void)adjustPanelsWithKeyBordHeight:(float)keyBordHeight;
- (void)dealloc;
- (void)handleKeyboardDidShow:(id)handleKeyboard;
- (void)hideKeyboard;
- (void)imageBtnClicked:(id)clicked;
- (void)keyboardWillHide;
- (void)keyboardWillShow;
- (void)mailCancel:(id)cancel;
- (void)mailSend:(id)send;
- (void)setupDoneButton;
- (void)setupImageView;
- (void)setupTextView;
- (void)setupTopView;
- (void)stopEditing;
- (void)textViewDidChange:(id)textView;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)view;
@end

