/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol CSScrollViewDelegate <NSObject>
@optional
- (void)beginTouches:(id)touches withEvent:(id)event;
- (void)cancelledtouches:(id)cancelledtouches withEvent:(id)event;
- (void)endedTouches:(id)touches withEvent:(id)event;
- (void)movedTouches:(id)touches withEvent:(id)event;
@end

