/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ChineseSkillNew-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIView;
@protocol CSShareSheetBtnClickedDelegate;

__attribute__((visibility("hidden")))
@interface CSShareIconSheet : XXUnknownSuperclass {
	id<CSShareSheetBtnClickedDelegate> _delegate;
	UIView* _backgroundView;
}
@property(retain, nonatomic) UIView* backgroundView;
@property(assign, nonatomic) __weak id<CSShareSheetBtnClickedDelegate> delegate;
- (id)initWithFrame:(CGRect)frame;
- (void).cxx_destruct;
- (void)cancel;
- (id)getData;
- (void)layoutSubviews;
- (void)setCancelBtn;
- (void)setIconSheet;
- (void)setbackgroundView;
- (void)shareBtnClicked:(id)clicked;
@end

