/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface CSShareIconSheetData : XXUnknownSuperclass {
	NSString* _imageName;
	NSString* _snsName;
}
@property(copy, nonatomic) NSString* imageName;
@property(retain, nonatomic) NSString* snsName;
- (id)initWithImageName:(id)imageName andSnsName:(id)name;
- (void).cxx_destruct;
@end

