/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "FBLoginViewDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class FBLoginView, NSString, STTwitterAPI;

__attribute__((visibility("hidden")))
@interface CSSSO : XXUnknownSuperclass <FBLoginViewDelegate> {
	STTwitterAPI* _twitter;
	FBLoginView* _loginView;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) FBLoginView* loginView;
@property(readonly, assign) Class superclass;
@property(retain, nonatomic) STTwitterAPI* twitter;
- (void).cxx_destruct;
- (void)getFacebookUserInfo;
- (void)loginWithLoginType:(id)loginType Success:(id)success failure:(id)failure;
@end

