/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface CSSurvivalResourceDLCenter : XXUnknownSuperclass {
	BOOL _isUpzipping;
}
@property(assign, nonatomic) BOOL isUpzipping;
+ (id)sharedOperator;
- (BOOL)IsFileExist:(id)exist Path:(id)path;
- (void)downloadSurvivalResourceWithId:(int)anId;
- (float)getProgressWithSurvivalId:(int)survivalId Total:(int)total;
- (BOOL)isParam:(id)param AlreadyInList:(id)list;
- (void)reDownloadWithSurvivalCid:(int)survivalCid andDeletePath:(id)path;
@end

