/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ChineseSkillNew-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class CSTabBarButton, NSMutableArray;
@protocol CSTabBarDelegate;

__attribute__((visibility("hidden")))
@interface CSTabBar : XXUnknownSuperclass {
	id<CSTabBarDelegate> _delegate;
	NSMutableArray* _tabBarButtons;
	CSTabBarButton* _selectedButton;
}
@property(assign, nonatomic) __weak id<CSTabBarDelegate> delegate;
@property(assign, nonatomic) __weak CSTabBarButton* selectedButton;
@property(retain, nonatomic) NSMutableArray* tabBarButtons;
- (id)initWithFrame:(CGRect)frame;
- (void).cxx_destruct;
- (void)addTabBarButtonWithItem:(id)item;
- (void)buttonClick:(id)click;
- (void)layoutSubviews;
@end

