/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ChineseSkillNew-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIColor;

__attribute__((visibility("hidden")))
@interface DACircularProgressLayer : XXUnknownSuperclass {
}
@property(assign, nonatomic) int clockwiseProgress;
@property(assign, nonatomic) float progress;
@property(retain, nonatomic) UIColor* progressTintColor;
@property(assign, nonatomic) int roundedCorners;
@property(assign, nonatomic) float thicknessRatio;
@property(retain, nonatomic) UIColor* trackTintColor;
+ (BOOL)needsDisplayForKey:(id)key;
- (void)drawInContext:(CGContextRef)context;
@end

