/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSTimer, NSString, NSArray;

__attribute__((visibility("hidden")))
@interface DataWriteToFile : XXUnknownSuperclass {
	BOOL _file_mutex_lock;
	BOOL _buffer_mutex_lock;
	BOOL _isUploading;
	NSArray* _StatistDataArray;
	NSString* _targetPath;
	NSString* _txtBuffer;
	NSTimer* _timer;
	int _nSendLine;
	int _nTryTime;
}
@property(retain, nonatomic) NSArray* StatistDataArray;
@property(assign, nonatomic) BOOL buffer_mutex_lock;
@property(assign, nonatomic) BOOL file_mutex_lock;
@property(assign, nonatomic) BOOL isUploading;
@property(assign) int nSendLine;
@property(assign) int nTryTime;
@property(retain, nonatomic) NSString* targetPath;
@property(retain, nonatomic) NSTimer* timer;
@property(retain, nonatomic) NSString* txtBuffer;
+ (id)sharedOperator;
- (id)init;
- (void).cxx_destruct;
- (void)Repeat_CheckAndUpload;
- (void)Start;
- (void)WriteToFileNow:(id)fileNow;
- (BOOL)checkFileDirectoryAndCreateItsDirectoryIfNotExist:(id)exist;
- (void)uploadFail;
- (void)uploadSuccess;
- (void)writeToFileWithData:(id)data;
@end

