/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ChineseSkillNew-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "UITableViewDelegate.h"
#import "UITableViewDataSource.h"

@class NSArray, NSString, UIColor, UIView, UIImage, UITableView;
@protocol DOPDropDownMenuDataSource, DOPDropDownMenuDelegate;

__attribute__((visibility("hidden")))
@interface DOPDropDownMenu : XXUnknownSuperclass <UITableViewDataSource, UITableViewDelegate> {
	BOOL _show;
	id<DOPDropDownMenuDataSource> _dataSource;
	id<DOPDropDownMenuDelegate> _delegate;
	UIColor* _indicatorColor;
	UIColor* _textColor;
	UIColor* _separatorColor;
	UIImage* _backgroundImage;
	int _currentSelectedMenudIndex;
	int _numOfMenu;
	UIView* _backGroundView;
	UITableView* _tableView;
	NSArray* _array;
	NSArray* _titles;
	NSArray* _indicators;
	NSArray* _bgLayers;
	CGPoint _origin;
}
@property(copy, nonatomic) NSArray* array;
@property(retain, nonatomic) UIView* backGroundView;
@property(retain, nonatomic) UIImage* backgroundImage;
@property(copy, nonatomic) NSArray* bgLayers;
@property(assign, nonatomic) int currentSelectedMenudIndex;
@property(assign, nonatomic) __weak id<DOPDropDownMenuDataSource> dataSource;
@property(readonly, copy) NSString* debugDescription;
@property(assign, nonatomic) __weak id<DOPDropDownMenuDelegate> delegate;
@property(readonly, copy) NSString* description;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) UIColor* indicatorColor;
@property(copy, nonatomic) NSArray* indicators;
@property(assign, nonatomic) int numOfMenu;
@property(assign, nonatomic) CGPoint origin;
@property(retain, nonatomic) UIColor* separatorColor;
@property(assign, nonatomic) BOOL show;
@property(readonly, assign) Class superclass;
@property(retain, nonatomic) UITableView* tableView;
@property(retain, nonatomic) UIColor* textColor;
@property(copy, nonatomic) NSArray* titles;
- (id)initWithOrigin:(CGPoint)origin andHeight:(float)height;
- (void).cxx_destruct;
- (void)animateBackGroundView:(id)view show:(BOOL)show complete:(id)complete;
- (void)animateIdicator:(id)idicator background:(id)background tableView:(id)view title:(id)title forward:(BOOL)forward complecte:(id)complecte;
- (void)animateIndicator:(id)indicator Forward:(BOOL)forward complete:(id)complete;
- (void)animateTableView:(id)view show:(BOOL)show complete:(id)complete;
- (void)animateTitle:(id)title show:(BOOL)show complete:(id)complete;
- (void)backgroundSwipped:(id)swipped;
- (void)backgroundTapped:(id)tapped;
- (CGSize)calculateTitleSizeWithString:(id)string;
- (void)confiMenuWithSelectRow:(int)selectRow;
- (void)configureCell:(id)cell forIndexPath:(id)indexPath;
- (id)createBgLayerWithColor:(id)color andPosition:(CGPoint)position;
- (id)createIndicatorWithColor:(id)color andPosition:(CGPoint)position;
- (id)createSeparatorLineWithColor:(id)color andPosition:(CGPoint)position;
- (id)createTextLayerWithNSString:(id)nsstring withColor:(id)color andPosition:(CGPoint)position count:(int)count;
- (void)dealloc;
- (void)menuTapped:(id)tapped;
- (void)setupTableViewCatergoryIllustration;
- (id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
- (void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
- (int)tableView:(id)view numberOfRowsInSection:(int)section;
- (id)tableViewCellWithReuseIdentifier:(id)reuseIdentifier;
- (id)titleForRowAtIndexPath:(id)indexPath;
@end

