/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface FBAppBridgeScheme : XXUnknownSuperclass {
	NSString* _version;
}
@property(copy, nonatomic) NSString* version;
+ (id)bridgeSchemeForFBAppForLike;
+ (id)bridgeSchemeForFBAppForOpenGraphActionShareDialogParams:(id)openGraphActionShareDialogParams;
+ (id)bridgeSchemeForFBAppForShareDialogParams:(id)shareDialogParams;
+ (id)bridgeSchemeForFBAppForShareDialogPhotos;
+ (id)bridgeSchemeForFBMessengerForOpenGraphActionShareDialogParams:(id)openGraphActionShareDialogParams;
+ (id)bridgeSchemeForFBMessengerForShareDialogParams:(id)shareDialogParams;
+ (id)bridgeSchemeForFBMessengerForShareDialogPhotos;
+ (id)bridgeVersions;
+ (id)installedFBNativeAppVersionForMethod:(id)method minVersion:(id)version;
+ (BOOL)isSupportedScheme:(id)scheme;
+ (id)schemePrefix;
+ (id)urlForMethod:(id)method queryParams:(id)params schemeVersion:(id)version version:(id)version4;
- (id)initWithVersion:(id)version;
- (void)dealloc;
- (id)urlForMethod:(id)method queryParams:(id)params;
@end

