/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSURL, NSFileManager;

@interface FBAudioResourceLoader : XXUnknownSuperclass {
	NSFileManager* _fileManager;
	NSURL* _fileURL;
	unsigned long _systemSoundID;
}
+ (id)data;
+ (id)name;
+ (id)sharedLoader;
+ (unsigned)version;
- (id)init;
- (id)_fileResourceURL;
- (id)_fileURL:(id*)url;
- (void)dealloc;
- (BOOL)loadSound:(id*)sound;
- (void)playSound;
@end

