/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface FBCacheEntityInfo : XXUnknownSuperclass {
	NSString* _uuid;
	NSString* _key;
	double _accessTime;
	unsigned _fileSize;
	BOOL _dirty;
}
@property(readonly, assign) double accessTime;
@property(assign, getter=isDirty) BOOL dirty;
@property(readonly, assign) unsigned fileSize;
@property(readonly, copy) NSString* key;
@property(readonly, copy) NSString* uuid;
- (id)initWithKey:(id)key uuid:(id)uuid accessTime:(double)time fileSize:(unsigned)size;
- (void)dealloc;
- (void)registerAccess;
@end

