/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSData;

@interface FBCrypto : XXUnknownSuperclass {
	NSData* _encryptionKeyData;
	NSData* _macKeyData;
}
+ (id)makeMasterKey;
+ (id)randomBytes:(unsigned)bytes;
- (id)initWithEncryptionKey:(id)encryptionKey macKey:(id)key;
- (id)initWithMasterKey:(id)masterKey;
- (id)_macForIV:(id)iv cipherData:(id)data additionalDataToSign:(id)sign;
- (void)dealloc;
- (id)decrypt:(id)decrypt additionalSignedData:(id)data;
- (id)encrypt:(id)encrypt additionalDataToSign:(id)sign;
@end

