/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "FBCacheIndexFileDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, FBCacheIndex, NSObject, NSCache;
@protocol OS_dispatch_queue;

@interface FBDataDiskCache : XXUnknownSuperclass <FBCacheIndexFileDelegate> {
	NSCache* _inMemoryCache;
	FBCacheIndex* _cacheIndex;
	NSString* _dataCachePath;
	NSObject<OS_dispatch_queue>* _fileQueue;
}
@property(assign, nonatomic) unsigned cacheSizeMemory;
@property(copy, nonatomic) NSString* dataCachePath;
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign, nonatomic) NSObject<OS_dispatch_queue>* fileQueue;
@property(readonly, assign) unsigned hash;
@property(readonly, assign) Class superclass;
+ (id)sharedCache;
- (id)init;
- (BOOL)_doesFileExist:(id)exist;
- (void)cacheIndex:(id)index deleteFileWithName:(id)name;
- (void)cacheIndex:(id)index writeFileWithName:(id)name data:(id)data;
- (id)dataForURL:(id)url;
- (void)dealloc;
- (void)removeDataForSession:(id)session;
- (void)removeDataForUrl:(id)url;
- (void)setData:(id)data forURL:(id)url;
@end

