/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface FBErrorUtility : XXUnknownSuperclass {
}
+ (int)errorCategoryForError:(id)error;
+ (BOOL)errorIsNetworkError:(id)error;
+ (int)fberrorCategoryFromError:(id)error code:(int)code subcode:(int)subcode returningUserMessage:(id*)message andShouldNotifyUser:(BOOL*)anAnd;
+ (id)fberrorForRetry:(id)retry;
+ (id)fberrorForSystemPasswordChange:(id)systemPasswordChange;
+ (void)fberrorGetCodeValueForError:(id)error index:(unsigned)index code:(int*)code subcode:(int*)subcode;
+ (BOOL)fberrorIsErrorFromSystemSession:(id)systemSession;
+ (id)jsonDictionaryForError:(id)error;
+ (BOOL)shouldNotifyUserForError:(id)error;
+ (id)userMessageForError:(id)error;
@end

