/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSCache;

@interface FBLikeActionControllerCache : XXUnknownSuperclass {
	NSCache* _cache;
}
- (id)init;
- (void)_activeSessionDidChangeWithNotification:(id)_activeSession;
- (void)dealloc;
- (id)objectForKeyedSubscript:(id)keyedSubscript;
- (void)setObject:(id)object forKeyedSubscript:(id)keyedSubscript;
@end

