/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ChineseSkillNew-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class FBLikeActionController, UILabel, NSString, FBLikeBoxView, FBLikeButton, UIColor, UIView;

@interface FBLikeControl : XXUnknownSuperclass {
	FBLikeActionController* _likeActionController;
	FBLikeBoxView* _likeBoxView;
	FBLikeButton* _likeButton;
	UIView* _likeButtonContainer;
	UILabel* _socialSentenceLabel;
	BOOL _soundEnabled;
	UIColor* _foregroundColor;
	unsigned _likeControlAuxiliaryPosition;
	unsigned _likeControlHorizontalAlignment;
	unsigned _likeControlStyle;
	NSString* _objectID;
	float _preferredMaxLayoutWidth;
}
@property(retain, nonatomic) UIColor* foregroundColor;
@property(assign, nonatomic) unsigned likeControlAuxiliaryPosition;
@property(assign, nonatomic) unsigned likeControlHorizontalAlignment;
@property(assign, nonatomic) unsigned likeControlStyle;
@property(copy, nonatomic) NSString* objectID;
@property(assign, nonatomic) float preferredMaxLayoutWidth;
@property(assign, nonatomic, getter=isSoundEnabled) BOOL soundEnabled;
+ (BOOL)dialogIsAvailable;
- (id)initWithFrame:(CGRect)frame;
- (id)_analyticsParameters;
- (id)_auxiliaryView;
- (float)_auxiliaryViewPadding;
- (void)_handleLikeActionControllerDidDisableNotification:(id)_handleLikeActionController;
- (void)_handleLikeActionControllerDidUpdateNotification:(id)_handleLikeActionController;
- (void)_handleLikeButtonTap:(id)tap;
- (void)_handleLikeButtonTouchDown:(id)down;
- (void)_handleLikeButtonTouchUp:(id)up;
- (void)_initializeContent;
- (FBLikeControlLayout)_layoutWithBounds:(CGRect)bounds subviewSizingBlock:(id)block;
- (void)_likeActionControllerDidResetNotification:(id)_likeActionController;
- (void)_resetLikeActionController;
- (void)_updateLikeBoxCaretPosition;
- (void)awakeFromNib;
- (void)dealloc;
- (void)drawRect:(CGRect)rect;
- (CGSize)intrinsicContentSize;
- (void)layoutSubviews;
- (void)setBackgroundColor:(id)color;
- (void)setOpaque:(BOOL)opaque;
- (CGSize)sizeThatFits:(CGSize)fits;
@end

