/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "FBDialogsParams.h"
#import "ChineseSkillNew-Structs.h"

@class NSString, FBAppBridgeScheme;
@protocol FBOpenGraphAction;

@interface FBOpenGraphActionParams : FBDialogsParams {
	id<FBOpenGraphAction> _action;
	NSString* _previewPropertyName;
	NSString* _actionType;
	FBAppBridgeScheme* _bridgeScheme;
}
@property(retain, nonatomic) id<FBOpenGraphAction> action;
@property(copy, nonatomic) NSString* actionType;
@property(retain, nonatomic) FBAppBridgeScheme* bridgeScheme;
@property(copy, nonatomic) NSString* previewPropertyName;
+ (id)getIdOrUrlFromObject:(id)object;
+ (id)getPostedObjectTypeFromObject:(id)object;
+ (id)methodName;
- (id)initWithAction:(id)action actionType:(id)type previewPropertyName:(id)name;
- (BOOL)containsUIImages:(id)images;
- (id)copyWithZone:(NSZone*)zone;
- (void)dealloc;
- (id)dictionaryMethodArgs;
- (id)flattenGraphObjects:(id)objects;
- (id)flattenObject:(id)object;
- (id)validate;
@end

