/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "FBGraphObjectSelectionChangedDelegate.h"
#import "FBGraphObjectViewControllerDelegate.h"
#import "FBViewController.h"
#import "FBGraphObjectPagingLoaderDelegate.h"
#import "ChineseSkillNew-Structs.h"

@class FBGraphObjectPagingLoader, FBGraphObjectTableDataSource, FBGraphObjectTableSelection, NSTimer, NSSet, NSString, FBSession, UITableView, UIActivityIndicatorView;
@protocol FBGraphPlace;

@interface FBPlacePickerViewController : FBViewController <FBGraphObjectSelectionChangedDelegate, FBGraphObjectViewControllerDelegate, FBGraphObjectPagingLoaderDelegate> {
	BOOL _hasSearchTextChangedSinceLastQuery;
	BOOL _trackActiveSession;
	UIActivityIndicatorView* _spinner;
	UITableView* _tableView;
	NSSet* _fieldsForRequest;
	int _radiusInMeters;
	int _resultsLimit;
	NSString* _searchText;
	FBSession* _session;
	FBGraphObjectTableDataSource* _dataSource;
	FBGraphObjectTableSelection* _selectionManager;
	FBGraphObjectPagingLoader* _loader;
	NSTimer* _searchTextChangedTimer;
	XXStruct_zYrK5D _locationCoordinate;
}
@property(retain, nonatomic) FBGraphObjectTableDataSource* dataSource;
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(copy, nonatomic) NSSet* fieldsForRequest;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) BOOL itemPicturesEnabled;
@property(retain, nonatomic) FBGraphObjectPagingLoader* loader;
@property(assign, nonatomic) XXStruct_zYrK5D locationCoordinate;
@property(assign, nonatomic) int radiusInMeters;
@property(assign, nonatomic) int resultsLimit;
@property(copy, nonatomic) NSString* searchText;
@property(retain, nonatomic) NSTimer* searchTextChangedTimer;
@property(readonly, retain, nonatomic) id<FBGraphPlace> selection;
@property(retain, nonatomic) FBGraphObjectTableSelection* selectionManager;
@property(retain, nonatomic) FBSession* session;
@property(retain, nonatomic) UIActivityIndicatorView* spinner;
@property(readonly, assign) Class superclass;
@property(retain, nonatomic) UITableView* tableView;
@property(assign, nonatomic) BOOL trackActiveSession;
+ (id)cacheDescriptorWithLocationCoordinate:(XXStruct_zYrK5D)locationCoordinate radiusInMeters:(int)meters searchText:(id)text resultsLimit:(int)limit fieldsForRequest:(id)request;
+ (id)requestForPlacesSearchAtCoordinate:(XXStruct_zYrK5D)coordinate radiusInMeters:(int)meters resultsLimit:(int)limit searchText:(id)text fields:(id)fields datasource:(id)datasource session:(id)session;
- (id)init;
- (id)initWithCoder:(id)coder;
- (id)initWithNibName:(id)nibName bundle:(id)bundle;
- (void)addSessionObserver:(id)observer;
- (void)centerAndStartSpinner;
- (void)clearData;
- (void)clearSelection;
- (void)configureUsingCachedDescriptor:(id)descriptor;
- (id)createSearchTextChangedTimer;
- (void)dealloc;
- (BOOL)graphObjectTableDataSource:(id)source filterIncludesItem:(id)item;
- (id)graphObjectTableDataSource:(id)source pictureUrlOfItem:(id)item;
- (id)graphObjectTableDataSource:(id)source subtitleOfItem:(id)item;
- (id)graphObjectTableDataSource:(id)source titleOfItem:(id)item;
- (void)graphObjectTableSelectionDidChange:(id)graphObjectTableSelection;
- (void)initialize;
- (void)loadData;
- (void)loadDataPostThrottleSkippingRoundTripIfCached:(id)cached;
- (void)logAppEvents:(BOOL)events;
- (void)observeValueForKeyPath:(id)keyPath ofObject:(id)object change:(id)change context:(void*)context;
- (void)pagingLoader:(id)loader didLoadData:(id)data;
- (void)pagingLoader:(id)loader handleError:(id)error;
- (void)pagingLoader:(id)loader willLoadURL:(id)url;
- (void)pagingLoaderDidFinishLoading:(id)pagingLoader;
- (void)pagingLoaderWasCancelled:(id)cancelled;
- (void)removeSessionObserver:(id)observer;
- (void)searchTextChangedTimerFired:(id)fired;
- (void)updateView;
- (void)viewDidLoad;
- (void)viewDidUnload;
@end

