/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ChineseSkillNew-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, UIImageView, NSDictionary, FBURLConnection;

@interface FBProfilePictureView : XXUnknownSuperclass {
	NSString* _profileID;
	int _pictureCropping;
	NSDictionary* _currentImageQueryParams;
	FBURLConnection* _connection;
	UIImageView* _imageView;
}
@property(retain, nonatomic) FBURLConnection* connection;
@property(copy, nonatomic) NSDictionary* currentImageQueryParams;
@property(retain, nonatomic) UIImageView* imageView;
@property(assign, nonatomic) int pictureCropping;
@property(copy, nonatomic) NSString* profileID;
- (id)init;
- (id)initWithCoder:(id)coder;
- (id)initWithFrame:(CGRect)frame;
- (id)initWithProfileID:(id)profileID pictureCropping:(int)cropping;
- (id)_generateQueryParams;
- (id)_placeholderImage;
- (void)dealloc;
- (void)ensureImageViewContentMode;
- (void)initialize;
- (CGSize)intrinsicContentSize;
- (void)layoutSubviews;
- (void)refreshImage:(BOOL)image;
@end

