/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ChineseSkillNew-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary, FBSession, NSURLConnection, NSMutableData, NSString, NSError;
@protocol FBGraphObject, FBRequestDelegate;

@interface FBRequest : XXUnknownSuperclass {
	id<FBRequestDelegate> _delegate;
	NSString* _url;
	NSString* _versionPart;
	NSURLConnection* _connection;
	NSMutableData* _responseText;
	unsigned _state;
	NSError* _error;
	BOOL _sessionDidExpire;
	id<FBGraphObject> _graphObject;
	BOOL _canCloseSessionOnError;
	BOOL _skipClientToken;
	NSMutableDictionary* _parameters;
	FBSession* _session;
	NSString* _graphPath;
	NSString* _restMethod;
	NSString* _HTTPMethod;
}
@property(copy, nonatomic) NSString* HTTPMethod;
@property(assign, nonatomic) BOOL canCloseSessionOnError;
@property(retain, nonatomic) NSURLConnection* connection;
@property(assign, nonatomic) id<FBRequestDelegate> delegate;
@property(retain, nonatomic) NSError* error;
@property(retain, nonatomic) id<FBGraphObject> graphObject;
@property(copy, nonatomic) NSString* graphPath;
@property(copy, nonatomic) NSString* httpMethod;
@property(readonly, retain, nonatomic) NSMutableDictionary* parameters;
@property(retain, nonatomic) NSMutableDictionary* params;
@property(retain, nonatomic) NSMutableData* responseText;
@property(copy, nonatomic) NSString* restMethod;
@property(retain, nonatomic) FBSession* session;
@property(assign, nonatomic) BOOL sessionDidExpire;
@property(assign, nonatomic) BOOL skipClientToken;
@property(assign, nonatomic) unsigned state;
@property(copy, nonatomic) NSString* url;
@property(readonly, assign) NSString* versionPart;
+ (id)requestForCustomAudienceThirdPartyID:(id)customAudienceThirdPartyID;
+ (id)requestForDeleteObject:(id)deleteObject;
+ (id)requestForGraphPath:(id)graphPath;
+ (id)requestForMe;
+ (id)requestForMyFriends;
+ (id)requestForPlacesSearchAtCoordinate:(XXStruct_zYrK5D)coordinate radiusInMeters:(int)meters resultsLimit:(int)limit searchText:(id)text;
+ (id)requestForPostOpenGraphObject:(id)postOpenGraphObject;
+ (id)requestForPostOpenGraphObjectWithType:(id)type title:(id)title image:(id)image url:(id)url description:(id)description objectProperties:(id)properties;
+ (id)requestForPostStatusUpdate:(id)postStatusUpdate;
+ (id)requestForPostStatusUpdate:(id)postStatusUpdate place:(id)place tags:(id)tags;
+ (id)requestForPostWithGraphPath:(id)graphPath graphObject:(id)object;
+ (id)requestForUpdateOpenGraphObject:(id)updateOpenGraphObject;
+ (id)requestForUpdateOpenGraphObjectWithId:(id)anId graphObject:(id)object;
+ (id)requestForUpdateOpenGraphObjectWithId:(id)anId title:(id)title image:(id)image url:(id)url description:(id)description objectProperties:(id)properties;
+ (id)requestForUploadPhoto:(id)uploadPhoto;
+ (id)requestForUploadStagingResourceWithImage:(id)image;
+ (id)requestWithGraphPath:(id)graphPath parameters:(id)parameters HTTPMethod:(id)method;
+ (id)serializeURL:(id)url params:(id)params;
+ (id)serializeURL:(id)url params:(id)params httpMethod:(id)method;
- (id)init;
- (id)initForPostWithSession:(id)session graphPath:(id)path graphObject:(id)object;
- (id)initWithSession:(id)session graphPath:(id)path;
- (id)initWithSession:(id)session graphPath:(id)path parameters:(id)parameters HTTPMethod:(id)method;
- (id)initWithSession:(id)session restMethod:(id)method parameters:(id)parameters HTTPMethod:(id)method4;
- (id)createRequestConnection;
- (void)dealloc;
- (id)description;
- (BOOL)loading;
- (void)overrideVersionPartWith:(id)with;
- (id)startWithCompletionHandler:(id)completionHandler;
@end

