/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface FBSessionTokenCachingStrategy : XXUnknownSuperclass {
	NSString* _accessTokenInformationKeyName;
}
+ (id)defaultInstance;
+ (BOOL)isValidTokenInformation:(id)information;
+ (id)nullCacheInstance;
- (id)init;
- (id)initWithUserDefaultTokenInformationKeyName:(id)userDefaultTokenInformationKeyName;
- (void)cacheFBAccessTokenData:(id)data;
- (void)cacheTokenInformation:(id)information;
- (void)clearToken;
- (void)dealloc;
- (id)fetchFBAccessTokenData;
- (id)fetchTokenInformation;
@end

