/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"

@class NSString;

@protocol FBSessionLoginStrategy <NSObject>
@property(readonly, copy) NSString* methodName;
- (BOOL)tryPerformAuthorizeWithParams:(id)params session:(id)session logger:(id)logger;
@end

