/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class ACAccountStore, ACAccountType;

@interface FBSystemAccountStoreAdapter : XXUnknownSuperclass {
	BOOL _forceBlockingRenew;
	ACAccountStore* _accountStore;
	ACAccountType* _accountTypeFB;
}
@property(readonly, retain, nonatomic) ACAccountStore* accountStore;
@property(readonly, retain, nonatomic) ACAccountType* accountTypeFB;
@property(readonly, assign) BOOL canRequestAccessWithoutUI;
@property(assign) BOOL forceBlockingRenew;
+ (void)setSharedInstance:(id)instance;
+ (id)sharedInstance;
- (id)init;
- (void)dealloc;
- (void)renewSystemAuthorization:(id)authorization;
- (id)renewSystemAuthorizationAsTask;
- (void)requestAccessToFacebookAccountStore:(id)facebookAccountStore defaultAudience:(int)audience isReauthorize:(BOOL)reauthorize appID:(id)anId session:(id)session handler:(id)handler;
- (id)requestAccessToFacebookAccountStoreAsTask:(id)facebookAccountStoreAsTask;
@end

