/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class FBSession, NSString, NSHashTable;

@interface FBViewImpressionTracker : XXUnknownSuperclass {
	NSHashTable* _trackedImpressions;
	NSString* _eventName;
	FBSession* _session;
}
@property(readonly, copy, nonatomic) NSString* eventName;
@property(retain, nonatomic) FBSession* session;
+ (id)impressionTrackerWithEventName:(id)eventName;
- (id)initWithEventName:(id)eventName;
- (void)_applicationDidEnterBackgroundNotification:(id)_application;
- (void)dealloc;
- (void)logImpressionWithView:(id)view identifier:(id)identifier parameters:(id)parameters;
@end

