/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ChineseSkillNew-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSMutableArray;

@interface FMDatabasePool : XXUnknownSuperclass {
	NSString* _path;
	dispatch_queue_s* _lockQueue;
	NSMutableArray* _databaseInPool;
	NSMutableArray* _databaseOutPool;
	id _delegate;
	unsigned _maximumNumberOfDatabasesToCreate;
	int _openFlags;
}
@property(assign) id delegate;
@property(assign) unsigned maximumNumberOfDatabasesToCreate;
@property(readonly, assign) int openFlags;
@property(retain) NSString* path;
+ (id)databasePoolWithPath:(id)path;
+ (id)databasePoolWithPath:(id)path flags:(int)flags;
- (id)init;
- (id)initWithPath:(id)path;
- (id)initWithPath:(id)path flags:(int)flags;
- (void).cxx_destruct;
- (void)beginTransaction:(BOOL)transaction withBlock:(id)block;
- (unsigned)countOfCheckedInDatabases;
- (unsigned)countOfCheckedOutDatabases;
- (unsigned)countOfOpenDatabases;
- (id)db;
- (void)dealloc;
- (void)executeLocked:(id)locked;
- (void)inDatabase:(id)database;
- (void)inDeferredTransaction:(id)deferredTransaction;
- (id)inSavePoint:(id)savePoint;
- (void)inTransaction:(id)transaction;
- (void)pushDatabaseBackInPool:(id)pool;
- (void)releaseAllDatabases;
@end

