/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ChineseSkillNew-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIViewController, FPTouchView, UIView, UIWindow, FPPopoverView;
@protocol FPPopoverControllerDelegate;

__attribute__((visibility("hidden")))
@interface FPPopoverController : XXUnknownSuperclass {
	UIView* _parentView;
	FPTouchView* _touchView;
	FPPopoverView* _contentView;
	UIViewController* _viewController;
	UIWindow* _window;
	UIView* _fromView;
	int _deviceOrientation;
	BOOL _shadowsHidden;
	CGColorRef _shadowColor;
	BOOL _border;
	BOOL _backgroundOpaque;
	id<FPPopoverControllerDelegate> _delegate;
	unsigned _arrowDirection;
	int _tint;
	float _alpha;
	CGSize _contentSize;
	CGPoint _origin;
}
@property(assign, nonatomic) float alpha;
@property(assign, nonatomic) unsigned arrowDirection;
@property(assign, nonatomic, getter=isOpaque) BOOL backgroundOpaque;
@property(assign, nonatomic) BOOL border;
@property(assign, nonatomic) CGSize contentSize;
@property(readonly, assign, nonatomic) FPPopoverView* contentView;
@property(assign, nonatomic) __weak id<FPPopoverControllerDelegate> delegate;
@property(assign, nonatomic) CGPoint origin;
@property(assign, nonatomic) int tint;
@property(readonly, assign, nonatomic) FPTouchView* touchView;
- (id)initWithViewController:(id)viewController;
- (id)initWithViewController:(id)viewController delegate:(id)delegate;
- (void).cxx_destruct;
- (void)addObservers;
- (CGRect)bestArrowDirectionAndFrameFromView:(id)view;
- (void)dealloc;
- (void)deviceOrientationDidChange:(id)deviceOrientation;
- (void)dismissPopover;
- (void)dismissPopoverAnimated:(BOOL)animated;
- (void)dismissPopoverAnimated:(BOOL)animated completion:(id)completion;
- (void)observeValueForKeyPath:(id)keyPath ofObject:(id)object change:(id)change context:(void*)context;
- (CGPoint)originFromView:(id)view;
- (float)parentHeight;
- (float)parentWidth;
- (void)presentPopoverFromPoint:(CGPoint)point;
- (void)presentPopoverFromPoint:(CGPoint)point inView:(id)view;
- (void)presentPopoverFromView:(id)view;
- (void)presentPopoverFromView:(id)view inView:(id)view2;
- (void)removeObservers;
- (void)setShadowsHidden:(BOOL)hidden;
- (void)setupView;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
- (void)viewDidLoad;
- (void)willPresentNewPopover:(id)popover;
@end

