/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ChineseSkillNew-Structs.h"
#import "NSObject.h"


@protocol iCarouselDelegate <NSObject>
@optional
- (void)carousel:(id)carousel didSelectItemAtIndex:(int)index;
- (CATransform3D)carousel:(id)carousel itemTransformForOffset:(float)offset baseTransform:(CATransform3D)transform;
- (BOOL)carousel:(id)carousel shouldSelectItemAtIndex:(int)index;
- (float)carousel:(id)carousel valueForOption:(int)option withDefault:(float)aDefault;
- (void)carouselCurrentItemIndexDidChange:(id)carouselCurrentItemIndex;
- (void)carouselDidEndDecelerating:(id)carousel;
- (void)carouselDidEndDragging:(id)carousel willDecelerate:(BOOL)decelerate;
- (void)carouselDidEndScrollingAnimation:(id)carousel;
- (void)carouselDidScroll:(id)carousel;
- (float)carouselItemWidth:(id)width;
- (void)carouselWillBeginDecelerating:(id)carousel;
- (void)carouselWillBeginDragging:(id)carousel;
- (void)carouselWillBeginScrollingAnimation:(id)carousel;
@end

