/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ChineseSkillNew-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UILabel, UIImageView;
@protocol NSObject;

__attribute__((visibility("hidden")))
@interface iPhone5LingoImageCheckBoxView : XXUnknownSuperclass {
	BOOL _checked;
	id<NSObject> _delegate;
	UIImageView* _checkBoxImageView;
	UIImageView* _mainImageView;
	UILabel* _textLabel;
	SEL _stateChangedSelector;
	int _style;
	int _nModelWordOrSentenceType;
	int _nModelWordOrSentenceId;
	int _nModelId;
}
@property(retain, nonatomic) UIImageView* checkBoxImageView;
@property(assign) BOOL checked;
@property(retain, nonatomic) id<NSObject> delegate;
@property(retain, nonatomic) UIImageView* mainImageView;
@property(assign) int nModelId;
@property(assign) int nModelWordOrSentenceId;
@property(assign) int nModelWordOrSentenceType;
@property(assign) SEL stateChangedSelector;
@property(assign) int style;
@property(retain, nonatomic) UILabel* textLabel;
- (id)initWithFrame:(CGRect)frame style:(int)style checked:(BOOL)checked;
- (void).cxx_destruct;
- (void)UpdateMainImageView:(id)view;
- (BOOL)canBecomeFirstResponder;
- (id)checkBoxImageForStyle:(int)style checked:(BOOL)checked;
- (void)dealloc;
- (void)setIsChecked:(BOOL)checked;
- (void)setStateChangedTarget:(id)target selector:(SEL)selector;
- (void)setText:(id)text;
- (void)touchesBegan:(id)began withEvent:(id)event;
- (void)touchesCancelled:(id)cancelled withEvent:(id)event;
- (void)touchesEnded:(id)ended withEvent:(id)event;
- (void)updateCheckBoxImage;
@end

