/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray, NSString, Model_db_survival_category;

__attribute__((visibility("hidden")))
@interface iPhoneSurvivalDetailsModel : XXUnknownSuperclass {
	BOOL _opened;
	NSString* _name;
	int _groupCount;
	Model_db_survival_category* _model_survival_ctg;
	NSArray* _itemArray;
}
@property(assign, nonatomic) int groupCount;
@property(retain, nonatomic) NSArray* itemArray;
@property(retain, nonatomic) Model_db_survival_category* model_survival_ctg;
@property(copy, nonatomic) NSString* name;
@property(assign, nonatomic, getter=isOpened) BOOL opened;
- (void).cxx_destruct;
@end

