/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ChineseSkillNew-Structs.h"
#import "UITextViewDelegate.h"
#import "CSAcountManagerDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "signupVCDelegate.h"

@class NSString, UIActivityIndicatorView, UITextField, NSURLConnection, NSMutableData, UIButton, NSTimer, UILabel;
@protocol userLoginVCDelegate;

__attribute__((visibility("hidden")))
@interface iPhone5UserLoginViewController : XXUnknownSuperclass <signupVCDelegate, CSAcountManagerDelegate, UITextViewDelegate> {
	UITextField* _EmailAddress;
	UITextField* _UserPassword;
	UIActivityIndicatorView* _activityView;
	UIButton* _loginButton;
	UIButton* _signupButton;
	UILabel* _RecommentLabel;
	NSURLConnection* _connection;
	NSMutableData* _feedXML;
	id<userLoginVCDelegate> _delegate;
	NSTimer* _timer;
	UIButton* _facebookLoginBtn;
	UIButton* _twitterLoginBtn;
	UIButton* _backBtn;
}
@property(assign, nonatomic) __weak UITextField* EmailAddress;
@property(assign, nonatomic) __weak UILabel* RecommentLabel;
@property(assign, nonatomic) __weak UITextField* UserPassword;
@property(assign, nonatomic) __weak UIActivityIndicatorView* activityView;
@property(assign, nonatomic) __weak UIButton* backBtn;
@property(retain, nonatomic) NSURLConnection* connection;
@property(readonly, copy) NSString* debugDescription;
@property(assign, nonatomic) __weak id<userLoginVCDelegate> delegate;
@property(readonly, copy) NSString* description;
@property(assign, nonatomic) __weak UIButton* facebookLoginBtn;
@property(retain, nonatomic) NSMutableData* feedXML;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) __weak UIButton* loginButton;
@property(assign, nonatomic) __weak UIButton* signupButton;
@property(readonly, assign) Class superclass;
@property(retain, nonatomic) NSTimer* timer;
@property(assign, nonatomic) __weak UIButton* twitterLoginBtn;
- (id)initWithNibName:(id)nibName bundle:(id)bundle;
- (void).cxx_destruct;
- (void)BackButtonClick:(id)click;
- (void)LoginClick;
- (void)PopupViewWithDely;
- (void)closeBtn:(id)btn;
- (void)didReceiveMemoryWarning;
- (void)dismissSelf;
- (void)facebookLoginBtnClicked:(id)clicked;
- (void)finishLoading;
- (void)forgotPassword:(id)password;
- (BOOL)isStringContainSubstring:(id)substring SUBSTRING:(id)substring2;
- (void)loginError:(id)error;
- (void)loginSuccess:(id)success;
- (void)signupBtnClick:(id)click;
- (void)signupSuccess;
- (void)twitterLoginBtnClicked:(id)clicked;
- (void)viewDidLoad;
- (void)viewDidUnload;
- (void)viewWillAppear:(BOOL)view;
- (void)viewWillDisappear:(BOOL)view;
@end

