/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "FPPopoverControllerDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "AVAudioPlayerDelegate.h"
#import "AVAudioRecorderDelegate.h"

@class Model_Pinyin, UIButton, NSMutableArray, NSURL, NSTimer, NSString, AVAudioPlayer, AVAudioRecorder, UIActivityIndicatorView;
@protocol myDelegate;

__attribute__((visibility("hidden")))
@interface iPhonePlusPinyinPoperViewController : XXUnknownSuperclass <FPPopoverControllerDelegate, AVAudioRecorderDelegate, AVAudioPlayerDelegate> {
	bool _isRecording;
	bool _isNewRecordSound;
	bool _hasRecord;
	id<myDelegate> _delegate;
	UIButton* _m_pinyinButton;
	UIButton* _nextButton;
	UIButton* _prevButton;
	UIButton* _recordUserButton;
	UIActivityIndicatorView* _activityIndicatorView;
	NSTimer* _dLtimer;
	Model_Pinyin* _m_data;
	NSMutableArray* _allList;
	AVAudioRecorder* _m_recorder;
	AVAudioPlayer* _m_avPlayer;
	NSURL* _m_CSLPODAudioPath;
	NSURL* _m_RecordAuidoPath;
	NSTimer* _timer;
	int _recordEncoding;
	int _AuidoPlayStatus;
	int _nCurIndex;
}
@property(assign) int AuidoPlayStatus;
@property(assign, nonatomic) __weak UIActivityIndicatorView* activityIndicatorView;
@property(retain, nonatomic) NSMutableArray* allList;
@property(retain, nonatomic) NSTimer* dLtimer;
@property(readonly, copy) NSString* debugDescription;
@property(retain, nonatomic) id<myDelegate> delegate;
@property(readonly, copy) NSString* description;
@property(assign) bool hasRecord;
@property(readonly, assign) unsigned hash;
@property(assign) bool isNewRecordSound;
@property(assign) bool isRecording;
@property(retain, nonatomic) NSURL* m_CSLPODAudioPath;
@property(retain, nonatomic) NSURL* m_RecordAuidoPath;
@property(retain, nonatomic) AVAudioPlayer* m_avPlayer;
@property(retain, nonatomic) Model_Pinyin* m_data;
@property(assign, nonatomic) __weak UIButton* m_pinyinButton;
@property(retain, nonatomic) AVAudioRecorder* m_recorder;
@property(assign) int nCurIndex;
@property(assign, nonatomic) __weak UIButton* nextButton;
@property(assign, nonatomic) __weak UIButton* prevButton;
@property(assign) int recordEncoding;
@property(assign, nonatomic) __weak UIButton* recordUserButton;
@property(readonly, assign) Class superclass;
@property(retain, nonatomic) NSTimer* timer;
- (id)initWithNibName:(id)nibName bundle:(id)bundle;
- (void).cxx_destruct;
- (void)BeginPlayCSLPODAuido;
- (void)BeginPlayRecordAudio;
- (void)CheckAudioAvaliable:(id)avaliable;
- (void)InitModelData:(id)data;
- (void)InitRecordUserSoundData;
- (BOOL)IsFileExist:(id)exist;
- (void)LeavePageActionCalled;
- (void)NextButtonClick:(id)click;
- (void)PlayPinyin:(id)pinyin;
- (void)PrevButtonClick:(id)click;
- (void)ReleaseDelegateReference;
- (void)Repeat_CheckPinyinAvaliable;
- (void)SetupRecorder;
- (void)StopAnyAudioPlayer;
- (void)audioPlayerDidFinishPlaying:(id)audioPlayer successfully:(BOOL)successfully;
- (void)detectionVoice;
- (void)didReceiveMemoryWarning;
- (void)recordButtonDragUp:(id)up;
- (void)recordButtonUp:(id)up;
- (void)updateImage;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)view;
- (void)viewWillDisappear:(BOOL)view;
@end

