/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "iPhone4DataModelViewController.h"

@class NSTimer, UILabel, CSLessonResultModel, UIView, NSMutableArray;

__attribute__((visibility("hidden")))
@interface iPhone4LessonPassViewController : iPhone4DataModelViewController {
	BOOL _isNetWorkOk;
	UILabel* _passLabel;
	UIView* _defeatPercentView;
	UILabel* _timeLabel;
	UILabel* _rightCountLabel;
	UILabel* _errorCountLabel;
	UILabel* _scoreLabel;
	UILabel* _congratulationsLabel;
	UILabel* _centerPercentLabel;
	UILabel* _rightPointLabel;
	UILabel* _wrongPointLabel;
	UILabel* _accuracyPointLabel;
	UILabel* _accuracyLabel;
	NSMutableArray* _circleSubViewArray;
	int _nLessonId;
	int _nmypoints;
	CSLessonResultModel* _lessonResultModel;
	int _nCurRunTimes;
	float _totalPercent;
	NSTimer* _runingTimer;
}
@property(assign, nonatomic) __weak UILabel* accuracyLabel;
@property(assign, nonatomic) __weak UILabel* accuracyPointLabel;
@property(assign, nonatomic) __weak UILabel* centerPercentLabel;
@property(retain, nonatomic) NSMutableArray* circleSubViewArray;
@property(assign, nonatomic) __weak UILabel* congratulationsLabel;
@property(assign, nonatomic) __weak UIView* defeatPercentView;
@property(assign, nonatomic) __weak UILabel* errorCountLabel;
@property(assign) BOOL isNetWorkOk;
@property(retain, nonatomic) CSLessonResultModel* lessonResultModel;
@property(assign, nonatomic) int nCurRunTimes;
@property(assign) int nLessonId;
@property(assign) int nmypoints;
@property(assign, nonatomic) __weak UILabel* passLabel;
@property(assign, nonatomic) __weak UILabel* rightCountLabel;
@property(assign, nonatomic) __weak UILabel* rightPointLabel;
@property(retain, nonatomic) NSTimer* runingTimer;
@property(assign, nonatomic) __weak UILabel* scoreLabel;
@property(assign, nonatomic) __weak UILabel* timeLabel;
@property(assign, nonatomic) float totalPercent;
@property(assign, nonatomic) __weak UILabel* wrongPointLabel;
- (id)initWithNibName:(id)nibName bundle:(id)bundle;
- (void).cxx_destruct;
- (void)DrawRuningPercent;
- (id)ExChangeTimeToString:(int)string;
- (void)InitCircleSubView;
- (void)UpdateInforLabel;
- (void)animationDidStop:(id)animation finished:(BOOL)finished;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)view;
- (void)viewWillDisappear:(BOOL)view;
@end

