/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SKPaymentTransactionObserver.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, iPhone5UserSubscribeViewController;

__attribute__((visibility("hidden")))
@interface iPhone5MyStoreObserver : XXUnknownSuperclass <SKPaymentTransactionObserver> {
	iPhone5UserSubscribeViewController* _subscribeUI;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) iPhone5UserSubscribeViewController* subscribeUI;
@property(readonly, assign) Class superclass;
+ (id)sharedOperator;
- (id)init;
- (void).cxx_destruct;
- (BOOL)ProcessPurchaseRestore:(id)restore;
- (void)RecordiPadUserBuyToCSLPOD:(id)cslpod;
- (void)RestoreButtonClick;
- (void)Start;
- (void)completeTransaction:(id)transaction TYPE:(id)type;
- (void)dealloc;
- (void)failedTransaction:(id)transaction TYPE:(id)type;
- (void)paymentQueue:(id)queue restoreCompletedTransactionsFailedWithError:(id)error;
- (void)paymentQueue:(id)queue updatedTransactions:(id)transactions;
- (void)paymentQueueRestoreCompletedTransactionsFinished:(id)finished;
- (void)restoreTransaction:(id)transaction TYPE:(id)type;
- (BOOL)validatePaymentTransactionReceiptForiOS7:(id)a7;
@end

