/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSTimer, UILabel, UIDatePicker, UIButton, UIView;

__attribute__((visibility("hidden")))
@interface iPhone5RemindMeViewController : XXUnknownSuperclass {
	UILabel* _titleLabel;
	UIButton* _SundayBtn;
	UIButton* _MondayBtn;
	UIButton* _TuesdayBtn;
	UIButton* _WednesdayBtn;
	UIButton* _ThursdayBtn;
	UIButton* _FridayBtn;
	UIButton* _SaturdayBtn;
	UIButton* _timeClock;
	UIView* _datePickerViewBG;
	UIDatePicker* _datePicker;
	NSTimer* _timer;
	UIButton* _cancelBtn;
}
@property(assign, nonatomic) __weak UIButton* FridayBtn;
@property(assign, nonatomic) __weak UIButton* MondayBtn;
@property(assign, nonatomic) __weak UIButton* SaturdayBtn;
@property(assign, nonatomic) __weak UIButton* SundayBtn;
@property(assign, nonatomic) __weak UIButton* ThursdayBtn;
@property(assign, nonatomic) __weak UIButton* TuesdayBtn;
@property(assign, nonatomic) __weak UIButton* WednesdayBtn;
@property(assign, nonatomic) __weak UIButton* cancelBtn;
@property(assign, nonatomic) __weak UIDatePicker* datePicker;
@property(assign, nonatomic) __weak UIView* datePickerViewBG;
@property(assign, nonatomic) __weak UIButton* timeClock;
@property(retain, nonatomic) NSTimer* timer;
@property(assign, nonatomic) __weak UILabel* titleLabel;
- (void).cxx_destruct;
- (void)FridayBtnClicked;
- (void)MondayBtnClicked;
- (void)SaturdayBtnClicked;
- (void)SundayBtnClicked;
- (void)ThursdayBtnClicked;
- (void)TuesdayBtnClicked;
- (void)WednesdayBtnClicked;
- (void)cancelBtnClicked:(id)clicked;
- (void)closeBtnClicked:(id)clicked;
- (void)didReceiveMemoryWarning;
- (void)setBtnStatus;
- (void)setupLocalizedString;
- (void)timeColckBtnClicked:(id)clicked;
- (void)touchesEnded:(id)ended withEvent:(id)event;
- (void)updateTimeBtn;
- (void)viewDidLoad;
- (void)viewWillDisappear:(BOOL)view;
@end

