/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DataModelViewController.h"


__attribute__((visibility("hidden")))
@interface LessonFailViewController : DataModelViewController {
}
- (id)initWithNibName:(id)nibName bundle:(id)bundle;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)view;
- (void)viewWillDisappear:(BOOL)view;
@end

