/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ChineseSkillNew-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class CAShapeLayer, UIColor;

__attribute__((visibility("hidden")))
@interface LSAudioPlayProgressView : XXUnknownSuperclass {
	UIColor* _progressTintColor;
	float _progress;
	float _lineWidth;
	CAShapeLayer* _arcLayer;
}
@property(retain, nonatomic) CAShapeLayer* arcLayer;
@property(assign, nonatomic) float lineWidth;
@property(assign, nonatomic) float progress;
@property(retain, nonatomic) UIColor* progressTintColor;
- (id)init;
- (id)initWithCoder:(id)coder;
- (id)initWithFrame:(CGRect)frame;
- (void).cxx_destruct;
- (void)drawLineAnimation:(id)animation Duration:(double)duration;
- (void)pauseAnimation;
- (void)pauseLayer:(id)layer;
- (void)resumeAnimation;
- (void)resumeLayer:(id)layer;
- (void)setProgress:(float)progress animated:(BOOL)animated WithDuration:(double)duration audioPlayBtn:(id)btn;
- (void)stopAnimation;
@end

