/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "UIPopoverControllerDelegate.h"
#import "myDelegate.h"
#import "UIActionSheetDelegate.h"

@class UIButton, NSTimer, UILabel, NSString, UIImageView, DetailViewController, UIView;

__attribute__((visibility("hidden")))
@interface MasterViewController : XXUnknownSuperclass <UIPopoverControllerDelegate, UIActionSheetDelegate, myDelegate> {
	DetailViewController* _detailViewController;
	UILabel* _PointTitleLabel;
	UIButton* _StrengthenSkillButton;
	UIButton* _ChooseLanguageButton;
	UIButton* _FindUsButton;
	UIButton* _PinyinExerciseButton;
	UIButton* _StrengthenCharacterButton;
	UIButton* _StrengthenWordButton;
	UIButton* _StrengthenSentenceButton;
	UILabel* _PinyinPracticeLabel;
	UILabel* _CharacterPracticeLabel;
	UILabel* _WordPracticeLabel;
	UILabel* _SentencePracticeLabel;
	UIImageView* _LogoImageView;
	UILabel* _LogoLabel;
	UIButton* _WordValueButton;
	UIButton* _WordLabeleButton;
	UIButton* _WordIconButton;
	UIButton* _SentenceValueButton;
	UIButton* _SentenceLabelButton;
	UIButton* _SentenceIconButton;
	UIButton* _CharacterValueButton;
	UIButton* _CharacterLabeleButton;
	UIButton* _CharacterIconButton;
	UIButton* _SettingButton;
	UIView* _sharedView;
	UILabel* _AchievementLabel;
	UILabel* _CompetitionLabel;
	UIButton* _ShareLingoButton;
	UIView* _subtitleBGView;
	UILabel* _subtitleLabel;
	UILabel* _subtitleTransLabel;
	UILabel* _indexLabel;
	UIButton* _charPlayButton;
	UIButton* _wordPlayButton;
	UIButton* _sentPlayButton;
	NSTimer* _timerCheckAvailable;
	int _whichButtonClick;
}
@property(assign, nonatomic) __weak UILabel* AchievementLabel;
@property(assign, nonatomic) __weak UIButton* CharacterIconButton;
@property(assign, nonatomic) __weak UIButton* CharacterLabeleButton;
@property(assign, nonatomic) __weak UILabel* CharacterPracticeLabel;
@property(assign, nonatomic) __weak UIButton* CharacterValueButton;
@property(assign, nonatomic) __weak UIButton* ChooseLanguageButton;
@property(assign, nonatomic) __weak UILabel* CompetitionLabel;
@property(assign, nonatomic) __weak UIButton* FindUsButton;
@property(assign, nonatomic) __weak UIImageView* LogoImageView;
@property(assign, nonatomic) __weak UILabel* LogoLabel;
@property(assign, nonatomic) __weak UIButton* PinyinExerciseButton;
@property(assign, nonatomic) __weak UILabel* PinyinPracticeLabel;
@property(assign, nonatomic) __weak UILabel* PointTitleLabel;
@property(assign, nonatomic) __weak UIButton* SentenceIconButton;
@property(assign, nonatomic) __weak UIButton* SentenceLabelButton;
@property(assign, nonatomic) __weak UILabel* SentencePracticeLabel;
@property(assign, nonatomic) __weak UIButton* SentenceValueButton;
@property(assign, nonatomic) __weak UIButton* SettingButton;
@property(assign, nonatomic) __weak UIButton* ShareLingoButton;
@property(assign, nonatomic) __weak UIButton* StrengthenCharacterButton;
@property(assign, nonatomic) __weak UIButton* StrengthenSentenceButton;
@property(assign, nonatomic) __weak UIButton* StrengthenSkillButton;
@property(assign, nonatomic) __weak UIButton* StrengthenWordButton;
@property(assign, nonatomic) __weak UIButton* WordIconButton;
@property(assign, nonatomic) __weak UIButton* WordLabeleButton;
@property(assign, nonatomic) __weak UILabel* WordPracticeLabel;
@property(assign, nonatomic) __weak UIButton* WordValueButton;
@property(assign, nonatomic) __weak UIButton* charPlayButton;
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(retain, nonatomic) DetailViewController* detailViewController;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) __weak UILabel* indexLabel;
@property(assign, nonatomic) __weak UIButton* sentPlayButton;
@property(assign, nonatomic) __weak UIView* sharedView;
@property(assign, nonatomic) __weak UIView* subtitleBGView;
@property(assign, nonatomic) __weak UILabel* subtitleLabel;
@property(assign, nonatomic) __weak UILabel* subtitleTransLabel;
@property(readonly, assign) Class superclass;
@property(retain, nonatomic) NSTimer* timerCheckAvailable;
@property(assign) int whichButtonClick;
@property(assign, nonatomic) __weak UIButton* wordPlayButton;
- (void).cxx_destruct;
- (void)CheckNeedUpdate;
- (void)ContactUsOnFacebookClick:(id)click;
- (void)InitUserData;
- (void)PinyinExerciseButtonClick:(id)click;
- (void)PlayListAudiosByType:(int)type;
- (void)PopupImportView:(id)view;
- (void)PopupMyCharacterView:(id)view;
- (void)PopupMySentenceView:(id)view;
- (void)PopupMyWordView:(id)view;
- (void)PopupSettingView:(id)view;
- (void)PopupTellAFriend:(id)aFriend;
- (void)PopupTellAFriendWithDely;
- (void)RefleshViewUI;
- (void)ResetAllPlayer;
- (void)ShareLingoButtonClick:(id)click;
- (void)StrengthenCharacterButtonClick:(id)click;
- (void)StrengthenSentenceButtonClick:(id)click;
- (void)StrengthenWordButtonClick:(id)click;
- (void)UpdateTimeToDisplay;
- (void)UpdateTimeToDisplayDone;
- (void)actionSheet:(id)sheet clickedButtonAtIndex:(int)index;
- (void)awakeFromNib;
- (void)charPlayButtonClick:(id)click;
- (void)checkAndUpdateFromAWS;
- (void)didReceiveMemoryWarning;
- (void)observeValueForKeyPath:(id)keyPath ofObject:(id)object change:(id)change context:(void*)context;
- (void)prepareForSegue:(id)segue sender:(id)sender;
- (void)sentPlayButtonClick:(id)click;
- (void)viewDidAppear:(BOOL)view;
- (void)viewDidLoad;
- (void)viewDidUnload;
- (void)viewWillAppear:(BOOL)view;
- (void)viewWillDisappear:(BOOL)view;
- (void)wordPlayButtonClick:(id)click;
@end

