/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MCSMGenericKeychainItem.h"

@class NSString;

@interface MCSMApplicationUUIDKeychainItem : MCSMGenericKeychainItem {
}
@property(readonly, copy) NSString* UUID;
+ (id)applicationUUID;
+ (id)applicationUUIDKeychainItem;
+ (id)generateApplicationUUIDKeychainItem;
- (id)description;
@end

