/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol MJRefreshBaseViewDelegate <NSObject>
@optional
- (void)refreshView:(id)view stateChange:(int)change;
- (void)refreshViewBeginRefreshing:(id)refreshing;
- (void)refreshViewEndRefreshing:(id)refreshing;
@end

