/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ChineseSkillNew-Structs.h"
#import "MJRefreshBaseView.h"


__attribute__((visibility("hidden")))
@interface MJRefreshFooterView : MJRefreshBaseView {
	int _lastRefreshCount;
}
+ (id)footer;
- (id)initWithFrame:(CGRect)frame;
- (void)adjustFrame;
- (float)contentBreakView;
- (void)free;
- (void)observeValueForKeyPath:(id)keyPath ofObject:(id)object change:(id)change context:(void*)context;
- (void)setFrame:(CGRect)frame;
- (void)setScrollView:(id)view;
- (void)setState:(int)state;
- (float)validY;
- (int)viewType;
@end

