/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary, NSString;

@interface MobClickGameAnalytics : XXUnknownSuperclass {
	NSString* _runningLevel;
	NSString* _lastLevel;
	NSMutableDictionary* _levels;
	double _levelBeginTime;
	NSString* _userLevel;
	NSMutableDictionary* _userInfo;
	double _lastLevelBeginTime;
}
@property(copy, nonatomic) NSString* lastLevel;
@property(assign, nonatomic) double lastLevelBeginTime;
@property(retain, nonatomic) NSMutableDictionary* levels;
@property(copy, nonatomic) NSString* runningLevel;
@property(retain, nonatomic) NSMutableDictionary* userInfo;
@property(copy, nonatomic) NSString* userLevel;
+ (void)bonus:(id)bonus amount:(int)amount price:(double)price source:(int)source;
+ (void)bonus:(double)bonus source:(int)source;
+ (void)buy:(id)buy amount:(int)amount price:(double)price;
+ (void)failLevel:(id)level;
+ (void)finishLevel:(id)level;
+ (void)pauseLevel:(id)level;
+ (void)pay:(double)pay source:(int)source coin:(double)coin;
+ (void)pay:(double)pay source:(int)source item:(id)item amount:(int)amount price:(double)price;
+ (void)resumeLevel:(id)level;
+ (void)setUserID:(id)anId sex:(int)sex age:(int)age platform:(id)platform;
+ (void)setUserLevel:(id)level;
+ (id)sharedInstance;
+ (void)startLevel:(id)level;
+ (void)use:(id)use amount:(int)amount price:(double)price;
+ (id)userInfo;
+ (BOOL)validLevel:(id)level;
- (id)init;
- (void)bonus:(id)bonus amount:(int)amount price:(double)price source:(int)source;
- (void)bonus:(double)bonus source:(int)source;
- (void)buy:(id)buy amount:(int)amount price:(double)price;
- (long)calculateLevelDuration:(id)duration;
- (void)clean;
- (void)cleanUpCurrentLevelTime:(id)time;
- (void)dealloc;
- (void)failLevel:(id)level;
- (void)finishLevel:(id)level;
- (void)levelFinish:(id)finish completed:(BOOL)completed;
- (void)pauseLevel:(id)level;
- (void)pay:(double)pay source:(int)source coin:(double)coin;
- (void)pay:(double)pay source:(int)source item:(id)item amount:(int)amount price:(double)price;
- (void)resumeLevel:(id)level;
- (void)setGameLevelIfNeeded:(id)needed;
- (void)setUserID:(id)anId sex:(int)sex age:(int)age platform:(id)platform;
- (void)setUserLevelIfNeeded:(id)needed;
- (void)startLevel:(id)level;
- (void)updateLevelDuration;
- (void)updateLevelDuration:(id)duration;
- (void)updateLevelTimestamp;
- (void)updateLevelTimestamp:(id)timestamp;
- (void)use:(id)use amount:(int)amount price:(double)price;
- (BOOL)validLevel:(id)level;
- (BOOL)validPay:(double)pay source:(int)source coin:(double)coin;
@end

