/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary, NSData, NSOperationQueue, NSString, NSDictionary, NSMutableArray;

@interface MobClickInternal : XXUnknownSuperclass {
	NSOperationQueue* _sendLogQueue;
	NSOperationQueue* _otherQueue;
	NSMutableArray* _launches;
	NSMutableArray* _terminates;
	NSMutableArray* _events;
	NSMutableArray* _errors;
	NSMutableArray* _ekv;
	NSMutableArray* _tmpContainer;
	NSMutableDictionary* _ekvBeginTimes;
	NSMutableDictionary* _eventBeginTimes;
	double lastLaunchTime;
	NSString* _lastSessionId;
	NSString* _json;
	NSData* _jsonDeflated;
	int policy;
	NSDictionary* _error_support_info;
	NSString* _sessionID;
	NSString* _wrapperType;
	NSString* _wrapperVersion;
	unsigned _backgroundTaskIdentifier;
	NSMutableDictionary* _envelope;
}
@property(retain) NSMutableArray* ekv;
@property(retain) NSMutableDictionary* ekvBeginTimes;
@property(retain, nonatomic) NSMutableDictionary* envelope;
@property(retain) NSDictionary* error_support_info;
@property(retain) NSMutableArray* errors;
@property(retain) NSMutableDictionary* eventBeginTimes;
@property(retain) NSMutableArray* events;
@property(copy, nonatomic) NSString* json;
@property(retain, nonatomic) NSData* jsonDeflated;
@property(assign) double lastLaunchTime;
@property(copy) NSString* lastSessionId;
@property(retain) NSMutableArray* launches;
@property(retain, nonatomic) NSOperationQueue* otherQueue;
@property(assign, nonatomic) int policy;
@property(retain, nonatomic) NSOperationQueue* sendLogQueue;
@property(copy, nonatomic) NSString* sessionID;
@property(retain) NSMutableArray* terminates;
@property(retain) NSMutableArray* tmpContainer;
@property(copy, nonatomic) NSString* wrapperType;
@property(copy, nonatomic) NSString* wrapperVersion;
+ (void)error:(id)error;
+ (id)sharedInstance;
+ (void)updateErrorSupportInfo:(id)info;
- (id)init;
- (void)_saveAndClean:(id)clean;
- (void)_saveCacheFile;
- (void)archiveObjects:(id)objects;
- (id)archiveObjectsWithHeader:(BOOL)header;
- (void)beginPerformJob;
- (id)buildEkv;
- (id)buildGkv;
- (void)clearData;
- (void)commitJob;
- (void)dealloc;
- (id)description;
- (void)fillCacheData:(id)data;
- (BOOL)hasJob;
- (id)header;
- (void)incrementRequest:(BOOL)request usedTime:(int)time;
- (void)incrementRequestNumber:(BOOL)number;
- (void)loadCache;
- (id)loadCacheFile;
- (void)logLastRequestTime:(int)time;
- (void)markJobDone;
- (void)removeEnvelopeData;
- (void)removeInstanceData;
- (void)removeJSONData;
- (void)removeMarkedRecords;
- (void)removeMatchedRecords:(id)records;
- (void)removeSentData;
- (void)saveCacheAndClean:(id)clean;
- (void)saveCacheFile;
- (void)setLastPostDate;
- (id)setupPostData;
- (void)unarchiveErrors:(id)errors;
- (void)unarchiveEvents:(id)events;
- (void)unarchiveObjects:(id)objects;
- (void)unarchiveSessions:(id)sessions;
- (void)updateJson;
- (void)updateSerialNum:(int)num;
@end

