/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, UMEnvelope, NSData;

@interface MobClickEnvelope : XXUnknownSuperclass {
	NSData* _identityMD5;
	char* _entityMD5;
	NSString* _signatureString;
	NSString* _guidString;
	NSString* _checksum;
	int _timestamp;
	NSString* _version;
	NSString* _address;
	int _serialNum;
	int _length;
	UMEnvelope* _enveloper;
	NSData* _signature;
	NSData* _guid;
	NSData* _envelopeData;
}
@property(copy, nonatomic) NSString* address;
@property(copy, nonatomic) NSString* checksum;
@property(assign, nonatomic) char* entityMD5;
@property(retain, nonatomic) NSData* envelopeData;
@property(retain, nonatomic) NSData* guid;
@property(retain, nonatomic) NSData* identityMD5;
@property(assign, nonatomic) int length;
@property(assign, nonatomic) int serialNum;
@property(retain, nonatomic) NSData* signature;
@property(assign, nonatomic) int timestamp;
@property(copy, nonatomic) NSString* version;
+ (id)sharedInstance;
- (id)init;
- (void)buildGUIDWithSignature:(unsigned char [32])signature;
- (void)buildIdentity;
- (void)buildSerialNum;
- (void)dealloc;
- (id)description;
- (id)envelopeFile;
- (void)fetchSignature;
- (void)generateChecksum;
- (id)loadEnvelopeData;
- (id)mergeEntityAndIdentity;
- (void)printBytes:(char*)bytes length:(int)length;
- (void)saveEnvelopeFile;
- (id)toDataWithEntity:(id)entity;
- (BOOL)verifyChecksum;
- (BOOL)verifyTimestamp;
@end

