/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIAlertViewDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface MobClick : XXUnknownSuperclass <UIAlertViewDelegate> {
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) unsigned hash;
@property(readonly, assign) Class superclass;
+ (void)beginEvent:(id)event;
+ (void)beginEvent:(id)event label:(id)label;
+ (void)beginEvent:(id)event primarykey:(id)primarykey attributes:(id)attributes;
+ (void)beginLogPageView:(id)view;
+ (void)checkUpdate;
+ (void)checkUpdate:(id)update cancelButtonTitle:(id)title otherButtonTitles:(id)titles;
+ (void)checkUpdateWithDelegate:(id)delegate selector:(SEL)selector;
+ (void)endEvent:(id)event;
+ (void)endEvent:(id)event label:(id)label;
+ (void)endEvent:(id)event primarykey:(id)primarykey;
+ (void)endLogPageView:(id)view;
+ (void)event:(id)event;
+ (void)event:(id)event acc:(int)acc;
+ (void)event:(id)event attributes:(id)attributes;
+ (void)event:(id)event attributes:(id)attributes counter:(int)counter;
+ (void)event:(id)event attributes:(id)attributes durations:(int)durations;
+ (void)event:(id)event durations:(int)durations;
+ (void)event:(id)event label:(id)label;
+ (void)event:(id)event label:(id)label acc:(int)acc;
+ (void)event:(id)event label:(id)label durations:(int)durations;
+ (id)getAdURL;
+ (id)getConfigParams;
+ (id)getConfigParams:(id)params;
+ (BOOL)isJailbroken;
+ (BOOL)isPirated;
+ (void)logPageView:(id)view seconds:(int)seconds;
+ (void)setAppVersion:(id)version;
+ (void)setCrashReportEnabled:(BOOL)enabled;
+ (void)setLatitude:(double)latitude longitude:(double)longitude;
+ (void)setLocation:(id)location;
+ (void)setLogEnabled:(BOOL)enabled;
+ (void)setLogSendInterval:(double)interval;
+ (void)setWrapperType:(id)type;
+ (void)setWrapperType:(id)type wrapperVersion:(id)version;
+ (void)setWrapperVersion:(id)version;
+ (void)startSession:(id)session;
+ (void)startWithAppkey:(id)appkey;
+ (void)startWithAppkey:(id)appkey reportPolicy:(int)policy channelId:(id)anId;
+ (void)updateOnlineConfig;
@end

