/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UMTIdTracking, UMTActivateMsg, UMTAppInfo, UMTUALogEntry, UMTDeviceInfo, UMTClientStats, NSMutableArray, UMTMiscInfo;

@interface MobClickThrift : XXUnknownSuperclass {
	UMTUALogEntry* _UALogEntry;
	UMTDeviceInfo* _deviceInfo;
	UMTAppInfo* _appInfo;
	UMTMiscInfo* _miscInfo;
	UMTIdTracking* _idTracking;
	UMTActivateMsg* _activateMsg;
	UMTClientStats* _clientStats;
	NSMutableArray* _sessions;
	NSMutableArray* _instantMessages;
}
+ (id)generateImprintChecksum:(id)checksum;
+ (id)sharedInstance;
+ (BOOL)validateImprintChecksum:(id)checksum;
- (id)init;
- (void)buildActivateMsg;
- (void)buildAppInfo;
- (void)buildClientStats;
- (void)buildDeviceInfo;
- (void)buildIdTracking;
- (void)buildImprint;
- (void)buildInstantMessageFromEkv:(id)ekv;
- (void)buildInstantMessageFromError:(id)error;
- (void)buildInstantMessageFromEvent:(id)event;
- (void)buildInstantMessages;
- (void)buildLogEntry;
- (void)buildMiscInfo;
- (void)buildSessionFrom:(id)from;
- (void)buildSessions;
- (void)buildSessionsAndInstantMessages;
- (void)buildSessionsFromMobClickInternal;
- (void)dealloc;
- (id)description;
- (id)entityData;
- (id)fromData:(id)data;
- (BOOL)isResponseOK:(id)ok;
- (void)markLaunchFrom:(id)from;
- (void)saveIdTracking;
- (void)setActivateMsgFlag;
- (id)toData;
- (void)updateImprint:(id)imprint;
- (void)writeIdTracking;
@end

