/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary, NSString;

@interface MobClickCheckUpdate : XXUnknownSuperclass {
	NSString* _appHomeUrl;
	NSString* _updateTitle;
	NSString* _updateCancelButtonTitle;
	NSString* _updateOtherButtonTitles;
	id _updateDelegate;
	SEL _appUpdateSelector;
	NSMutableDictionary* _updateInfo;
	BOOL _checkUpdateJobFlag;
}
@property(copy, nonatomic) NSString* appHomeUrl;
@property(assign, nonatomic) SEL appUpdateSelector;
@property(copy, nonatomic) NSString* updateCancelButtonTitle;
@property(assign, nonatomic) id updateDelegate;
@property(retain, nonatomic) NSMutableDictionary* updateInfo;
@property(copy, nonatomic) NSString* updateOtherButtonTitles;
@property(copy, nonatomic) NSString* updateTitle;
+ (id)sharedInstance;
- (id)init;
- (void)alertView:(id)view clickedButtonAtIndex:(int)index;
- (void)appUpdateWithAlert:(id)alert;
- (BOOL)checkAppUpdate:(id)update;
- (void)checkAppUpdateResult;
- (void)checkUpdate;
- (void)checkUpdate:(id)update cancelButtonTitle:(id)title otherButtonTitles:(id)titles;
- (void)checkUpdateWithDelegate:(id)delegate selector:(SEL)selector;
- (void)dealloc;
- (id)description;
- (void)excuteUpdate:(id)update;
- (id)getData:(id)data error:(id*)error;
- (void)gotAppkey;
- (id)setAppUpdateData;
- (void)toggleCheckUpdateJobFlag;
@end

