/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface MobClickSession : XXUnknownSuperclass {
	BOOL _observerAdded;
	BOOL _firstStartSessionHasFinished;
	BOOL _launchHasBegan;
	BOOL _appInBackGround;
	BOOL _appBeKilling;
	double _duration;
}
@property(assign, nonatomic) BOOL appBeKilling;
@property(assign, nonatomic) BOOL appInBackGround;
@property(assign, nonatomic) BOOL firstStartSessionHasFinished;
@property(assign, nonatomic) BOOL launchHasBegan;
@property(assign, nonatomic) BOOL observerAdded;
+ (void)postGotAppkeyNotification;
+ (id)sharedInstance;
+ (void)startSession:(id)session;
+ (void)startWithAppkey:(id)appkey;
+ (void)startWithAppkey:(id)appkey reportPolicy:(int)policy channelId:(id)anId;
+ (void)stopSession:(id)session;
+ (int)updateReportPolicy:(int)policy;
- (void)_appLaunch;
- (void)_appTerminate;
- (void)addObserverForSession;
- (void)addObservers;
- (void)appLaunch;
- (void)appTerminate;
- (id)description;
- (void)ensureFirstLaunch;
- (void)startSession:(id)session;
- (void)stopSession:(id)session;
@end

