/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSDictionary;

@interface MobClickSocialWeibo : XXUnknownSuperclass {
	NSString* _platformType;
	NSString* _weiboId;
	NSString* _userId;
	NSDictionary* _param;
}
@property(retain, nonatomic) NSDictionary* param;
@property(copy, nonatomic) NSString* platformType;
@property(copy, nonatomic) NSString* userId;
@property(copy, nonatomic) NSString* weiboId;
- (id)initWithPlatformType:(id)platformType weiboId:(id)anId usid:(id)usid param:(id)param;
- (id)description;
@end

