/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface Model_PlayModel : XXUnknownSuperclass {
	bool _needLoop;
	NSString* _name;
	NSString* _filePath;
	NSString* _itemCategory;
	NSString* _displayText;
	NSString* _translationText;
	int _status;
	int _itemtype;
	int _itemid;
}
@property(retain, nonatomic) NSString* displayText;
@property(retain, nonatomic) NSString* filePath;
@property(retain, nonatomic) NSString* itemCategory;
@property(assign) int itemid;
@property(assign) int itemtype;
@property(retain, nonatomic) NSString* name;
@property(assign) bool needLoop;
@property(assign) int status;
@property(retain, nonatomic) NSString* translationText;
- (id)init;
- (void).cxx_destruct;
@end

