/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSMutableArray;

__attribute__((visibility("hidden")))
@interface Model_db_ListenSpeakLesson : XXUnknownSuperclass {
	int _CId;
	int _episodeId;
	NSString* _JSONContent;
	int _proficient;
	int _status;
	int _LessonId;
	NSString* _STitle;
	NSString* _TTitle;
	NSString* _Translation;
	NSString* _CategoryName;
	NSString* _PublishDate;
	NSMutableArray* _SentList;
	int _CategoryType;
	int _LevelType;
}
@property(assign, nonatomic) int CId;
@property(retain, nonatomic) NSString* CategoryName;
@property(assign) int CategoryType;
@property(retain, nonatomic) NSString* JSONContent;
@property(assign) int LessonId;
@property(assign) int LevelType;
@property(retain, nonatomic) NSString* PublishDate;
@property(retain, nonatomic) NSString* STitle;
@property(retain, nonatomic) NSMutableArray* SentList;
@property(retain, nonatomic) NSString* TTitle;
@property(retain, nonatomic) NSString* Translation;
@property(assign) int episodeId;
@property(assign) int proficient;
@property(assign) int status;
- (id)init;
- (id)initWithDict:(id)dict;
- (void).cxx_destruct;
@end

