/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface Model_Survival_item : XXUnknownSuperclass {
	int _cid;
	int _sid;
	NSString* _eng_item;
	NSString* _chn_item;
	NSString* _pinyin;
}
@property(retain, nonatomic) NSString* chn_item;
@property(assign, nonatomic) int cid;
@property(retain, nonatomic) NSString* eng_item;
@property(retain, nonatomic) NSString* pinyin;
@property(assign, nonatomic) int sid;
- (void).cxx_destruct;
@end

