/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface Model_db_sentence050 : XXUnknownSuperclass {
	int _Index;
	int _SentenceId;
	NSString* _Options;
	NSString* _Answer;
	long _Version;
	NSString* _DataUId;
}
@property(retain, nonatomic) NSString* Answer;
@property(retain, nonatomic) NSString* DataUId;
@property(assign) int Index;
@property(retain, nonatomic) NSString* Options;
@property(assign) int SentenceId;
@property(assign, nonatomic) long Version;
- (id)init;
- (void).cxx_destruct;
@end

