/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSMutableArray;

__attribute__((visibility("hidden")))
@interface Model_db_lesson : XXUnknownSuperclass {
	int _LessonId;
	NSString* _LessonName;
	NSString* _Description;
	NSString* _TDescription;
	NSString* _WordListString;
	NSString* _SentenceListString;
	NSString* _CharacterListString;
	NSString* _NewRegexString;
	NSString* _NormalRegexString;
	int _LevelId;
	int _UnitId;
	int _SortIndex;
	long _Version;
	NSString* _DataUId;
	NSMutableArray* _m_wordList;
	NSMutableArray* _m_sentenceList;
	NSMutableArray* _m_characterList;
	NSMutableArray* _m_NormalRegexList;
}
@property(retain, nonatomic) NSString* CharacterListString;
@property(retain, nonatomic) NSString* DataUId;
@property(retain, nonatomic) NSString* Description;
@property(assign, nonatomic) int LessonId;
@property(retain, nonatomic) NSString* LessonName;
@property(assign, nonatomic) int LevelId;
@property(retain, nonatomic) NSString* NewRegexString;
@property(retain, nonatomic) NSString* NormalRegexString;
@property(retain, nonatomic) NSString* SentenceListString;
@property(assign, nonatomic) int SortIndex;
@property(retain, nonatomic) NSString* TDescription;
@property(assign, nonatomic) int UnitId;
@property(assign, nonatomic) long Version;
@property(retain, nonatomic) NSString* WordListString;
@property(retain, nonatomic) NSMutableArray* m_NormalRegexList;
@property(retain, nonatomic) NSMutableArray* m_characterList;
@property(retain, nonatomic) NSMutableArray* m_sentenceList;
@property(retain, nonatomic) NSMutableArray* m_wordList;
- (id)init;
- (void).cxx_destruct;
@end

