/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface Model_wordreview : XXUnknownSuperclass {
	BOOL _isDownloaded;
	int _WordId;
	NSString* _SWord;
	NSString* _TWord;
	NSString* _Pinyin;
	NSString* _Translations;
	NSString* _Explanation;
	NSString* _Audio;
	NSString* _MainPic;
	NSString* _Images;
	NSString* _DirCode;
	NSString* _Lessons;
	int _WordType;
	int _Status;
	int _Proficient;
}
@property(retain, nonatomic) NSString* Audio;
@property(retain, nonatomic) NSString* DirCode;
@property(retain, nonatomic) NSString* Explanation;
@property(retain, nonatomic) NSString* Images;
@property(retain, nonatomic) NSString* Lessons;
@property(retain, nonatomic) NSString* MainPic;
@property(retain, nonatomic) NSString* Pinyin;
@property(assign) int Proficient;
@property(retain, nonatomic) NSString* SWord;
@property(assign) int Status;
@property(retain, nonatomic) NSString* TWord;
@property(retain, nonatomic) NSString* Translations;
@property(assign) int WordId;
@property(assign) int WordType;
@property(assign) BOOL isDownloaded;
- (id)init;
- (void).cxx_destruct;
@end

