/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface Model_db_level : XXUnknownSuperclass {
	int _LevelId;
	NSString* _LevelName;
	NSString* _Description;
	NSString* _UnitList;
	int _SortIndex;
	long _Version;
	NSString* _DataUId;
	NSString* _TestOutList;
}
@property(retain, nonatomic) NSString* DataUId;
@property(retain, nonatomic) NSString* Description;
@property(assign) int LevelId;
@property(retain, nonatomic) NSString* LevelName;
@property(assign) int SortIndex;
@property(retain, nonatomic) NSString* TestOutList;
@property(retain, nonatomic) NSString* UnitList;
@property(assign, nonatomic) long Version;
- (id)init;
- (void).cxx_destruct;
@end

