/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSMutableArray;

__attribute__((visibility("hidden")))
@interface Model_db_sentence : XXUnknownSuperclass {
	int _SentenceId;
	NSString* _SSentence;
	NSString* _TSentence;
	NSString* _WordListString;
	NSString* _Translations;
	NSString* _Audio;
	NSString* _DirCode;
	NSString* _Lessons;
	NSMutableArray* _WordList;
	long _Version;
	NSString* _DataUId;
}
@property(copy, nonatomic) NSString* Audio;
@property(copy, nonatomic) NSString* DataUId;
@property(copy, nonatomic) NSString* DirCode;
@property(copy, nonatomic) NSString* Lessons;
@property(copy, nonatomic) NSString* SSentence;
@property(assign) int SentenceId;
@property(copy, nonatomic) NSString* TSentence;
@property(copy, nonatomic) NSString* Translations;
@property(assign, nonatomic) long Version;
@property(retain, nonatomic) NSMutableArray* WordList;
@property(copy, nonatomic) NSString* WordListString;
- (id)init;
- (void).cxx_destruct;
- (id)RetrivalSimplifiedChineseSentence;
- (id)RetrivalTranditionalChineseSentence;
@end

