/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface Model_db_word040 : XXUnknownSuperclass {
	int _Index;
	int _WordId;
	NSString* _Answers;
	long _Version;
	NSString* _DataUId;
}
@property(retain, nonatomic) NSString* Answers;
@property(retain, nonatomic) NSString* DataUId;
@property(assign) int Index;
@property(assign, nonatomic) long Version;
@property(assign) int WordId;
- (id)init;
- (void).cxx_destruct;
@end

