/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface Model_db_myword : XXUnknownSuperclass {
	int _WordId;
	int _Status;
	int _Proficient;
	int _LessonId;
}
@property(assign) int LessonId;
@property(assign) int Proficient;
@property(assign) int Status;
@property(assign) int WordId;
- (id)init;
@end

