/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface Model_db_pointget : XXUnknownSuperclass {
	int _Index;
	int _Point;
	NSString* _TimeString;
}
@property(assign) int Index;
@property(assign) int Point;
@property(retain, nonatomic) NSString* TimeString;
- (id)init;
- (void).cxx_destruct;
@end

