/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ChineseSkillNew-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface Model_db_characterpart : XXUnknownSuperclass {
	int _PartId;
	NSString* _PartName;
	NSString* _Description;
	NSString* _ImageName;
	NSString* _DirCode;
	NSString* _StrRect;
	int _SpriteRectRealWidth;
	long _Version;
	NSString* _DataUId;
	CGRect _SpriteRect;
}
@property(retain, nonatomic) NSString* DataUId;
@property(retain, nonatomic) NSString* Description;
@property(retain, nonatomic) NSString* DirCode;
@property(retain, nonatomic) NSString* ImageName;
@property(assign) int PartId;
@property(retain, nonatomic) NSString* PartName;
@property(assign) CGRect SpriteRect;
@property(assign) int SpriteRectRealWidth;
@property(retain, nonatomic) NSString* StrRect;
@property(assign, nonatomic) long Version;
- (id)init;
- (void).cxx_destruct;
- (void)MakeupSpriteRect;
@end

