/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ChineseSkillNew-Structs.h"
#import "MRStopableView.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class CAShapeLayer, MRStopButton, NSString;

@interface MRActivityIndicatorView : XXUnknownSuperclass <MRStopableView> {
	BOOL _animating;
	BOOL _hidesWhenStopped;
	MRStopButton* _stopButton;
	CAShapeLayer* _shapeLayer;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) BOOL hidesWhenStopped;
@property(assign, nonatomic) float lineWidth;
@property(assign, nonatomic) BOOL mayStop;
@property(assign, nonatomic) __weak CAShapeLayer* shapeLayer;
@property(assign, nonatomic) __weak MRStopButton* stopButton;
@property(readonly, assign) Class superclass;
+ (void)load;
- (id)initWithCoder:(id)coder;
- (id)initWithFrame:(CGRect)frame;
- (void).cxx_destruct;
- (void)addAnimation;
- (void)applicationDidEnterBackground:(id)application;
- (void)applicationWillEnterForeground:(id)application;
- (void)commonInit;
- (void)dealloc;
- (BOOL)isAnimating;
- (id)layoutPath;
- (void)layoutSubviews;
- (void)registerForNotificationCenter;
- (void)removeAnimation;
- (void)startAnimating;
- (void)stopAnimating;
- (void)tintColorDidChange;
- (void)unregisterFromNotificationCenter;
@end

