/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MTLValueTransformer.h"


@interface MTLReversibleValueTransformer : MTLValueTransformer {
}
+ (BOOL)allowsReverseTransformation;
- (id)initWithForwardBlock:(id)forwardBlock reverseBlock:(id)block;
- (id)reverseTransformedValue:(id)value;
@end

