/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@protocol myDelegate;

__attribute__((visibility("hidden")))
@interface OneWelcomeBaseViewController : XXUnknownSuperclass {
	id<myDelegate> _delegate;
}
@property(retain, nonatomic) id<myDelegate> delegate;
- (id)initWithNibName:(id)nibName bundle:(id)bundle;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)setAndShowData:(int)data;
- (void)viewDidLoad;
@end

