/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OneWelcomeBaseViewController.h"

@class UIButton;

__attribute__((visibility("hidden")))
@interface OneWelcome1ViewController : OneWelcomeBaseViewController {
	UIButton* _CreateButton;
}
@property(assign, nonatomic) __weak UIButton* CreateButton;
- (id)initWithNibName:(id)nibName bundle:(id)bundle;
- (void).cxx_destruct;
- (void)EnterButtonClick:(id)click;
- (void)didReceiveMemoryWarning;
- (void)setAndShowData:(int)data;
- (void)viewDidLoad;
@end

