/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AVAudioPlayerDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary, NSString, AVAudioPlayer;

__attribute__((visibility("hidden")))
@interface PlayInRepeatModel : XXUnknownSuperclass <AVAudioPlayerDelegate> {
	BOOL _isPlaying;
	BOOL _stopped;
	NSMutableDictionary* _m_auidoDict;
	AVAudioPlayer* _m_avPlayer;
	int _nCurPlay;
	int _nTotalPlay;
	int _nCurPlayTimes;
	int _nRepeatTimes;
	int _itemtype;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) unsigned hash;
@property(assign) BOOL isPlaying;
@property(assign) int itemtype;
@property(retain, nonatomic) NSMutableDictionary* m_auidoDict;
@property(retain, nonatomic) AVAudioPlayer* m_avPlayer;
@property(assign) int nCurPlay;
@property(assign) int nCurPlayTimes;
@property(assign) int nRepeatTimes;
@property(assign) int nTotalPlay;
@property(assign) BOOL stopped;
@property(readonly, assign) Class superclass;
+ (id)sharedOperator;
- (id)init;
- (void).cxx_destruct;
- (void)AddOnePlayModel:(id)model DeleteOther:(BOOL)other;
- (void)BeginPlayFirstAuido;
- (void)BeginPlayNextAuido;
- (void)ClearPlayList;
- (id)RetrivalCurrentAuidoSubTitle;
- (id)RetrivalCurrentAuidoSubTitleTranslation;
- (void)Start;
- (void)StopAudioPlay;
- (void)audioPlayerDidFinishPlaying:(id)audioPlayer successfully:(BOOL)successfully;
- (void)playNextAudioWithDelay;
@end

