/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UITextFieldDelegate.h"
#import "ChineseSkillNew-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSURLConnection, NSMutableData, NSString, UIButton, UIActivityIndicatorView, UITextField;

__attribute__((visibility("hidden")))
@interface ResetPasswordViewController : XXUnknownSuperclass <UITextFieldDelegate> {
	UITextField* _oldPasswordLabel;
	UITextField* _passwordLabel;
	UITextField* _confirmPWLabel;
	NSURLConnection* _connection;
	NSMutableData* _feedXML;
	UIButton* _confirmBtn;
	UIActivityIndicatorView* _activityView;
}
@property(assign, nonatomic) __weak UIActivityIndicatorView* activityView;
@property(assign, nonatomic) __weak UIButton* confirmBtn;
@property(assign, nonatomic) __weak UITextField* confirmPWLabel;
@property(retain, nonatomic) NSURLConnection* connection;
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(retain, nonatomic) NSMutableData* feedXML;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) __weak UITextField* oldPasswordLabel;
@property(assign, nonatomic) __weak UITextField* passwordLabel;
@property(readonly, assign) Class superclass;
- (void).cxx_destruct;
- (id)GetValueFromSettingDB:(id)settingDB;
- (void)backBtn:(id)btn;
- (void)confirmBtn:(id)btn;
- (void)connection:(id)connection didFailWithError:(id)error;
- (void)connection:(id)connection didReceiveData:(id)data;
- (void)connection:(id)connection didReceiveResponse:(id)response;
- (void)connectionDidFinishLoading:(id)connection;
- (void)didReceiveMemoryWarning;
- (void)handleError:(id)error;
- (void)resetSuccess;
- (void)viewDidLoad;
@end

