/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary, NSTimer, NSMutableArray;

__attribute__((visibility("hidden")))
@interface ResumeFileDownloadWrapper : XXUnknownSuperclass {
	BOOL priorityMap_mutex_lock;
	BOOL filesList_mutex_lock;
	BOOL _errorDLDict_mutex_lock;
	NSMutableArray* downloaderArray;
	NSMutableDictionary* priorityMap;
	NSTimer* downloadTimer;
	int nCurMaxPriority;
	NSMutableArray* filesList;
	NSMutableDictionary* _errorDLDict;
}
@property(retain, nonatomic) NSTimer* downloadTimer;
@property(retain, nonatomic) NSMutableArray* downloaderArray;
@property(retain, nonatomic) NSMutableDictionary* errorDLDict;
@property(assign, nonatomic) BOOL errorDLDict_mutex_lock;
@property(retain, nonatomic) NSMutableArray* filesList;
@property(assign, nonatomic) BOOL filesList_mutex_lock;
@property(assign) int nCurMaxPriority;
@property(retain, nonatomic) NSMutableDictionary* priorityMap;
@property(assign, nonatomic) BOOL priorityMap_mutex_lock;
+ (id)sharedDownLoader;
- (id)init;
- (void).cxx_destruct;
- (void)AppendOneErrorDLModel:(id)model;
- (void)RemoveOneParamFromDLDict:(id)dldict;
- (void)RemoveOneParamFromPriorityMap:(id)priorityMap;
- (BOOL)addOneQueueToDownload:(id)download;
- (void)addOneQueueToDownload_AllMaterials:(id)download_AllMaterials;
- (BOOL)addOneQueueToDownload_MaxPriority:(id)download_MaxPriority;
- (void)addOneQueueToDownload_Pinyin:(id)download_Pinyin;
- (void)addOneQueueToDownload_SurvialChinese:(id)download_SurvialChinese;
- (void)dealloc;
- (float)downloadListenSpeakStatusWithEpisodeId:(int)episodeId;
- (float)downloadStatusWithCharId:(int)charId;
- (float)downloadStatusWithSentenceId:(int)sentenceId;
- (float)downloadStatusWithSurvivalCHNCId:(int)survivalCHNCId;
- (float)downloadStatusWithWordId:(int)wordId;
- (float)downloadStatusWithZipPartName:(id)zipPartName;
- (BOOL)isFileExistListenSpeakWithEpisodeId:(int)episodeId;
- (BOOL)isFileExistWithCharId:(int)charId;
- (BOOL)isFileExistWithSentenceId:(int)sentenceId;
- (BOOL)isFileExistWithSurvivalCId:(int)survivalCId;
- (BOOL)isFileExistWithWordId:(int)wordId;
- (BOOL)isFileExistWithZipPartName:(id)zipPartName;
- (BOOL)isFindInErrorDLDict:(id)errorDLDict;
- (BOOL)isModelInSubmitQueue:(id)submitQueue;
- (void)letMyQueueMaxPriority:(int)priority;
- (void)removeOneFileToLanuchDownload;
@end

