/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface STHTTPRequestFileUpload : XXUnknownSuperclass {
	NSString* _path;
	NSString* _parameterName;
	NSString* _mimeType;
}
@property(retain, nonatomic) NSString* mimeType;
@property(retain, nonatomic) NSString* parameterName;
@property(retain, nonatomic) NSString* path;
+ (id)fileUploadWithPath:(id)path parameterName:(id)name;
+ (id)fileUploadWithPath:(id)path parameterName:(id)name mimeType:(id)type;
- (void).cxx_destruct;
@end

