/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol STTwitterProtocol <NSObject>
@property(assign, nonatomic) double timeoutInSeconds;
@optional
- (id)bearerToken;
@required
- (BOOL)canVerifyCredentials;
- (id)consumerName;
- (id)fetchResource:(id)resource HTTPMethod:(id)method baseURLString:(id)string parameters:(id)parameters uploadProgressBlock:(id)block downloadProgressBlock:(id)block6 successBlock:(id)block7 errorBlock:(id)block8;
@optional
- (void)invalidateBearerTokenWithSuccessBlock:(id)successBlock errorBlock:(id)block;
@required
- (id)loginTypeDescription;
@optional
- (id)oauthAccessToken;
- (id)oauthAccessTokenSecret;
- (void)postAccessTokenRequestWithPIN:(id)pin successBlock:(id)block errorBlock:(id)block3;
- (void)postReverseAuthAccessTokenWithAuthenticationHeader:(id)authenticationHeader successBlock:(id)block errorBlock:(id)block3;
- (void)postReverseOAuthTokenRequest:(id)request errorBlock:(id)block;
- (void)postTokenRequest:(id)request authenticateInsteadOfAuthorize:(BOOL)authorize forceLogin:(id)login screenName:(id)name oauthCallback:(id)callback errorBlock:(id)block;
@required
- (void)verifyCredentialsWithSuccessBlock:(id)successBlock errorBlock:(id)block;
@end

