/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ChineseSkillNew-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface TBXML : XXUnknownSuperclass {
	TBXMLElement* rootXMLElement;
	TBXMLElementBuffer* currentElementBuffer;
	TBXMLAttributeBuffer* currentAttributeBuffer;
	long currentElement;
	long currentAttribute;
	char* bytes;
	long bytesLength;
}
@property(readonly, assign, nonatomic) TBXMLElement* rootXMLElement;
+ (id)attributeName:(TBXMLAttribute*)name;
+ (id)attributeName:(TBXMLAttribute*)name error:(id*)error;
+ (id)attributeValue:(TBXMLAttribute*)value;
+ (id)attributeValue:(TBXMLAttribute*)value error:(id*)error;
+ (TBXMLElement*)childElementNamed:(id)named parentElement:(TBXMLElement*)element;
+ (TBXMLElement*)childElementNamed:(id)named parentElement:(TBXMLElement*)element error:(id*)error;
+ (id)elementName:(TBXMLElement*)name;
+ (id)elementName:(TBXMLElement*)name error:(id*)error;
+ (id)errorTextForCode:(int)code;
+ (id)errorWithCode:(int)code;
+ (id)errorWithCode:(int)code userInfo:(id)info;
+ (void)iterateAttributesOfElement:(TBXMLElement*)element withBlock:(id)block;
+ (void)iterateElementsForQuery:(id)query fromElement:(TBXMLElement*)element withBlock:(id)block;
+ (TBXMLElement*)nextSiblingNamed:(id)named searchFromElement:(TBXMLElement*)element;
+ (TBXMLElement*)nextSiblingNamed:(id)named searchFromElement:(TBXMLElement*)element error:(id*)error;
+ (id)tbxmlWithURL:(id)url success:(id)success failure:(id)failure;
+ (id)tbxmlWithXMLData:(id)xmldata;
+ (id)tbxmlWithXMLData:(id)xmldata error:(id*)error;
+ (id)tbxmlWithXMLFile:(id)xmlfile;
+ (id)tbxmlWithXMLFile:(id)xmlfile error:(id*)error;
+ (id)tbxmlWithXMLFile:(id)xmlfile fileExtension:(id)extension;
+ (id)tbxmlWithXMLFile:(id)xmlfile fileExtension:(id)extension error:(id*)error;
+ (id)tbxmlWithXMLString:(id)xmlstring;
+ (id)tbxmlWithXMLString:(id)xmlstring error:(id*)error;
+ (id)textForElement:(TBXMLElement*)element;
+ (id)textForElement:(TBXMLElement*)element error:(id*)error;
+ (id)valueOfAttributeNamed:(id)attributeNamed forElement:(TBXMLElement*)element;
+ (id)valueOfAttributeNamed:(id)attributeNamed forElement:(TBXMLElement*)element error:(id*)error;
- (id)init;
- (id)initWithURL:(id)url success:(id)success failure:(id)failure;
- (id)initWithXMLData:(id)xmldata;
- (id)initWithXMLData:(id)xmldata error:(id*)error;
- (id)initWithXMLFile:(id)xmlfile;
- (id)initWithXMLFile:(id)xmlfile error:(id*)error;
- (id)initWithXMLFile:(id)xmlfile fileExtension:(id)extension;
- (id)initWithXMLFile:(id)xmlfile fileExtension:(id)extension error:(id*)error;
- (id)initWithXMLString:(id)xmlstring;
- (id)initWithXMLString:(id)xmlstring error:(id*)error;
- (void)allocateBytesOfLength:(long)length error:(id*)error;
- (void)dealloc;
- (void)decodeBytes;
- (void)decodeData:(id)data;
- (void)decodeData:(id)data withError:(id*)error;
- (TBXMLAttribute*)nextAvailableAttribute;
- (TBXMLElement*)nextAvailableElement;
@end

