/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MBProgressHUDDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIButton, NSMutableArray, NSMutableDictionary, UISegmentedControl, NSTimer, UILabel, NSString, MBProgressHUD, UIImageView, UIActivityIndicatorView, UITextField;

__attribute__((visibility("hidden")))
@interface TempImportDataViewController : XXUnknownSuperclass <MBProgressHUDDelegate> {
	UIButton* _doneButton;
	UIActivityIndicatorView* _activity;
	UILabel* _outStringLabel;
	UISegmentedControl* _languageSegment;
	MBProgressHUD* _LoadAuidoHUD;
	UIImageView* _wordMainPic;
	UILabel* _wordName;
	UIButton* _nextImageButton;
	UITextField* _IPTextField;
	UIButton* _confirmNewIPButton;
	NSMutableDictionary* _m_wordmap;
	NSMutableArray* _allWordList;
	NSTimer* _timerToAutoUpdateTitle;
	int _nCurWordIndex;
}
@property(assign, nonatomic) __weak UITextField* IPTextField;
@property(retain, nonatomic) MBProgressHUD* LoadAuidoHUD;
@property(assign, nonatomic) __weak UIActivityIndicatorView* activity;
@property(retain, nonatomic) NSMutableArray* allWordList;
@property(assign, nonatomic) __weak UIButton* confirmNewIPButton;
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(assign, nonatomic) __weak UIButton* doneButton;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) __weak UISegmentedControl* languageSegment;
@property(retain, nonatomic) NSMutableDictionary* m_wordmap;
@property(assign) int nCurWordIndex;
@property(assign, nonatomic) __weak UIButton* nextImageButton;
@property(assign, nonatomic) __weak UILabel* outStringLabel;
@property(readonly, assign) Class superclass;
@property(retain, nonatomic) NSTimer* timerToAutoUpdateTitle;
@property(assign, nonatomic) __weak UIImageView* wordMainPic;
@property(assign, nonatomic) __weak UILabel* wordName;
- (id)initWithNibName:(id)nibName bundle:(id)bundle;
- (void).cxx_destruct;
- (void)BackButtonClick:(id)click;
- (void)BeginDownloadAuidoCheck;
- (void)ChangeLanguageSegment:(id)segment;
- (void)DownloadWordPicture:(id)picture;
- (void)DownloadWordPictureCount:(id)count;
- (void)ImportAllData:(id)data;
- (void)InitCurWordImage;
- (void)NewIPConfirma:(id)confirma;
- (void)NextWordImageClick:(id)click;
- (void)OnlyEffectSetup:(id)setup;
- (void)autoUpdateTitle;
- (void)didReceiveMemoryWarning;
- (void)downloadProgressTask;
- (void)viewDidLoad;
@end

