/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "TTransport.h"

@class NSData, NSMutableData, NSURL, NSString, NSMutableURLRequest;

@interface THTTPClient : XXUnknownSuperclass <TTransport> {
	NSURL* mURL;
	NSMutableURLRequest* mRequest;
	NSMutableData* mRequestData;
	NSData* mResponseData;
	int mResponseDataOffset;
	NSString* mUserAgent;
	int mTimeout;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) NSMutableData* mRequestData;
@property(readonly, assign) Class superclass;
- (id)initWithURL:(id)url;
- (id)initWithURL:(id)url userAgent:(id)agent timeout:(int)timeout;
- (void)dealloc;
- (void)flush;
- (int)readAll:(char*)all offset:(int)offset length:(int)length;
- (void)setURL:(id)url;
- (void)setupRequest;
- (void)write:(const char*)write offset:(unsigned)offset length:(unsigned)length;
@end

