/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ChineseSkillNew-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary, NSURL, NSString;

@interface TMDiskCache : XXUnknownSuperclass {
	id _willAddObjectBlock;
	id _willRemoveObjectBlock;
	id _willRemoveAllObjectsBlock;
	id _didAddObjectBlock;
	id _didRemoveObjectBlock;
	id _didRemoveAllObjectsBlock;
	unsigned _byteLimit;
	NSString* _name;
	NSURL* _cacheURL;
	unsigned _byteCount;
	dispatch_queue_s* _queue;
	NSMutableDictionary* _dates;
	NSMutableDictionary* _sizes;
	double _ageLimit;
}
@property(assign) double ageLimit;
@property(assign) unsigned byteCount;
@property(assign) unsigned byteLimit;
@property(retain) NSURL* cacheURL;
@property(retain, nonatomic) NSMutableDictionary* dates;
@property(copy) id didAddObjectBlock;
@property(copy) id didRemoveAllObjectsBlock;
@property(copy) id didRemoveObjectBlock;
@property(readonly, assign) NSString* name;
@property(assign, nonatomic) dispatch_queue_s* queue;
@property(retain, nonatomic) NSMutableDictionary* sizes;
@property(copy) id willAddObjectBlock;
@property(copy) id willRemoveAllObjectsBlock;
@property(copy) id willRemoveObjectBlock;
+ (void)emptyTrash;
+ (BOOL)moveItemAtURLToTrash:(id)trash;
+ (id)sharedCache;
+ (dispatch_queue_s*)sharedQueue;
+ (dispatch_queue_s*)sharedTrashQueue;
+ (id)sharedTrashURL;
- (id)initWithName:(id)name;
- (id)initWithName:(id)name rootPath:(id)path;
- (void).cxx_destruct;
- (BOOL)createCacheDirectory;
- (id)decodedString:(id)string;
- (id)description;
- (id)encodedFileURLForKey:(id)key;
- (id)encodedString:(id)string;
- (void)enumerateObjectsWithBlock:(id)block;
- (void)enumerateObjectsWithBlock:(id)block completionBlock:(id)block2;
- (id)fileURLForKey:(id)key;
- (void)fileURLForKey:(id)key block:(id)block;
- (void)initializeDiskProperties;
- (id)keyForEncodedFileURL:(id)encodedFileURL;
- (id)objectForKey:(id)key;
- (void)objectForKey:(id)key block:(id)block;
- (void)removeAllObjects;
- (void)removeAllObjects:(id)objects;
- (BOOL)removeFileAndExecuteBlocksForKey:(id)key;
- (void)removeObjectForKey:(id)key;
- (void)removeObjectForKey:(id)key block:(id)block;
- (BOOL)setFileModificationDate:(id)date forURL:(id)url;
- (void)setObject:(id)object forKey:(id)key;
- (void)setObject:(id)object forKey:(id)key block:(id)block;
- (void)trimDiskToDate:(id)date;
- (void)trimDiskToSize:(unsigned)size;
- (void)trimDiskToSizeByDate:(unsigned)sizeByDate;
- (void)trimToAgeLimitRecursively;
- (void)trimToDate:(id)date;
- (void)trimToDate:(id)date block:(id)block;
- (void)trimToSize:(unsigned)size;
- (void)trimToSize:(unsigned)size block:(id)block;
- (void)trimToSizeByDate:(unsigned)sizeByDate;
- (void)trimToSizeByDate:(unsigned)sizeByDate block:(id)block;
@end

