/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ChineseSkillNew-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary;

@interface TMMemoryCache : XXUnknownSuperclass {
	BOOL _removeAllObjectsOnMemoryWarning;
	BOOL _removeAllObjectsOnEnteringBackground;
	unsigned _costLimit;
	unsigned _totalCost;
	id _willAddObjectBlock;
	id _willRemoveObjectBlock;
	id _willRemoveAllObjectsBlock;
	id _didAddObjectBlock;
	id _didRemoveObjectBlock;
	id _didRemoveAllObjectsBlock;
	id _didReceiveMemoryWarningBlock;
	id _didEnterBackgroundBlock;
	dispatch_queue_s* _queue;
	NSMutableDictionary* _dictionary;
	NSMutableDictionary* _dates;
	NSMutableDictionary* _costs;
	double _ageLimit;
}
@property(assign) double ageLimit;
@property(assign) unsigned costLimit;
@property(retain, nonatomic) NSMutableDictionary* costs;
@property(retain, nonatomic) NSMutableDictionary* dates;
@property(retain, nonatomic) NSMutableDictionary* dictionary;
@property(copy) id didAddObjectBlock;
@property(copy) id didEnterBackgroundBlock;
@property(copy) id didReceiveMemoryWarningBlock;
@property(copy) id didRemoveAllObjectsBlock;
@property(copy) id didRemoveObjectBlock;
@property(assign) dispatch_queue_s* queue;
@property(assign) BOOL removeAllObjectsOnEnteringBackground;
@property(assign) BOOL removeAllObjectsOnMemoryWarning;
@property(readonly, assign) unsigned totalCost;
@property(copy) id willAddObjectBlock;
@property(copy) id willRemoveAllObjectsBlock;
@property(copy) id willRemoveObjectBlock;
+ (id)sharedCache;
- (id)init;
- (void).cxx_destruct;
- (void)dealloc;
- (void)didObserveApocalypticNotification:(id)notification;
- (void)enumerateObjectsWithBlock:(id)block;
- (void)enumerateObjectsWithBlock:(id)block completionBlock:(id)block2;
- (id)objectForKey:(id)key;
- (void)objectForKey:(id)key block:(id)block;
- (void)removeAllObjects;
- (void)removeAllObjects:(id)objects;
- (void)removeObjectAndExecuteBlocksForKey:(id)key;
- (void)removeObjectForKey:(id)key;
- (void)removeObjectForKey:(id)key block:(id)block;
- (void)setObject:(id)object forKey:(id)key;
- (void)setObject:(id)object forKey:(id)key block:(id)block;
- (void)setObject:(id)object forKey:(id)key withCost:(unsigned)cost;
- (void)setObject:(id)object forKey:(id)key withCost:(unsigned)cost block:(id)block;
- (void)trimMemoryToDate:(id)date;
- (void)trimToAgeLimitRecursively;
- (void)trimToCost:(unsigned)cost;
- (void)trimToCost:(unsigned)cost block:(id)block;
- (void)trimToCostByDate:(unsigned)costByDate;
- (void)trimToCostByDate:(unsigned)costByDate block:(id)block;
- (void)trimToCostLimit:(unsigned)costLimit;
- (void)trimToCostLimitByDate:(unsigned)costLimitByDate;
- (void)trimToDate:(id)date;
- (void)trimToDate:(id)date block:(id)block;
@end

