/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TException.h"


__attribute__((objc_exception))
@interface TProtocolException : TException {
}
@end

