/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TProcessorFactory.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;
@protocol TProcessor;

@interface TSharedProcessorFactory : XXUnknownSuperclass <TProcessorFactory> {
	id<TProcessor> mSharedProcessor;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) unsigned hash;
@property(readonly, assign) Class superclass;
- (id)initWithSharedProcessor:(id)sharedProcessor;
- (void)dealloc;
- (id)processorForTransport:(id)transport;
@end

