/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary, NSString;

@interface UICKeyChainStore : XXUnknownSuperclass {
	NSMutableDictionary* itemsToUpdate;
	NSString* _service;
	NSString* _accessGroup;
}
@property(readonly, assign, nonatomic) NSString* accessGroup;
@property(readonly, assign, nonatomic) NSString* service;
+ (id)dataForKey:(id)key;
+ (id)dataForKey:(id)key service:(id)service;
+ (id)dataForKey:(id)key service:(id)service accessGroup:(id)group;
+ (id)defaultService;
+ (id)itemsForService:(id)service accessGroup:(id)group;
+ (id)keyChainStore;
+ (id)keyChainStoreWithService:(id)service;
+ (id)keyChainStoreWithService:(id)service accessGroup:(id)group;
+ (BOOL)removeAllItems;
+ (BOOL)removeAllItemsForService:(id)service;
+ (BOOL)removeAllItemsForService:(id)service accessGroup:(id)group;
+ (BOOL)removeItemForKey:(id)key;
+ (BOOL)removeItemForKey:(id)key service:(id)service;
+ (BOOL)removeItemForKey:(id)key service:(id)service accessGroup:(id)group;
+ (BOOL)setData:(id)data forKey:(id)key;
+ (BOOL)setData:(id)data forKey:(id)key service:(id)service;
+ (BOOL)setData:(id)data forKey:(id)key service:(id)service accessGroup:(id)group;
+ (void)setDefaultService:(id)service;
+ (BOOL)setString:(id)string forKey:(id)key;
+ (BOOL)setString:(id)string forKey:(id)key service:(id)service;
+ (BOOL)setString:(id)string forKey:(id)key service:(id)service accessGroup:(id)group;
+ (id)stringForKey:(id)key;
+ (id)stringForKey:(id)key service:(id)service;
+ (id)stringForKey:(id)key service:(id)service accessGroup:(id)group;
- (id)init;
- (id)initWithService:(id)service;
- (id)initWithService:(id)service accessGroup:(id)group;
- (void).cxx_destruct;
- (id)dataForKey:(id)key;
- (id)description;
- (id)objectForKeyedSubscript:(id)keyedSubscript;
- (void)removeAllItems;
- (void)removeItemForKey:(id)key;
- (void)setData:(id)data forKey:(id)key;
- (void)setObject:(id)object forKeyedSubscript:(id)keyedSubscript;
- (void)setString:(id)string forKey:(id)key;
- (id)stringForKey:(id)key;
- (void)synchronize;
@end

