/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface UMANUtil : XXUnknownSuperclass {
}
+ (id)JSONFragment:(id)fragment;
+ (id)JSONValue:(id)value;
+ (id)accessString;
+ (id)appDisplayNameString;
+ (id)appPackageNameString;
+ (id)appPirateString;
+ (id)appShortVersionString;
+ (id)appVersionString;
+ (id)bytesToHexString:(char*)hexString length:(int)length;
+ (id)carrierString;
+ (id)countryString;
+ (id)dateString;
+ (id)deflatedData:(id)data;
+ (id)deflatedDataPrefixedWith:(id)with level:(int)level source:(id)source;
+ (id)deviceJailBreakString;
+ (id)deviceMacAddressString;
+ (id)deviceModelString;
+ (id)getString:(id)string bytesLength:(int)length;
+ (id)idfv;
+ (BOOL)isAppPirate;
+ (BOOL)isDebugging;
+ (BOOL)isDeviceJailBreak;
+ (BOOL)isPad;
+ (id)languageString;
+ (id)md5:(id)a5;
+ (char*)md5BytesWithString:(id)string;
+ (id)md5DataWithData:(id)data;
+ (id)openUDIDString;
+ (id)osString;
+ (id)osVersionString;
+ (int)resolutionHeight;
+ (id)resolutionString;
+ (int)resolutionWidth;
+ (id)returnCheck:(id)check;
+ (id)sdkTypeString;
+ (id)sdkVersionString;
+ (id)sessionId;
+ (id)sha1WithData:(id)data;
+ (id)sha1WithString:(id)string;
+ (id)timeString;
+ (int)timezone;
+ (id)timezoneString;
+ (id)umStringDecode:(id)decode;
+ (id)urlEncode:(id)encode;
@end

