/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSCoding.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary, NSString;

@interface UMTImprint : XXUnknownSuperclass <NSCoding> {
	NSMutableDictionary* __property;
	int __version;
	NSString* __checksum;
	BOOL __property_isset;
	BOOL __version_isset;
	BOOL __checksum_isset;
}
@property(retain, nonatomic, getter=checksum, setter=setChecksum:) NSString* checksum;
@property(retain, nonatomic, getter=property, setter=setProperty:) NSMutableDictionary* property;
@property(assign, nonatomic, getter=version, setter=setVersion:) int version;
- (id)init;
- (id)initWithCoder:(id)coder;
- (id)initWithProperty:(id)property version:(int)version checksum:(id)checksum;
- (BOOL)checksumIsSet;
- (void)dealloc;
- (id)description;
- (void)encodeWithCoder:(id)coder;
- (BOOL)propertyIsSet;
- (void)read:(id)read;
- (void)unsetChecksum;
- (void)unsetProperty;
- (void)unsetVersion;
- (BOOL)versionIsSet;
- (void)write:(id)write;
@end

