/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSCoding.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, UMTTraffic, NSMutableArray;

@interface UMTSession : XXUnknownSuperclass <NSCoding> {
	NSString* __id;
	long long __start_time;
	long long __end_time;
	long long __duration;
	NSMutableArray* __pages;
	NSMutableArray* __locations;
	UMTTraffic* __traffic;
	BOOL __id_isset;
	BOOL __start_time_isset;
	BOOL __end_time_isset;
	BOOL __duration_isset;
	BOOL __pages_isset;
	BOOL __locations_isset;
	BOOL __traffic_isset;
}
@property(assign, nonatomic, getter=duration, setter=setDuration:) long long duration;
@property(assign, nonatomic, getter=end_time, setter=setEnd_time:) long long end_time;
@property(retain, nonatomic, getter=id, setter=setId:) NSString* id;
@property(retain, nonatomic, getter=locations, setter=setLocations:) NSMutableArray* locations;
@property(retain, nonatomic, getter=pages, setter=setPages:) NSMutableArray* pages;
@property(assign, nonatomic, getter=start_time, setter=setStart_time:) long long start_time;
@property(retain, nonatomic, getter=traffic, setter=setTraffic:) UMTTraffic* traffic;
- (id)init;
- (id)initWithCoder:(id)coder;
- (id)initWithId:(id)anId start_time:(long long)time end_time:(long long)time3 duration:(long long)duration pages:(id)pages locations:(id)locations traffic:(id)traffic;
- (void)dealloc;
- (id)description;
- (BOOL)durationIsSet;
- (void)encodeWithCoder:(id)coder;
- (BOOL)end_timeIsSet;
- (BOOL)idIsSet;
- (BOOL)locationsIsSet;
- (BOOL)pagesIsSet;
- (void)read:(id)read;
- (BOOL)start_timeIsSet;
- (BOOL)trafficIsSet;
- (void)unsetDuration;
- (void)unsetEnd_time;
- (void)unsetId;
- (void)unsetLocations;
- (void)unsetPages;
- (void)unsetStart_time;
- (void)unsetTraffic;
- (void)write:(id)write;
@end

