/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSCoding.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface UMTTraffic : XXUnknownSuperclass <NSCoding> {
	int __upload_traffic;
	int __download_traffic;
	BOOL __upload_traffic_isset;
	BOOL __download_traffic_isset;
}
@property(assign, nonatomic, getter=download_traffic, setter=setDownload_traffic:) int download_traffic;
@property(assign, nonatomic, getter=upload_traffic, setter=setUpload_traffic:) int upload_traffic;
- (id)init;
- (id)initWithCoder:(id)coder;
- (id)initWithUpload_traffic:(int)upload_traffic download_traffic:(int)traffic;
- (void)dealloc;
- (id)description;
- (BOOL)download_trafficIsSet;
- (void)encodeWithCoder:(id)coder;
- (void)read:(id)read;
- (void)unsetDownload_traffic;
- (void)unsetUpload_traffic;
- (BOOL)upload_trafficIsSet;
- (void)write:(id)write;
@end

