/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, UserStatisticsPayloadModel;

__attribute__((visibility("hidden")))
@interface UserStatistics : XXUnknownSuperclass {
	int _currentPlayBtnType;
	NSString* _userGuid;
	int _seq;
	UserStatisticsPayloadModel* _payloadModel;
	double _VCStartTime;
	double _appStartTime;
	double _appBackgroundTime;
	double _testStartTime;
	double _testDuration;
	double _backgroundBegin;
	double _AchievementVCPlayTime;
}
@property(assign, nonatomic) double AchievementVCPlayTime;
@property(assign, nonatomic) double VCStartTime;
@property(assign, nonatomic) double appBackgroundTime;
@property(assign, nonatomic) double appStartTime;
@property(assign, nonatomic) double backgroundBegin;
@property(assign, nonatomic) int currentPlayBtnType;
@property(retain, nonatomic) UserStatisticsPayloadModel* payloadModel;
@property(assign, nonatomic) int seq;
@property(assign, nonatomic) double testDuration;
@property(assign, nonatomic) double testStartTime;
@property(retain, nonatomic) NSString* userGuid;
+ (void)clearUserGuidFromNSUserDefaults;
+ (id)deviceModleWithCustomDevieceID:(int)customDevieceID;
+ (int)getCustomDeviceID;
+ (int)getCustomDeviceIDID;
+ (id)sharedOperator;
- (void).cxx_destruct;
- (id)GetEmailFromSettingDB;
- (id)GetLoginTypeFromSettingDB;
- (void)VCDidAppear;
- (void)VCDidDisAppearWithName:(id)vc;
- (void)appEnterBackground;
- (void)appEnterForeground;
- (void)appStart;
- (void)appTerminate;
- (double)getDuration:(double)duration;
- (id)getUID;
- (id)getUserGuid;
- (void)oneTestPayloadStatWithModel:(id)model WithTestType:(int)testType;
- (void)oneTestStart;
- (void)reviewAudioBeginPlayEventWithPlayType:(int)playType;
- (void)reviewAudioPlayStopped;
- (void)reviewAudioStopped:(id)stopped time:(double)time;
- (void)testWriteToFile:(id)file withPayloadMode:(id)payloadMode;
- (void)writeToFile:(id)file;
@end

