/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIScrollViewDelegate.h"
#import "myDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "ChineseSkillNew-Structs.h"

@class NSString, UIScrollView, NSArray, UIPageControl, NSMutableArray;

__attribute__((visibility("hidden")))
@interface WelcomeViewController : XXUnknownSuperclass <UIScrollViewDelegate, myDelegate> {
	BOOL _forward;
	BOOL _backward;
	BOOL _pageControlUsed;
	UIScrollView* _scrollView;
	UIPageControl* _pageControl;
	NSMutableArray* _controllersList;
	NSArray* _pageList;
	int _indexPage;
}
@property(assign) BOOL backward;
@property(retain, nonatomic) NSMutableArray* controllersList;
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(assign) BOOL forward;
@property(readonly, assign) unsigned hash;
@property(assign) int indexPage;
@property(assign, nonatomic) __weak UIPageControl* pageControl;
@property(assign) BOOL pageControlUsed;
@property(retain, nonatomic) NSArray* pageList;
@property(assign, nonatomic) __weak UIScrollView* scrollView;
@property(readonly, assign) Class superclass;
- (id)initWithNibName:(id)nibName bundle:(id)bundle;
- (void).cxx_destruct;
- (void)BeginApp:(id)app;
- (void)PopupCreateAccountView;
- (void)PopupSignInView;
- (void)PopupSignInWithFacebook;
- (void)changePage:(id)page;
- (void)didReceiveMemoryWarning;
- (void)loadScrollViewWithPage:(int)page;
- (void)scrollViewDidEndDecelerating:(id)scrollView;
- (void)scrollViewDidScroll:(id)scrollView;
- (void)scrollViewWillBeginDragging:(id)scrollView;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
- (void)viewDidLoad;
- (void)viewDidUnload;
- (void)viewWillAppear:(BOOL)view;
- (void)viewWillDisappear:(BOOL)view;
@end

