/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIScrollView, VerticallyAlignedLabel, UIButton, Model_db_word;
@protocol myDelegate;

__attribute__((visibility("hidden")))
@interface WordExplainPoperViewController : XXUnknownSuperclass {
	id<myDelegate> _delegate;
	VerticallyAlignedLabel* _inforLabel;
	UIButton* _GoItButton;
	Model_db_word* _m_data;
	UIScrollView* _scrollView;
}
@property(assign, nonatomic) __weak UIButton* GoItButton;
@property(retain, nonatomic) id<myDelegate> delegate;
@property(assign, nonatomic) __weak VerticallyAlignedLabel* inforLabel;
@property(retain, nonatomic) Model_db_word* m_data;
@property(retain, nonatomic) UIScrollView* scrollView;
- (id)initWithNibName:(id)nibName bundle:(id)bundle;
- (void).cxx_destruct;
- (void)GoitClick:(id)click;
- (void)InitModelData:(id)data;
- (void)didReceiveMemoryWarning;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)view;
- (void)viewWillDisappear:(BOOL)view;
@end

