/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSXMLParserDelegate.h"
#import "ChineseSkillNew-Structs.h"
#import "NSCopying.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary, NSString, NSMutableString, NSMutableArray;

@interface XMLDictionaryParser : XXUnknownSuperclass <NSXMLParserDelegate, NSCopying> {
	BOOL _collapseTextNodes;
	BOOL _stripEmptyNodes;
	BOOL _trimWhiteSpace;
	BOOL _alwaysUseArrays;
	BOOL _preserveComments;
	BOOL _wrapRootNode;
	int _attributesMode;
	int _nodeNameMode;
	NSMutableDictionary* _root;
	NSMutableArray* _stack;
	NSMutableString* _text;
}
@property(assign, nonatomic) BOOL alwaysUseArrays;
@property(assign, nonatomic) int attributesMode;
@property(assign, nonatomic) BOOL collapseTextNodes;
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) int nodeNameMode;
@property(assign, nonatomic) BOOL preserveComments;
@property(retain, nonatomic) NSMutableDictionary* root;
@property(retain, nonatomic) NSMutableArray* stack;
@property(assign, nonatomic) BOOL stripEmptyNodes;
@property(readonly, assign) Class superclass;
@property(retain, nonatomic) NSMutableString* text;
@property(assign, nonatomic) BOOL trimWhiteSpace;
@property(assign, nonatomic) BOOL wrapRootNode;
+ (id)XMLStringForNode:(id)node withNodeName:(id)nodeName;
+ (id)sharedInstance;
- (id)init;
- (void).cxx_destruct;
- (void)addText:(id)text;
- (id)copyWithZone:(NSZone*)zone;
- (id)dictionaryWithData:(id)data;
- (id)dictionaryWithFile:(id)file;
- (id)dictionaryWithParser:(id)parser;
- (id)dictionaryWithString:(id)string;
- (void)endText;
- (id)nameForNode:(id)node inDictionary:(id)dictionary;
- (void)parser:(id)parser didEndElement:(id)element namespaceURI:(id)uri qualifiedName:(id)name;
- (void)parser:(id)parser didStartElement:(id)element namespaceURI:(id)uri qualifiedName:(id)name attributes:(id)attributes;
- (void)parser:(id)parser foundCDATA:(id)cdata;
- (void)parser:(id)parser foundCharacters:(id)characters;
- (void)parser:(id)parser foundComment:(id)comment;
@end

