/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ChineseSkillNew-Structs.h"
#import "CSLSAddedTableView.h"
#import "UIGestureRecognizerDelegate.h"

@class NSIndexPath, UIButton, UISwipeGestureRecognizer, UITapGestureRecognizer, NSString;

__attribute__((visibility("hidden")))
@interface YFJLeftSwipeDeleteTableView : CSLSAddedTableView <UIGestureRecognizerDelegate> {
	UISwipeGestureRecognizer* _leftGestureRecognizer;
	UISwipeGestureRecognizer* _rightGestureRecognizer;
	UITapGestureRecognizer* _tapGestureRecognizer;
	UIButton* _deleteButton;
	NSIndexPath* _editingIndexPath;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) unsigned hash;
@property(readonly, assign) Class superclass;
- (id)initWithFrame:(CGRect)frame;
- (id)initWithFrame:(CGRect)frame style:(int)style;
- (void).cxx_destruct;
- (id)cellIndexPathForGestureRecognizer:(id)gestureRecognizer;
- (void)deleteItem:(id)item;
- (BOOL)gestureRecognizer:(id)recognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)gestureRecognizer;
- (void)setEditing:(BOOL)editing atIndexPath:(id)indexPath cell:(id)cell;
- (void)swiped:(id)swiped;
- (void)tapped:(id)tapped;
@end

